/**
 * 체험용 예시 메일함(기획서 §14 1단계, §17).
 *
 * 실제 Gmail·한메일은 아직 붙지 않았다. OAuth 와 IMAP 이 붙기 전에도 분류·
 * 중요도·요약·삭제 후보 검토를 **사람이 손으로 돌려 볼 수 있어야** 하므로,
 * 목회자의 실제 받은편지함과 비슷한 모양의 메일을 만들어 둔다.
 *
 * 시각은 고정하지 않고 `now` 에서 거슬러 만든다. 날짜를 박아 두면 며칠만
 * 지나도 「30일 지난 반복 알림」 같은 판정이 전부 한쪽으로 쏠린다.
 */

import type { DemoMail } from '@/lib/emailOrganizer';

const GMAIL = 'gmail-demo';
const HANMAIL = 'hanmail-demo';

export const DEMO_ACCOUNTS: {
  id: string;
  provider: 'gmail' | 'hanmail';
  address: string;
  label: string;
  color: string;
}[] = [
  { id: GMAIL, provider: 'gmail', address: 'dicipleofjx2@gmail.com', label: 'Gmail', color: '#BC5C35' },
  { id: HANMAIL, provider: 'hanmail', address: 'davidbible@hanmail.net', label: '한메일', color: '#6E8C99' },
];

type Seed = Omit<DemoMail, 'receivedAt'> & { daysAgo: number; hour: number };

const SEEDS: Seed[] = [
  {
    id: 'm1',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '새부대교회 김요한 목사',
    fromAddress: 'john@saebudae.church',
    subject: '주일 설교 순서 확인 부탁드립니다',
    body:
      '목사님, 평안하신지요.\n이번 주일 예배 설교 순서를 확인해 주시기 바랍니다.\n일시: 3월 9일 오전 11시\n장소: 새부대교회 본당\n오늘까지 회신해 주시면 주보에 넣겠습니다.',
    read: false,
    attachments: [],
    threadId: 't1',
    contactScore: 24,
    daysAgo: 0,
    hour: 8,
  },
  {
    id: 'm2',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '국세청 홈택스',
    fromAddress: 'noreply@hometax.go.kr',
    subject: '[국세청] 부가가치세 신고 안내',
    body:
      '2026년 1기 부가가치세 신고 기간을 안내드립니다.\n신고 기한은 7월 25일까지입니다.\n납부 세액은 452,000원입니다.\n기한 내 신고하지 않으면 가산세가 부과됩니다.',
    read: false,
    attachments: ['부가세안내.pdf'],
    threadId: 't2',
    contactScore: 4,
    daysAgo: 1,
    hour: 9,
  },
  {
    id: 'm3',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '한빛초등학교',
    fromAddress: 'office@hanbit.sch.kr',
    subject: '가정통신문 - 학부모 상담 주간 안내',
    body:
      '학부모 상담 주간을 안내드립니다.\n기간: 3월 16일 ~ 3월 20일\n담임 선생님과의 상담 시간을 3월 12일까지 신청해 주세요.\n장소: 각 교실',
    read: false,
    attachments: ['가정통신문.hwp'],
    threadId: 't3',
    contactScore: 6,
    daysAgo: 2,
    hour: 15,
  },
  {
    id: 'm4',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '서울노회 사무국',
    fromAddress: 'office@presbytery-seoul.org',
    subject: '노회 정기회 참석 여부 회신 요청',
    body:
      '노회 정기회를 아래와 같이 개최합니다.\n일시: 4월 2일 오전 10시\n장소: 서울제일교회 교육관\n참석 여부를 3월 25일까지 알려주세요.\n안건 자료는 첨부를 확인하시기 바랍니다.',
    read: false,
    attachments: ['정기회안건.pdf'],
    threadId: 't4',
    contactScore: 11,
    daysAgo: 2,
    hour: 11,
  },
  {
    id: 'm5',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '태국 치앙마이 박선교사',
    fromAddress: 'park.mission@gmw.kr',
    subject: '선교 후원 보고와 기도 부탁',
    body:
      '목사님, 주님의 은혜가 함께하시기를 빕니다.\n지난달 현지 성도 세 가정이 새로 예배에 나왔습니다.\n후원금 500,000원 잘 받았습니다. 영수증은 첨부합니다.\n다음 달 수련회를 위해 기도 부탁드립니다.',
    read: true,
    attachments: ['후원영수증.pdf'],
    threadId: 't5',
    contactScore: 18,
    daysAgo: 3,
    hour: 21,
  },
  {
    id: 'm6',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '쿠팡',
    fromAddress: 'promotion@coupang-mail.com',
    subject: '[광고] 오늘만 최대 70% 할인 기획전',
    body: '봄맞이 특가 기획전이 열렸습니다.\n쿠폰을 받고 무료배송 혜택을 누리세요.\n마감임박 상품을 확인해 보세요.',
    read: false,
    attachments: [],
    threadId: 't6',
    unsubscribeUrl: 'https://example.com/unsubscribe/coupang',
    contactScore: 0,
    openedCount: 0,
    daysAgo: 1,
    hour: 10,
  },
  {
    id: 'm7',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '쿠팡',
    fromAddress: 'promotion@coupang-mail.com',
    subject: '[광고] 놓치면 후회할 주말 특가',
    body: '주말 한정 특가 세일입니다.\n적립금 5,000원을 드립니다.',
    read: false,
    attachments: [],
    threadId: 't7',
    unsubscribeUrl: 'https://example.com/unsubscribe/coupang',
    contactScore: 0,
    openedCount: 0,
    daysAgo: 4,
    hour: 10,
  },
  {
    id: 'm8',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '쿠팡',
    fromAddress: 'promotion@coupang-mail.com',
    subject: '[광고] 이번 주 쿠폰이 도착했습니다',
    body: '이번 주 쿠폰과 프로모션 안내입니다.\n최저가 상품을 모았습니다.',
    read: false,
    attachments: [],
    threadId: 't8',
    unsubscribeUrl: 'https://example.com/unsubscribe/coupang',
    contactScore: 0,
    openedCount: 0,
    daysAgo: 9,
    hour: 10,
  },
  {
    id: 'm9',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '쿠팡',
    fromAddress: 'promotion@coupang-mail.com',
    subject: '[광고] 신상품 입고 안내',
    body: '신상품이 입고되었습니다.\n할인 쿠폰을 함께 드립니다.',
    read: false,
    attachments: [],
    threadId: 't9',
    unsubscribeUrl: 'https://example.com/unsubscribe/coupang',
    contactScore: 0,
    openedCount: 0,
    daysAgo: 14,
    hour: 10,
  },
  {
    id: 'm10',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '쿠팡',
    fromAddress: 'promotion@coupang-mail.com',
    subject: '[광고] 봄 세일 마지막 날',
    body: '봄 세일이 오늘 끝납니다.\n특가 상품을 서두르세요.',
    read: false,
    attachments: [],
    threadId: 't10',
    unsubscribeUrl: 'https://example.com/unsubscribe/coupang',
    contactScore: 0,
    openedCount: 0,
    daysAgo: 20,
    hour: 10,
  },
  {
    id: 'm11',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '삼성화재',
    fromAddress: 'notice@samsungfire.life.co.kr',
    subject: '보험료 자동이체 결과 안내',
    body: '3월분 보험료 128,400원이 정상 출금되었습니다.\n계약 내용은 변동이 없습니다.',
    read: true,
    attachments: [],
    threadId: 't11',
    contactScore: 3,
    daysAgo: 6,
    hour: 7,
  },
  {
    id: 'm12',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: 'YouTube',
    fromAddress: 'noreply@youtube.com',
    subject: '채널 주간 리포트가 도착했습니다',
    body: '지난주 채널 통계 요약입니다.\n조회수와 구독자 변화를 확인하세요.',
    read: true,
    attachments: [],
    threadId: 't12',
    unsubscribeUrl: 'https://example.com/unsubscribe/youtube',
    contactScore: 1,
    openedCount: 3,
    daysAgo: 5,
    hour: 6,
  },
  {
    id: 'm13',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: 'Google',
    fromAddress: 'no-reply@accounts.google.com',
    subject: '새로운 기기에서 로그인 알림',
    body: '새 기기에서 계정에 로그인했습니다.\n본인이 맞다면 별도 조치가 필요하지 않습니다.',
    read: true,
    attachments: [],
    threadId: 't13',
    contactScore: 0,
    daysAgo: 41,
    hour: 3,
  },
  {
    id: 'm14',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: 'CJ대한통운',
    fromAddress: 'noreply@cjlogistics.com',
    subject: '배송이 완료되었습니다',
    body: '주문하신 상품의 배송이 완료되었습니다.\n수령 확인 부탁드립니다.',
    read: true,
    attachments: [],
    threadId: 't14',
    contactScore: 0,
    daysAgo: 38,
    hour: 17,
  },
  {
    id: 'm15',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '보안팀',
    fromAddress: 'security@hanmai1-service.com',
    subject: '계정이 정지될 예정입니다. 즉시 확인하지 않으면 삭제됩니다',
    body: '고객님의 계정이 정지될 예정입니다.\n본인 확인이 필요하니 지금 클릭하여 비밀번호를 입력해 주세요.',
    read: false,
    attachments: [],
    threadId: 't15',
    contactScore: 0,
    daysAgo: 1,
    hour: 2,
  },
  {
    id: 'm16',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '이하늘 집사',
    fromAddress: 'haneul@example.com',
    subject: '심방 일정 문의드립니다',
    body:
      '목사님, 어머니께서 병원에 입원하셔서 심방을 부탁드리고 싶습니다.\n3월 11일 오후 3시쯤 가능하신지요?\n장소: 서울성모병원 7층',
    read: false,
    attachments: [],
    threadId: 't16',
    contactScore: 9,
    daysAgo: 0,
    hour: 20,
  },
  {
    id: 'm17',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '교육부 세미나 사무국',
    fromAddress: 'seminar@edu-forum.kr',
    subject: '다음세대 교육 세미나 자료집을 보내드립니다',
    body: '세미나 발표 자료집과 제안서를 첨부합니다.\n필요하신 자료가 더 있으면 알려주세요.',
    read: true,
    attachments: ['자료집.pdf', '제안서.docx'],
    threadId: 't17',
    contactScore: 2,
    daysAgo: 7,
    hour: 13,
  },
  {
    id: 'm18',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '다음메일 고객센터',
    fromAddress: 'notice@daum.net',
    subject: '서비스 이용약관 변경 안내',
    body: '이용약관이 4월 1일부터 변경됩니다.\n변경된 정책을 확인해 주시기 바랍니다.',
    read: true,
    attachments: [],
    threadId: 't18',
    contactScore: 0,
    daysAgo: 12,
    hour: 10,
  },
  {
    id: 'm19',
    accountId: GMAIL,
    provider: 'gmail',
    fromName: '새부대교회 김요한 목사',
    fromAddress: 'john@saebudae.church',
    subject: 'RE: 주일 설교 순서 확인 부탁드립니다',
    body: '말씀하신 대로 순서를 수정했습니다.\n주보 인쇄는 토요일 오전에 넘기겠습니다.',
    read: true,
    attachments: [],
    threadId: 't1',
    contactScore: 24,
    daysAgo: 0,
    hour: 12,
  },
  {
    id: 'm20',
    accountId: HANMAIL,
    provider: 'hanmail',
    fromName: '국민은행',
    fromAddress: 'noreply@kbstar.com',
    subject: '카드 이용 대금 명세서',
    body: '3월 카드 이용 대금은 1,240,000원입니다.\n결제일은 3월 25일입니다.',
    read: false,
    attachments: [],
    threadId: 't20',
    contactScore: 2,
    daysAgo: 4,
    hour: 8,
  },
];

export function buildSampleMailbox(now: Date = new Date()): DemoMail[] {
  return SEEDS.map(({ daysAgo, hour, ...mail }) => {
    const d = new Date(now.getTime() - daysAgo * 86_400_000);
    d.setHours(hour, (mail.id.length * 7) % 60, 0, 0);
    return { ...mail, receivedAt: d.toISOString() };
  }).sort((a, b) => Date.parse(b.receivedAt) - Date.parse(a.receivedAt));
}
