import type { Question } from './types';

/** 대의 파악 문항 (주장/요지/주제/제목). 전부 자체 제작 — 기획서 §4.4 참고. */

const ORIGINAL = { status: 'original', label: '자체 제작 수능형 문항', reviewedBy: '미검수' } as const;

export const GIST_QUESTIONS: Question[] = [
  {
    id: 'claim-1',
    type: 'claim',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 80,
    source: ORIGINAL,
    instruction: '다음 글에서 필자가 주장하는 바로 가장 적절한 것은?',
    passage: [
      'Many schools measure reading by counting the number of books a student finishes.',
      'The count is easy to record, and it makes progress look clear on a chart.',
      'But a student who races through twenty thin books may never have stopped to ask what a single sentence meant.',
      'Reading grows when a reader slows down, returns to a difficult page, and argues with the writer.',
      'Teachers should therefore ask students to bring one paragraph they could not settle, rather than a list of titles.',
      'What we count is what students will practice.',
    ],
    choices: [
      { id: 1, text: '독서량보다 깊이 있게 읽는 과정을 평가해야 한다.' },
      { id: 2, text: '학생들이 더 많은 책을 읽도록 독려해야 한다.', whyWrong: '필자가 문제 삼는 것이 바로 권수 늘리기다.', cause: 'logic' },
      { id: 3, text: '독서 기록표를 정확하게 관리해야 한다.', whyWrong: '기록의 편리함은 통념으로 제시된 것이지 주장이 아니다.', cause: 'strategy' },
      { id: 4, text: '어려운 책을 학년별로 지정해 주어야 한다.', whyWrong: '책의 난이도 지정은 언급되지 않았다.', cause: 'careless' },
      { id: 5, text: '읽기 지도를 교사가 아닌 학생에게 맡겨야 한다.', whyWrong: '오히려 교사가 무엇을 요구할지를 말하고 있다.', cause: 'logic' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '통념(권수로 재기) → 그 편리함 → 반박(빨리 읽으면 남는 게 없다) → 대안 → 요구(교사는 문단 하나를 물어라)',
    hint: 'should 가 들어간 문장을 찾으세요. 주장은 행동 요구입니다.',
    explanation:
      'But 앞은 통념, 뒤가 필자의 생각이다. 주장은 should 가 붙은 다섯 번째 문장 — 제목 목록 대신 해결하지 못한 문단 하나를 가져오게 하라는 것. 마지막 문장은 그 이유를 압축한 것이다. ②는 지문이 반박하는 통념이므로 대의 파악에서 가장 흔한 함정이다.',
    rule: '주장 문제는 should·must·명령문이 붙은 문장을 먼저 찾고, But 앞의 통념은 지운다.',
    keyVocab: [
      { word: 'race through', meaning: '~을 서둘러 해치우다' },
      { word: 'settle', meaning: '해결하다, 매듭짓다', note: '「정착하다」 외에 「문제를 매듭짓다」로 자주 쓰인다.' },
      { word: 'measure', meaning: '재다, 평가하다' },
    ],
    keySyntax: [
      {
        sentence:
          'But a student who races through twenty thin books may never have stopped to ask what a single sentence meant.',
        chunks: ['But a student', 'who races through twenty thin books', 'may never have stopped', 'to ask what a single sentence meant.'],
        translation: '그러나 얇은 책 스무 권을 서둘러 해치우는 학생은 한 문장이 무슨 뜻인지 물으려고 멈춰 선 적이 한 번도 없을 수 있다.',
        point: '주어(a student)와 동사(may have stopped) 사이에 관계절이 길게 끼어 있다. 관계절을 괄호에 넣고 주어-동사를 먼저 잇는다.',
      },
    ],
  },
  {
    id: 'claim-2',
    type: 'claim',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 80,
    source: ORIGINAL,
    variantOf: 'claim-1',
    instruction: '다음 글에서 필자가 주장하는 바로 가장 적절한 것은?',
    passage: [
      'When a city plans a new park, it usually asks residents to vote on a finished design.',
      'By then the paths, the trees, and the budget have already been decided by a small team.',
      'Residents can only say yes or no to something they had no part in shaping.',
      'Real participation begins earlier, when the question is still open: what should this ground be for?',
      'Planners must bring residents in before the first drawing is made, not after.',
      'A vote at the end is not consultation; it is approval.',
    ],
    choices: [
      { id: 1, text: '공원 설계는 전문가에게 맡겨야 한다.', whyWrong: '전문가 소수가 정하는 지금의 방식을 문제 삼고 있다.', cause: 'logic' },
      { id: 2, text: '주민 투표 절차를 더 자주 열어야 한다.', whyWrong: '투표 횟수가 아니라 참여 시점이 문제다.', cause: 'strategy' },
      { id: 3, text: '주민 참여는 설계 도면을 그리기 전에 시작되어야 한다.' },
      { id: 4, text: '공원 예산을 늘려야 한다.', whyWrong: '예산은 이미 정해진 것들의 예로 한 번 나왔을 뿐이다.', cause: 'careless' },
      { id: 5, text: '도시마다 공원의 수를 늘려야 한다.', whyWrong: '공원의 수는 화제가 아니다.', cause: 'careless' },
    ],
    answer: 3,
    evidenceIndex: 4,
    structureLine: '현행(완성된 설계에 투표) → 그 한계 → 진짜 참여의 정의 → 요구(도면 전에 부르라) → 마무리 대조',
    hint: 'must 가 붙은 문장과 그 안의 before / not after 를 보세요.',
    explanation:
      'Planners must bring residents in before the first drawing is made, not after 가 주장이다. 마지막 문장 A vote at the end is not consultation; it is approval 은 그 주장을 다시 못박는 대조 문장이다. 주장은 대개 must/should 문장과 마지막 한 문장이 같은 말을 두 번 한다.',
    rule: '주장 문제는 「무엇을 하라」가 아니라 「언제·어떻게 하라」까지 담긴 선택지를 고른다.',
    keyVocab: [
      { word: 'consultation', meaning: '의견을 구하는 일, 협의' },
      { word: 'shape', meaning: '(모양을) 만들어 가다' },
      { word: 'approval', meaning: '승인' },
    ],
    keySyntax: [
      {
        sentence: 'Real participation begins earlier, when the question is still open: what should this ground be for?',
        chunks: ['Real participation begins earlier,', 'when the question is still open:', 'what should this ground be for?'],
        translation: '진정한 참여는 더 이르게, 질문이 아직 열려 있을 때 시작된다 — 이 땅은 무엇을 위한 곳이어야 하는가?',
        point: '콜론(:) 뒤는 앞말을 풀어 주는 자리다. 여기서는 「열려 있는 질문」이 무엇인지 그대로 보여 준다.',
      },
    ],
  },
  {
    id: 'mainIdea-1',
    type: 'mainIdea',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 80,
    source: ORIGINAL,
    instruction: '다음 글의 요지로 가장 적절한 것은?',
    passage: [
      'A map that showed every tree, wall, and puddle would be as hard to use as the city itself.',
      'Maps work because they throw things away.',
      'The subway diagram in your pocket has wrong distances and impossible straight lines, yet it answers the only question a rider asks: which train, and where do I change?',
      'A good model is not the one closest to reality but the one that drops what the user does not need.',
      'The skill, then, lies in choosing what to leave out.',
    ],
    choices: [
      { id: 1, text: '좋은 모형은 현실을 최대한 그대로 담아야 한다.', whyWrong: '지문이 정면으로 부정하는 말이다.', cause: 'logic' },
      { id: 2, text: '좋은 모형은 사용자에게 필요 없는 것을 덜어 낸 것이다.' },
      { id: 3, text: '지하철 노선도는 거리 정보를 정확히 표시해야 한다.', whyWrong: '예시 하나를 요지로 삼았고, 지문은 거리가 틀려도 된다고 했다.', cause: 'strategy' },
      { id: 4, text: '도시를 이해하려면 여러 종류의 지도가 필요하다.', whyWrong: '지도의 가짓수는 화제가 아니다.', cause: 'careless' },
      { id: 5, text: '사용자는 지도의 한계를 알고 사용해야 한다.', whyWrong: '사용자의 태도가 아니라 모형을 만드는 원리를 말한다.', cause: 'strategy' },
    ],
    answer: 2,
    evidenceIndex: 3,
    structureLine: '가정(모든 것을 담은 지도) → 원리(버리기 때문에 쓸모 있다) → 예시(노선도) → 일반화 → 마무리',
    hint: '예시(지하철 노선도) 문장은 괄호에 넣고 앞뒤의 일반화 문장만 읽어 보세요.',
    explanation:
      '네 번째 문장 A good model is not the one closest to reality but the one that drops what the user does not need 가 일반화 문장이고 요지다. not A but B 구조라서 A(현실에 가장 가까운 것)를 요지로 고르면 정확히 반대가 된다. 노선도는 그 원리를 보여 주는 예시일 뿐이다.',
    rule: '요지는 예시 문장이 아니라 그 앞뒤의 일반화 문장에서 고른다.',
    keyVocab: [
      { word: 'puddle', meaning: '물웅덩이' },
      { word: 'drop', meaning: '덜어 내다, 빼다' },
      { word: 'leave out', meaning: '빼놓다, 생략하다' },
    ],
    keySyntax: [
      {
        sentence: 'A good model is not the one closest to reality but the one that drops what the user does not need.',
        chunks: ['A good model is', 'not the one closest to reality', 'but the one', 'that drops what the user does not need.'],
        translation: '좋은 모형이란 현실에 가장 가까운 것이 아니라, 사용자에게 필요 없는 것을 덜어 내는 것이다.',
        point: 'not A but B — B가 필자의 말이다. A만 읽고 답하면 반대로 간다.',
      },
    ],
  },
  {
    id: 'mainIdea-2',
    type: 'mainIdea',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 90,
    source: ORIGINAL,
    variantOf: 'mainIdea-1',
    instruction: '다음 글의 요지로 가장 적절한 것은?',
    passage: [
      'We tend to praise the athlete who trains through pain, as though rest were the opposite of effort.',
      'Physiologists describe the opposite picture: muscle fibers torn during training are rebuilt while the body is still.',
      'Without that quiet interval, the same workload produces smaller and smaller gains.',
      'Sleep researchers report a similar pattern in learning; a skill practiced in the evening improves overnight even without further practice.',
      'Recovery is not the pause between periods of growth, but the period in which growth happens.',
    ],
    choices: [
      { id: 1, text: '휴식은 성장이 멈춘 시간이 아니라 성장이 일어나는 시간이다.' },
      { id: 2, text: '운동선수는 고통을 참고 훈련해야 기량이 는다.', whyWrong: '첫 문장의 통념이며 지문이 뒤집는 말이다.', cause: 'logic' },
      { id: 3, text: '수면 시간을 늘리면 학습 능력이 향상된다.', whyWrong: '수면 연구는 근거의 하나일 뿐, 요지는 회복 일반에 관한 것이다.', cause: 'strategy' },
      { id: 4, text: '훈련량이 많을수록 근섬유가 더 많이 회복된다.', whyWrong: '지문은 오히려 쉬지 않으면 효과가 줄어든다고 했다.', cause: 'logic' },
      { id: 5, text: '운동과 학습은 서로 다른 원리로 향상된다.', whyWrong: '둘이 같은 양상을 보인다는 것이 지문의 논지다.', cause: 'logic' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '통념(쉬는 것은 노력의 반대) → 반박 근거 1(근육) → 그 결과 → 반박 근거 2(학습) → 재정의',
    hint: '마지막 문장 하나가 앞의 모든 근거를 한 문장으로 눌러 담고 있습니다.',
    explanation:
      '마지막 문장 Recovery is not the pause between periods of growth, but the period in which growth happens 가 요지다. 앞의 두 근거(근섬유 재건, 수면 중 기능 향상)는 같은 결론으로 모인다. ③은 근거 하나만 옮긴 것이라 범위가 좁다 — 요지는 지문의 범위를 넘지도, 좁히지도 않아야 한다.',
    rule: '근거가 둘 이상이면 요지는 그것들이 함께 가리키는 한 문장이다.',
    keyVocab: [
      { word: 'physiologist', meaning: '생리학자' },
      { word: 'interval', meaning: '(시간의) 간격' },
      { word: 'gain', meaning: '(능력·성과의) 향상', note: '「이익」보다 여기서는 「향상분」이다.' },
    ],
    keySyntax: [
      {
        sentence: 'Recovery is not the pause between periods of growth, but the period in which growth happens.',
        chunks: ['Recovery is not the pause', 'between periods of growth,', 'but the period', 'in which growth happens.'],
        translation: '회복은 성장의 시기들 사이에 있는 멈춤이 아니라, 성장이 일어나는 바로 그 시기다.',
        point: '전치사 + 관계대명사(in which) — 뒤에 완전한 문장이 온다. 「그 안에서 ~하는」으로 앞 명사에 붙여 읽는다.',
      },
    ],
  },
  {
    id: 'topic-1',
    type: 'topic',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 80,
    source: ORIGINAL,
    instruction: '다음 글의 주제로 가장 적절한 것은?',
    passage: [
      'Street names are usually treated as neutral labels, but they carry the memory of whoever had the power to name.',
      'When a city renames an avenue, old residents keep the former name in speech for decades, and letters arrive addressed to a street that no longer officially exists.',
      'Cartographers must then decide which name to print, and their choice quietly settles an argument that the city council thought it had already closed.',
      'A map, in this sense, is a record of who won the naming.',
    ],
    choices: [
      { id: 1, text: 'the role of maps in urban traffic planning', whyWrong: '교통 계획은 지문에 없다.', cause: 'careless' },
      { id: 2, text: 'street names as a record of power and memory' },
      { id: 3, text: 'the difficulty of designing readable maps', whyWrong: '지도 읽기의 어려움이 아니라 이름의 선택이 화제다.', cause: 'strategy' },
      { id: 4, text: 'why city councils change street names', whyWrong: '개명의 이유는 다루지 않는다. 개명 이후가 화제다.', cause: 'strategy' },
      { id: 5, text: 'the history of postal delivery systems', whyWrong: '편지는 예시로 한 번 나왔을 뿐이다.', cause: 'strategy' },
    ],
    answer: 2,
    evidenceIndex: 0,
    structureLine: '통념(중립적 이름표) → 반박(권력의 기억) → 사례(개명 후에도 남는 옛 이름) → 결론(지도는 명명 싸움의 기록)',
    hint: '핵심어 두 개를 정해 보세요 — 무엇에 대한 글이고, 그것의 어떤 점을 말합니까?',
    explanation:
      '첫 문장이 화제를 못박는다: 거리 이름 = 중립적 이름표가 아니라 명명 권력의 기억. 마지막 문장이 같은 말을 다시 한다. 주제는 「무엇(street names) + 어떤 점(power and memory)」이 모두 맞아야 한다. ④⑤는 지문에 나온 낱말을 담았지만 화제가 다르다.',
    rule: '주제 선택지는 「무엇」과 「어떤 점」으로 쪼개 둘 다 맞는지 확인한다.',
    keyVocab: [
      { word: 'neutral', meaning: '중립적인' },
      { word: 'cartographer', meaning: '지도 제작자' },
      { word: 'settle (an argument)', meaning: '(논쟁을) 매듭짓다' },
    ],
    keySyntax: [
      {
        sentence:
          'Cartographers must then decide which name to print, and their choice quietly settles an argument that the city council thought it had already closed.',
        chunks: ['Cartographers must then decide', 'which name to print,', 'and their choice quietly settles an argument', 'that the city council thought', 'it had already closed.'],
        translation: '그러면 지도 제작자들은 어느 이름을 인쇄할지 정해야 하고, 그 선택은 시의회가 이미 끝냈다고 여긴 논쟁을 조용히 매듭짓는다.',
        point: '관계절 안에 thought 가 끼어든 형태(연쇄 관계절). that 뒤의 주어·동사를 건너뛰고 원래 자리를 찾는다.',
      },
    ],
  },
  {
    id: 'topic-2',
    type: 'topic',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 75,
    source: ORIGINAL,
    variantOf: 'topic-1',
    instruction: '다음 글의 주제로 가장 적절한 것은?',
    passage: [
      'Museums once measured success by how many objects they held.',
      'Storerooms filled with unlabeled crates, and a single curator might be responsible for tens of thousands of items no one had examined in fifty years.',
      'Recently several institutions have begun to publish lists of what they cannot care for, and to return or transfer those objects.',
      'Shrinking a collection, once treated as failure, is now argued to be a condition of caring for what remains.',
    ],
    choices: [
      { id: 1, text: 'why museums compete for famous artworks', whyWrong: '유명 작품 경쟁은 언급되지 않는다.', cause: 'careless' },
      { id: 2, text: 'the rise of digital archives in museums', whyWrong: '디지털화는 지문에 없다.', cause: 'careless' },
      { id: 3, text: 'reducing a collection as a form of care' },
      { id: 4, text: 'the training required to become a curator', whyWrong: '큐레이터는 문제 상황을 보여 주는 예로만 나온다.', cause: 'strategy' },
      { id: 5, text: 'how museums attract younger visitors', whyWrong: '관람객 이야기는 없다.', cause: 'careless' },
    ],
    answer: 3,
    evidenceIndex: 3,
    structureLine: '과거 기준(많이 가질수록 성공) → 그 실상(방치된 수장고) → 변화(감축·반환) → 재해석(감축이 곧 돌봄)',
    hint: '마지막 문장에서 once treated as failure 뒤에 무엇이 온다고 했나요?',
    explanation:
      '마지막 문장이 화제를 확정한다 — 소장품을 줄이는 일이 실패가 아니라 남은 것을 돌보기 위한 조건이라는 것. 주제는 이 재해석 자체이므로 ③. 큐레이터·수장고는 그 전환을 설명하기 위한 배경이다.',
    rule: '「once ~, now ~」로 뒤집히는 글은 뒤쪽이 주제다.',
    keyVocab: [
      { word: 'crate', meaning: '(운반용) 나무 상자' },
      { word: 'transfer', meaning: '(다른 곳으로) 옮기다' },
      { word: 'condition', meaning: '조건', note: '「상태·질환」의 뜻도 있으나 여기서는 「~하기 위한 조건」이다.' },
    ],
    keySyntax: [
      {
        sentence: 'Shrinking a collection, once treated as failure, is now argued to be a condition of caring for what remains.',
        chunks: ['Shrinking a collection,', 'once treated as failure,', 'is now argued to be', 'a condition of caring for what remains.'],
        translation: '한때 실패로 여겨지던, 소장품을 줄이는 일이 이제는 남아 있는 것을 돌보기 위한 조건이라고 이야기된다.',
        point: '주어(동명사구)와 동사(is argued) 사이에 삽입구가 콤마로 끼어 있다. 삽입구를 걷어 내고 주어-동사를 먼저 잇는다.',
      },
    ],
  },
  {
    id: 'title-1',
    type: 'title',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 75,
    source: ORIGINAL,
    instruction: '다음 글의 제목으로 가장 적절한 것은?',
    passage: [
      'A weather forecast that is right nine days out of ten sounds excellent until you ask which day it missed.',
      'If the tenth was the day of the flood, the average tells you nothing you needed.',
      'Forecasters therefore report not one number but a range, and they say how confident they are in it.',
      'Readers dislike this; a range feels like an excuse.',
      'Yet a single number hides exactly the information a decision requires: how wrong it might be.',
    ],
    choices: [
      { id: 1, text: 'Why Forecasts Fail in Extreme Weather', whyWrong: '예보 실패의 원인이 아니라 불확실성을 어떻게 전할지를 말한다.', cause: 'strategy' },
      { id: 2, text: 'One Number Is Not Enough: Reporting Uncertainty' },
      { id: 3, text: 'How to Read a Weather Map', whyWrong: '지도 읽는 법은 나오지 않는다.', cause: 'careless' },
      { id: 4, text: 'The Rising Accuracy of Modern Forecasting', whyWrong: '정확도가 높아졌다는 이야기가 아니다.', cause: 'logic' },
      { id: 5, text: 'Floods and the Cost of Late Warnings', whyWrong: '홍수는 예시로 한 번 나온 세부 내용이다.', cause: 'strategy' },
    ],
    answer: 2,
    evidenceIndex: 4,
    structureLine: '문제 제기(90% 적중의 함정) → 사례(홍수의 날) → 대안(범위와 신뢰도) → 반발 → 반박(하나의 숫자는 필요한 정보를 감춘다)',
    hint: '먼저 요지를 한 문장으로 만들고, 그 문장을 덮는 제목만 남기세요.',
    explanation:
      '요지는 「하나의 숫자는 결정에 필요한 오차 정보를 감추므로 범위와 신뢰도를 함께 전해야 한다」이다. 제목은 그 요지 전체를 덮어야 하므로 ②. ⑤는 지문에 나온 세부 내용을 제목으로 삼은 것으로, 제목 유형에서 가장 잦은 실수다.',
    rule: '제목은 요지를 함축하되 글 전체를 덮어야 한다. 세부 내용은 제목이 될 수 없다.',
    keyVocab: [
      { word: 'forecast', meaning: '예보(하다)' },
      { word: 'range', meaning: '범위, 구간' },
      { word: 'confident', meaning: '확신하는' },
    ],
    keySyntax: [
      {
        sentence: 'Yet a single number hides exactly the information a decision requires: how wrong it might be.',
        chunks: ['Yet a single number hides', 'exactly the information', 'a decision requires:', 'how wrong it might be.'],
        translation: '그러나 하나의 숫자는 결정이 필요로 하는 바로 그 정보를 감춘다 — 그것이 얼마나 틀릴 수 있는가를.',
        point: 'the information (that) a decision requires — 목적격 관계대명사가 생략됐다. 명사 뒤에 「주어+동사」가 바로 오면 생략을 의심한다.',
      },
    ],
  },
  {
    id: 'title-2',
    type: 'title',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 85,
    source: ORIGINAL,
    variantOf: 'title-1',
    instruction: '다음 글의 제목으로 가장 적절한 것은?',
    passage: [
      'Every language loses words, and speakers rarely notice the loss while it happens.',
      'A term for a tool no one uses, or for a distance no one walks, simply stops being said.',
      'Dictionaries record such words long after the practice has gone, which makes them look like a museum of things rather than of doing.',
      'Linguists who study fishing villages find that the vocabulary for tides disappears within a generation of the last working boat.',
      'What a community stops doing, it soon stops being able to say.',
    ],
    choices: [
      { id: 1, text: 'Dictionaries: Guardians of Forgotten Words', whyWrong: '사전은 뒤늦게 기록할 뿐이라는 것이 지문의 지적이다. 오히려 한계를 말한다.', cause: 'logic' },
      { id: 2, text: 'When Practice Ends, Words Follow' },
      { id: 3, text: 'How Fishing Villages Preserve Tradition', whyWrong: '어촌은 근거로 든 사례이고, 보존이 아니라 소멸을 보여 준다.', cause: 'strategy' },
      { id: 4, text: 'The Growth of Technical Vocabulary', whyWrong: '어휘의 증가가 아니라 소멸을 다룬다.', cause: 'logic' },
      { id: 5, text: 'Why Children Learn Words So Quickly', whyWrong: '습득 속도는 화제가 아니다.', cause: 'careless' },
    ],
    answer: 2,
    evidenceIndex: 4,
    structureLine: '현상(말은 소리 없이 사라진다) → 이유(쓰지 않는 것의 이름) → 사전의 한계 → 사례(조수 어휘) → 압축 결론',
    hint: '마지막 한 문장이 제목의 뜻을 그대로 담고 있습니다.',
    explanation:
      '마지막 문장 What a community stops doing, it soon stops being able to say 가 요지이고, ②가 그것을 그대로 옮긴 제목이다. ①은 사전을 긍정적으로 뒤집어 놓았고 ③은 사례를 제목으로 삼았다. 제목 유형은 요지를 먼저 자기 말로 만들어 두면 이런 반전형 오답에 걸리지 않는다.',
    rule: '요지를 먼저 한 문장으로 만든 뒤에 선택지를 본다. 순서를 바꾸면 그럴듯한 문구에 끌린다.',
    keyVocab: [
      { word: 'term', meaning: '용어', note: '「기간·학기」의 뜻도 있다. 여기서는 낱말을 가리킨다.' },
      { word: 'tide', meaning: '조수, 밀물과 썰물' },
      { word: 'generation', meaning: '한 세대' },
    ],
    keySyntax: [
      {
        sentence: 'What a community stops doing, it soon stops being able to say.',
        chunks: ['What a community stops doing,', 'it soon stops being able to say.'],
        translation: '공동체가 하기를 그만둔 것은, 머지않아 말할 수 있기를 그만두게 된다.',
        point: '목적어(What절)가 문장 앞으로 나간 도치. 원래는 it soon stops being able to say what a community stops doing 이다.',
      },
    ],
  },
];
