import type { Question } from './types';

/** 어휘·어법 + 추론 문항. 전부 자체 제작 — 기획서 §4.4 참고.
 *
 * 밑줄 문항은 지문 안에 ①~⑤ 기호를 그대로 넣는다. 화면이 별도의 밑줄
 * 좌표를 관리하지 않아도 되고, 글자 크기를 키워도 표시가 어긋나지 않는다. */

const ORIGINAL = { status: 'original', label: '자체 제작 수능형 문항', reviewedBy: '미검수' } as const;

export const LEXIS_QUESTIONS: Question[] = [
  {
    id: 'vocab-1',
    type: 'vocab',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 85,
    source: ORIGINAL,
    instruction: '다음 글의 밑줄 친 부분 중, 문맥상 낱말의 쓰임이 적절하지 않은 것은?',
    passage: [
      'Noise in an office is rarely loud enough to damage hearing, yet it still ① reduces the quality of work.',
      'The reason is that speech, unlike machine noise, cannot be ② ignored; the brain keeps decoding words it did not ask for.',
      'Workers in open offices therefore report that a quiet conversation two desks away is more ③ disturbing than a printer running beside them.',
      'Designers who understand this stop trying to make rooms silent and instead ④ raise the amount of meaningful speech reaching each desk.',
      'A low, steady background sound that masks words turns out to be more ⑤ helpful than silence itself.',
    ],
    choices: [
      { id: 1, text: '① reduces', whyWrong: '소음이 업무의 질을 「떨어뜨린다」 — 뒤 문장들이 그 이유를 설명한다.', cause: 'logic' },
      { id: 2, text: '② ignored', whyWrong: '말소리는 「무시될 수 없다」가 맞다. 세미콜론 뒤가 그 이유다.', cause: 'syntax' },
      { id: 3, text: '③ disturbing', whyWrong: '조용한 대화가 프린터보다 더 「방해가 된다」 — 앞 문장과 이어진다.', cause: 'logic' },
      { id: 4, text: '④ raise' },
      { id: 5, text: '⑤ helpful', whyWrong: '말을 덮는 배경음이 침묵보다 「도움이 된다」는 마무리다.', cause: 'logic' },
    ],
    answer: 4,
    evidenceIndex: 4,
    structureLine: '현상(소음은 작아도 방해가 된다) → 이유(말소리는 무시할 수 없다) → 사례 → 설계의 대응 → 결론(말을 덮는 소리가 낫다)',
    hint: '마지막 문장이 「말을 덮는 소리」를 권합니다. ④는 그 반대 방향인가요, 같은 방향인가요?',
    explanation:
      '글의 방향은 「알아들을 수 있는 말소리가 방해가 되므로 그것을 줄이거나 덮어야 한다」이다. ④가 든 문장은 설계자들이 무엇을 하는지 말하는 자리인데 raise(늘리다)를 넣으면 마지막 문장(말을 덮는 배경음이 침묵보다 낫다)과 정면으로 어긋난다. reduce/mask 가 들어가야 한다. 어휘 문항은 낱말의 난이도가 아니라 글의 화살표 방향으로 판단한다.',
    rule: '어휘 문항은 먼저 글 전체의 방향을 화살표 하나로 잡고, 밑줄마다 그 방향과 맞는지 본다.',
    keyVocab: [
      { word: 'decode', meaning: '(뜻을) 해독하다' },
      { word: 'mask', meaning: '(소리를) 덮다, 가리다' },
      { word: 'steady', meaning: '일정한, 꾸준한' },
    ],
    keySyntax: [
      {
        sentence: 'The reason is that speech, unlike machine noise, cannot be ignored; the brain keeps decoding words it did not ask for.',
        chunks: ['The reason is', 'that speech,', 'unlike machine noise,', 'cannot be ignored;', 'the brain keeps decoding words', 'it did not ask for.'],
        translation: '그 이유는 말소리가 기계 소음과 달리 무시될 수 없다는 데 있다 — 뇌는 청하지도 않은 낱말을 계속 해독한다.',
        point: '주어(speech)와 동사(cannot be ignored) 사이에 unlike 구가 삽입됐다. 삽입구를 걷어 내야 수동태의 주어가 보인다.',
      },
    ],
  },
  {
    id: 'vocab-2',
    type: 'vocab',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 85,
    source: ORIGINAL,
    variantOf: 'vocab-1',
    instruction: '다음 글의 밑줄 친 부분 중, 문맥상 낱말의 쓰임이 적절하지 않은 것은?',
    passage: [
      'When a species is moved to an island where it has no predators, its population often ① grows far beyond what the land can feed.',
      'Plants that evolved without grazing animals have no thorns and are ② eaten faster than they can regrow.',
      'Within a few decades the soil loses its cover, rain carries it to the sea, and the island becomes ③ poorer than before the animal arrived.',
      'Removing the introduced species later is expensive, and the plants that once held the soil may be too ④ common to return on their own.',
      'Prevention, therefore, costs far ⑤ less than repair.',
    ],
    choices: [
      { id: 1, text: '① grows', whyWrong: '천적이 없으니 개체 수가 「늘어난다」가 맞다.', cause: 'logic' },
      { id: 2, text: '② eaten', whyWrong: '가시가 없으니 「먹힌다」가 맞고, 뒤의 regrow 와 짝을 이룬다.', cause: 'logic' },
      { id: 3, text: '③ poorer', whyWrong: '흙이 쓸려 가면 섬은 「더 척박해진다」.', cause: 'logic' },
      { id: 4, text: '④ common' },
      { id: 5, text: '⑤ less', whyWrong: '예방이 복구보다 「덜」 든다는 마무리다.', cause: 'logic' },
    ],
    answer: 4,
    evidenceIndex: 3,
    structureLine: '도입종 유입 → 식물 훼손 → 토양 유실 → 복구의 어려움 → 결론(예방이 싸다)',
    hint: '스스로 돌아오지 못할 만큼 어떤 상태여야 할까요?',
    explanation:
      '④가 든 문장은 「흙을 붙들던 식물이 스스로 돌아오기에는 너무 ~하다」는 뜻이어야 한다. common(흔한)을 넣으면 흔해서 돌아오지 못한다는 말이 되어 앞뒤가 어긋난다. rare/scarce 가 들어가야 한다. 나머지는 모두 「도입종 → 훼손 → 유실 → 복구난」이라는 한 방향을 따른다.',
    rule: 'too ~ to 구문에 밑줄이 있으면 「그래서 못 한다」가 성립하는 낱말인지 넣어 읽어 본다.',
    keyVocab: [
      { word: 'predator', meaning: '포식자' },
      { word: 'graze', meaning: '(풀을) 뜯어 먹다' },
      { word: 'thorn', meaning: '가시' },
    ],
    keySyntax: [
      {
        sentence: 'Removing the introduced species later is expensive, and the plants that once held the soil may be too rare to return on their own.',
        chunks: ['Removing the introduced species later', 'is expensive,', 'and the plants', 'that once held the soil', 'may be too rare', 'to return on their own.'],
        translation: '나중에 도입종을 없애는 일은 비용이 많이 들고, 한때 흙을 붙들던 식물들은 너무 드물어져 스스로 돌아오지 못할 수 있다.',
        point: '동명사 주어 + too ~ to 부정사. 「너무 …해서 ~할 수 없다」로 붙여 읽는다.',
      },
    ],
  },
  {
    id: 'grammar-1',
    type: 'grammar',
    difficulty: 3,
    vocabLevel: 'high2',
    expectedSeconds: 80,
    source: ORIGINAL,
    instruction: '다음 글의 밑줄 친 부분 중, 어법상 틀린 것은?',
    passage: [
      'The number of volunteers who sign up for the river cleanup ① has risen every spring since 2015.',
      'Most of them are students ② living within walking distance of the bank.',
      'What surprises the organizers ③ are that nearly half return the following year.',
      'The bags of waste ④ collected last April filled two trucks.',
      'The city now provides gloves and water so that no one ⑤ has to bring supplies.',
    ],
    choices: [
      { id: 1, text: '① has risen', whyWrong: '주어가 The number(단수)이므로 has 가 맞다. who절의 volunteers 에 맞추면 틀린다.', cause: 'syntax' },
      { id: 2, text: '② living', whyWrong: 'students 를 뒤에서 꾸미는 현재분사다. 학생들이 사는 것이므로 능동이 맞다.', cause: 'syntax' },
      { id: 3, text: '③ are' },
      { id: 4, text: '④ collected', whyWrong: '쓰레기는 「수거된」 것이므로 과거분사가 맞다.', cause: 'syntax' },
      { id: 5, text: '⑤ has to bring', whyWrong: 'no one 은 단수 취급이다.', cause: 'syntax' },
    ],
    answer: 3,
    evidenceIndex: 2,
    structureLine: '참가자 증가 → 구성 → 재참가율 → 수거량 → 시의 지원',
    hint: '③이 든 문장의 주어는 무엇인가요? What 으로 시작하는 덩어리 전체입니다.',
    explanation:
      'What surprises the organizers 는 관계대명사 what 이 이끄는 명사절 주어이고, 명사절 주어는 단수 취급한다. 따라서 are 가 아니라 is 가 맞다. 뒤에 오는 organizers 나 half 에 수를 맞추면 틀린다. ①도 같은 함정(주어 The number vs 수식어 속 volunteers)이라 두 곳을 함께 보아 두면 좋다.',
    rule: '동사에 밑줄이 있으면 수식어를 걷어 내고 진짜 주어를 먼저 찾는다. 명사절 주어는 단수다.',
    keyVocab: [
      { word: 'organizer', meaning: '주최자' },
      { word: 'supplies', meaning: '물품, 준비물' },
      { word: 'within walking distance', meaning: '걸어갈 만한 거리 안에' },
    ],
    keySyntax: [
      {
        sentence: 'What surprises the organizers is that nearly half return the following year.',
        chunks: ['What surprises the organizers', 'is', 'that nearly half return', 'the following year.'],
        translation: '주최자들을 놀라게 하는 것은 거의 절반이 이듬해에 다시 온다는 점이다.',
        point: '관계대명사 what 절이 주어, that 절이 보어. 주어가 절이면 동사는 단수다.',
      },
    ],
  },
  {
    id: 'grammar-2',
    type: 'grammar',
    difficulty: 4,
    vocabLevel: 'csatBase',
    expectedSeconds: 85,
    source: ORIGINAL,
    variantOf: 'grammar-1',
    instruction: '다음 글의 밑줄 친 부분 중, 어법상 틀린 것은?',
    passage: [
      'Scientists who study memory have long argued about ① whether forgetting is a failure or a feature.',
      'A brain ② storing every detail of every day would spend its energy on information no one needs.',
      'Recent work suggests that the cells ③ which erase weak connections are as active as those that build them.',
      'This is the reason ④ which some researchers now describe forgetting as a kind of editing.',
      'Seen this way, a memory is less a recording than a story ⑤ retold each time it is used.',
    ],
    choices: [
      { id: 1, text: '① whether', whyWrong: 'about 의 목적어로 「~인지 아닌지」를 이끄는 명사절이 맞다.', cause: 'syntax' },
      { id: 2, text: '② storing', whyWrong: '뇌가 저장하는 것이므로 능동의 현재분사가 맞다.', cause: 'syntax' },
      { id: 3, text: '③ which', whyWrong: 'the cells 를 받는 주격 관계대명사이고 뒤 문장에 주어가 빠져 있다. 옳다.', cause: 'syntax' },
      { id: 4, text: '④ which' },
      { id: 5, text: '⑤ retold', whyWrong: '이야기는 「다시 이야기되는」 것이므로 과거분사가 맞다.', cause: 'syntax' },
    ],
    answer: 4,
    evidenceIndex: 3,
    structureLine: '논쟁 제기 → 모두 저장하는 뇌의 낭비 → 지우는 세포도 활발 → 그래서 편집으로 본다 → 기억의 재정의',
    hint: '④ 뒤의 문장에 빠진 자리가 있나요? 주어도 목적어도 다 있다면 관계대명사는 쓸 수 없습니다.',
    explanation:
      '④ 뒤의 some researchers now describe forgetting as a kind of editing 은 주어·동사·목적어가 모두 갖춰진 완전한 문장이다. 완전한 절 앞에는 관계대명사 which 를 쓸 수 없고, the reason 을 받는 관계부사 why(또는 that)가 와야 한다. ③은 뒤에 주어가 비어 있으므로 which 가 맞다 — 두 자리를 비교해 두면 규칙이 몸에 남는다.',
    rule: '관계사에 밑줄이 있으면 뒤 절이 완전한지 먼저 센다. 완전하면 관계부사, 빠진 자리가 있으면 관계대명사다.',
    keyVocab: [
      { word: 'erase', meaning: '지우다' },
      { word: 'connection', meaning: '(신경) 연결' },
      { word: 'retell', meaning: '다시 이야기하다' },
    ],
    keySyntax: [
      {
        sentence: 'Seen this way, a memory is less a recording than a story retold each time it is used.',
        chunks: ['Seen this way,', 'a memory is', 'less a recording', 'than a story', 'retold each time it is used.'],
        translation: '이렇게 보면 기억은 녹음이라기보다 쓰일 때마다 다시 이야기되는 하나의 이야기다.',
        point: '분사구문(Seen this way) + less A than B(「A라기보다 B」). B 뒤에 과거분사구가 또 붙어 있다.',
      },
    ],
  },
  {
    id: 'implied-1',
    type: 'implied',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 95,
    source: ORIGINAL,
    instruction: '밑줄 친 the map is drawn by the walking가 다음 글에서 의미하는 바로 가장 적절한 것은?',
    passage: [
      'Beginners in a new field ask for the outline first: give me the structure, and then I will read.',
      'But an outline is a summary of journeys already made, and it means little to someone who has not made them.',
      'The words in it are the same words the expert uses, yet they point to nothing in the beginner mind.',
      'Understanding arrives the other way round: you read badly, get lost, read again, and only then does the shape appear.',
      'In learning, the map is drawn by the walking.',
    ],
    choices: [
      { id: 1, text: '전체 구조를 먼저 익혀야 세부를 이해할 수 있다', whyWrong: '지문이 부정하는 통념이다. 밑줄은 그 반대를 말한다.', cause: 'logic' },
      { id: 2, text: '직접 헤매며 읽는 경험을 통해서만 전체 구조가 생긴다' },
      { id: 3, text: '전문가의 용어를 외우면 이해가 빨라진다', whyWrong: '같은 낱말을 써도 초보자에게는 가리키는 것이 없다고 했다.', cause: 'logic' },
      { id: 4, text: '학습에는 좋은 안내서가 반드시 필요하다', whyWrong: '요약된 개요의 한계를 말하는 글이다.', cause: 'strategy' },
      { id: 5, text: '길을 잃지 않으려면 미리 계획을 세워야 한다', whyWrong: '밑줄의 walking 을 문자 그대로 읽은 오답이다.', cause: 'vocab' },
    ],
    answer: 2,
    evidenceIndex: 3,
    structureLine: '통념(개요부터 달라) → 반박(개요는 이미 다녀온 길의 요약) → 왜 안 통하나 → 실제 순서(헤매고 나서야 모양이 보인다) → 압축 비유',
    hint: '밑줄을 가리고 네 번째 문장을 읽어 보세요. 밑줄은 그 문장을 한 마디로 줄인 것입니다.',
    explanation:
      '밑줄 바로 앞 문장이 밑줄을 풀어 쓴 자리다 — 잘못 읽고, 길을 잃고, 다시 읽은 뒤에야 모양이 나타난다. 따라서 「걸어감으로써 지도가 그려진다」는 것은 직접 헤매는 경험이 구조를 만든다는 뜻이다. ⑤는 walking 을 사전 뜻 그대로 옮긴 전형적인 함정이다.',
    rule: '함축 의미는 밑줄을 덮고 요지를 만든 뒤, 밑줄을 풀어 쓴 앞뒤 문장을 찾아 확인한다.',
    keyVocab: [
      { word: 'outline', meaning: '개요, 윤곽' },
      { word: 'the other way round', meaning: '그 반대로' },
      { word: 'point to', meaning: '~을 가리키다' },
    ],
    keySyntax: [
      {
        sentence: 'Understanding arrives the other way round: you read badly, get lost, read again, and only then does the shape appear.',
        chunks: ['Understanding arrives the other way round:', 'you read badly,', 'get lost,', 'read again,', 'and only then does the shape appear.'],
        translation: '이해는 그 반대로 온다 — 서툴게 읽고, 길을 잃고, 다시 읽고, 그러고 나서야 비로소 그 모양이 나타난다.',
        point: 'only then 이 문두에 오면 뒤가 도치된다(does the shape appear). 부정·제한어구 도치의 대표형이다.',
      },
    ],
  },
  {
    id: 'implied-2',
    type: 'implied',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 95,
    source: ORIGINAL,
    variantOf: 'implied-1',
    instruction: '밑줄 친 부분이 다음 글에서 의미하는 바로 가장 적절한 것은?',
    passage: [
      'A factory that measures only output will get output, and it will get it from wherever the number can be found.',
      'Maintenance is postponed because a repaired machine produces nothing that week.',
      'Training is skipped because a worker in a classroom is a worker off the line.',
      'None of this is cheating; every decision is exactly what the measure asked for.',
      'A year later the plant is fast and brittle, and managers wonder what went wrong.',
      'The problem was never dishonesty. They were paying for the shadow and expecting the tree.',
    ],
    choices: [
      { id: 1, text: '측정 지표만 보상하면서 그 지표가 나온 실체까지 얻기를 기대했다' },
      { id: 2, text: '직원들이 성과를 조작해 실적을 부풀렸다', whyWrong: '넷째 문장과 마지막에서 부정직의 문제가 아니라고 두 번 못박는다.', cause: 'logic' },
      { id: 3, text: '설비 투자를 늘리면 생산성이 저절로 오른다', whyWrong: '투자 확대는 화제가 아니다.', cause: 'careless' },
      { id: 4, text: '관리자가 현장을 직접 살피지 않아 문제를 놓쳤다', whyWrong: '관리자의 시찰 여부는 언급되지 않는다.', cause: 'careless' },
      { id: 5, text: '생산 속도를 높이면 품질이 반드시 떨어진다', whyWrong: '속도와 품질의 일반 법칙을 말하는 글이 아니다.', cause: 'strategy' },
    ],
    answer: 1,
    evidenceIndex: 3,
    structureLine: '전제(산출만 재면 산출만 온다) → 사례 둘(정비·교육 생략) → 부정직이 아니다 → 결과(빠르지만 부서지기 쉬움) → 압축 비유',
    hint: '그림자(shadow)와 나무(tree)가 이 글에서 각각 무엇에 해당하는지 짝지어 보세요.',
    explanation:
      '그림자는 측정된 숫자, 나무는 그 숫자를 만들어 낸 실제 역량이다. 넷째 문장이 「모든 결정은 지표가 요구한 그대로였다」고 말하므로 문제는 부정직이 아니라 무엇을 보상했는가에 있다. 따라서 ①. ②는 shadow 를 「속임수」로 읽은 오답인데, 지문이 두 번이나 부정하고 있다.',
    rule: '비유가 나오면 그 비유의 두 항이 지문의 무엇에 대응하는지 먼저 짝짓는다.',
    keyVocab: [
      { word: 'postpone', meaning: '미루다' },
      { word: 'brittle', meaning: '부서지기 쉬운' },
      { word: 'off the line', meaning: '생산 라인에서 빠진' },
    ],
    keySyntax: [
      {
        sentence: 'None of this is cheating; every decision is exactly what the measure asked for.',
        chunks: ['None of this is cheating;', 'every decision is', 'exactly what the measure asked for.'],
        translation: '이 중 어느 것도 속임수가 아니다 — 모든 결정은 그 측정 지표가 요구한 바로 그것이었다.',
        point: 'what 명사절이 보어. ask for 의 목적어가 what 으로 빠져나갔다.',
      },
    ],
  },
  {
    id: 'blank-1',
    type: 'blank',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 100,
    source: ORIGINAL,
    instruction: '다음 빈칸에 들어갈 말로 가장 적절한 것은?',
    passage: [
      'Historians of technology often note that a new tool spreads fastest where it is needed least.',
      'The regions that adopted mechanical clocks earliest were not those with the most urgent need to measure time, but those whose towns already kept careful written records.',
      'The same holds for early printing, which took root in cities with dense networks of copyists rather than in places starved of books.',
      'A tool, in other words, is taken up by ______.',
      'Where nothing similar existed, the new device had no hands ready to use it and no habits to attach itself to.',
    ],
    choices: [
      { id: 1, text: 'those who already practice what it makes easier' },
      { id: 2, text: 'the communities that suffer most from its absence', whyWrong: '지문이 정면으로 부정한다 — 가장 절실한 곳에서 먼저 퍼지지 않았다.', cause: 'logic' },
      { id: 3, text: 'governments that can pay for its distribution', whyWrong: '비용이나 정부는 지문에 없다.', cause: 'careless' },
      { id: 4, text: 'inventors who understand its inner workings', whyWrong: '발명가의 이해도는 화제가 아니다.', cause: 'careless' },
      { id: 5, text: 'people who have never seen a similar device', whyWrong: '마지막 문장이 정확히 그 반대를 말한다.', cause: 'logic' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '주장(가장 덜 필요한 곳에서 빨리 퍼진다) → 근거 1(시계) → 근거 2(인쇄) → 일반화(빈칸) → 뒤집어 확인',
    hint: '빈칸 뒤 문장이 「비슷한 것이 없던 곳에서는 …」이라고 했습니다. 그 반대를 쓰면 됩니다.',
    explanation:
      '빈칸 문장은 in other words 로 시작하는 일반화 자리다. 두 근거의 공통점은 「이미 비슷한 일을 하고 있던 곳」 — 기록을 잘 남기던 도시, 필사 조직이 두터운 도시. 빈칸 뒤 문장도 비슷한 것이 없던 곳에는 쓸 손도 붙일 습관도 없었다고 뒤집어 확인해 준다. 따라서 ①. ②는 첫 문장의 표현(needed least)을 반대로 읽은 오답이다.',
    rule: '빈칸이 in other words / thus 뒤에 있으면 앞 근거들의 공통점을 한 마디로 만든 뒤 선택지를 본다.',
    keyVocab: [
      { word: 'adopt', meaning: '받아들이다, 채택하다' },
      { word: 'take root', meaning: '뿌리내리다' },
      { word: 'starved of', meaning: '~이 몹시 부족한' },
    ],
    keySyntax: [
      {
        sentence:
          'The regions that adopted mechanical clocks earliest were not those with the most urgent need to measure time, but those whose towns already kept careful written records.',
        chunks: ['The regions', 'that adopted mechanical clocks earliest', 'were not those', 'with the most urgent need to measure time,', 'but those', 'whose towns already kept careful written records.'],
        translation: '기계 시계를 가장 먼저 받아들인 지역은 시간을 잴 필요가 가장 절박한 곳이 아니라, 그 도시들이 이미 꼼꼼한 기록을 남기고 있던 곳이었다.',
        point: 'not A but B 안에서 A와 B가 모두 those + 수식어. 대명사 those 가 무엇을 받는지(regions) 잡아야 한다.',
      },
    ],
  },
  {
    id: 'blank-2',
    type: 'blank',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 100,
    source: ORIGINAL,
    variantOf: 'blank-1',
    instruction: '다음 빈칸에 들어갈 말로 가장 적절한 것은?',
    passage: [
      'A referee who calls every small foul is said to be strict, and one who lets play run is said to be lenient.',
      'Players, however, complain about neither extreme as much as they complain about ______.',
      'A game in which the same contact is punished in the first half and ignored in the second forces players to guess the rule rather than follow it.',
      'Under a consistently strict referee, teams simply adjust; under a consistently loose one, they adjust as well.',
      'What cannot be adjusted to is a standard that moves.',
    ],
    choices: [
      { id: 1, text: 'a referee whose standard changes during the game' },
      { id: 2, text: 'referees who punish every minor contact', whyWrong: '엄격함 자체는 적응할 수 있다고 네 번째 문장이 말한다.', cause: 'logic' },
      { id: 3, text: 'rules that are too complicated to remember', whyWrong: '규칙의 복잡함은 언급되지 않는다.', cause: 'careless' },
      { id: 4, text: 'the pressure of playing in front of a crowd', whyWrong: '관중은 지문에 없다.', cause: 'careless' },
      { id: 5, text: 'coaches who argue with officials', whyWrong: '감독 이야기는 없다.', cause: 'careless' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '두 극단(엄격/관대) → 진짜 불만은 그것이 아니다(빈칸) → 사례(전후반이 다른 판정) → 두 극단 모두 적응 가능 → 결론(움직이는 기준)',
    hint: '마지막 문장 What cannot be adjusted to is a standard that moves 를 그대로 옮긴 선택지를 찾으세요.',
    explanation:
      '빈칸 뒤의 사례(전반과 후반의 기준이 다른 경기)와 마지막 문장(적응할 수 없는 것은 움직이는 기준이다)이 함께 빈칸을 정한다. 따라서 ①. ②는 지문에 나온 표현이지만 네 번째 문장이 「일관되게 엄격하면 적응한다」고 이미 배제해 두었다 — 낱말이 겹친다고 답이 되지 않는다.',
    rule: '빈칸을 고른 뒤 반드시 넣어 읽고 뒷문장과 충돌하지 않는지 검산한다.',
    keyVocab: [
      { word: 'lenient', meaning: '관대한' },
      { word: 'consistently', meaning: '일관되게' },
      { word: 'adjust', meaning: '적응하다, 맞추다' },
    ],
    keySyntax: [
      {
        sentence:
          'A game in which the same contact is punished in the first half and ignored in the second forces players to guess the rule rather than follow it.',
        chunks: ['A game', 'in which the same contact is punished in the first half', 'and ignored in the second', 'forces players to guess the rule', 'rather than follow it.'],
        translation: '같은 접촉이 전반에는 반칙이 되고 후반에는 넘어가는 경기는 선수들로 하여금 규칙을 따르기보다 짐작하게 만든다.',
        point: '주어(A game)와 동사(forces) 사이에 in which 관계절이 길게 들어갔다. 관계절을 괄호로 묶어야 동사가 보인다.',
      },
    ],
  },
];
