import type { Question } from './types';

/** 글의 구조 + 요약 문항 (무관한 문장/순서/삽입/요약문). 전부 자체 제작 — §4.4.
 *
 * 순서·삽입 문항은 지문 배열의 각 원소가 화면의 한 덩어리가 된다.
 * (A)(B)(C) 표시와 ①~⑤ 자리 표시를 본문에 그대로 넣어 두었다. */

const ORIGINAL = { status: 'original', label: '자체 제작 수능형 문항', reviewedBy: '미검수' } as const;

export const STRUCTURE_QUESTIONS: Question[] = [
  {
    id: 'irrelevant-1',
    type: 'irrelevant',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 85,
    source: ORIGINAL,
    instruction: '다음 글에서 전체 흐름과 관계 없는 문장은?',
    passage: [
      'Street lighting was once designed to make roads bright, and brightness was measured at the lamp.',
      '① Engineers now measure instead how evenly the light falls, because a road with bright pools and dark gaps is harder to read than a dimmer but even one.',
      '② A driver whose eyes keep adjusting between glare and shadow sees less than one under steady low light.',
      '③ The energy saved by replacing old lamps with LEDs has allowed several cities to cut their lighting budgets.',
      '④ For the same reason, designers now space lamps more closely and aim them downward rather than raising their power.',
      '⑤ Evenness, not intensity, has become the standard by which a lit street is judged.',
    ],
    choices: [
      { id: 1, text: '①', whyWrong: '밝기에서 균일함으로 기준이 옮겨 갔다는 화제를 여는 문장이다.', cause: 'strategy' },
      { id: 2, text: '②', whyWrong: '균일함이 왜 중요한지를 눈의 적응으로 설명한다.', cause: 'strategy' },
      { id: 3, text: '③' },
      { id: 4, text: '④', whyWrong: '균일함을 얻기 위한 설계 방식이다.', cause: 'strategy' },
      { id: 5, text: '⑤', whyWrong: '화제를 한 문장으로 마무리한다.', cause: 'strategy' },
    ],
    answer: 3,
    evidenceIndex: 3,
    structureLine: '옛 기준(밝기) → 새 기준(균일함) → 이유(눈의 적응) → 설계의 대응 → 마무리',
    hint: '문장마다 「무엇에 대해 무엇을 더했는지」를 한 마디로 적어 보세요. 화제가 바뀌는 자리가 보입니다.',
    explanation:
      '이 글의 화제는 「밝기에서 균일함으로 옮겨 간 조명의 기준」이다. ③은 LED 교체로 예산을 줄였다는 비용 이야기로, lighting 이라는 낱말만 같을 뿐 균일함과는 무관하다. ③을 빼고 ②에서 ④로 바로 이으면 For the same reason 이 자연스럽게 붙는다 — 이것이 확인 방법이다.',
    rule: '같은 낱말이 있다고 관계있는 문장이 아니다. 빼고 읽어 앞뒤가 붙는지 확인한다.',
    keyVocab: [
      { word: 'glare', meaning: '눈부심' },
      { word: 'evenness', meaning: '고름, 균일함' },
      { word: 'intensity', meaning: '세기, 강도' },
    ],
    keySyntax: [
      {
        sentence: 'A driver whose eyes keep adjusting between glare and shadow sees less than one under steady low light.',
        chunks: ['A driver', 'whose eyes keep adjusting between glare and shadow', 'sees less', 'than one under steady low light.'],
        translation: '눈부심과 그늘 사이에서 눈이 계속 적응해야 하는 운전자는 일정한 저조도 아래의 운전자보다 덜 본다.',
        point: '소유격 관계대명사 whose 절이 주어와 동사(sees) 사이를 벌려 놓았다. one 은 a driver 를 받는다.',
      },
    ],
  },
  {
    id: 'irrelevant-2',
    type: 'irrelevant',
    difficulty: 3,
    vocabLevel: 'csatBase',
    expectedSeconds: 85,
    source: ORIGINAL,
    variantOf: 'irrelevant-1',
    instruction: '다음 글에서 전체 흐름과 관계 없는 문장은?',
    passage: [
      'A recipe written for a restaurant kitchen assumes readers who already know the moves.',
      '① It says "reduce until thick" because a cook can see thickness, while a home reader wants a number of minutes.',
      '② Translating such a recipe therefore means adding the checks that a trained hand performs without naming them.',
      '③ Good writers of home recipes describe what the pan should sound like, not only what the timer should say.',
      '④ Restaurant kitchens usually run longer hours than bakeries, which open before dawn and close in the afternoon.',
      '⑤ The added sentences are not simplifications; they are the tacit part of the craft written down.',
    ],
    choices: [
      { id: 1, text: '①', whyWrong: '전문가용 표현과 가정용 독자의 차이를 보여 주는 예다.', cause: 'strategy' },
      { id: 2, text: '②', whyWrong: '그 차이를 메우는 일이 무엇인지 정의한다.', cause: 'strategy' },
      { id: 3, text: '③', whyWrong: '메우는 방법의 구체적인 예다.', cause: 'strategy' },
      { id: 4, text: '④' },
      { id: 5, text: '⑤', whyWrong: '더해진 문장의 성격을 한 마디로 마무리한다.', cause: 'strategy' },
    ],
    answer: 4,
    evidenceIndex: 4,
    structureLine: '전제(전문가용 조리법) → 예 → 번역의 정의 → 구체적 방법 → 마무리(암묵지의 기록)',
    hint: '④가 kitchen 이라는 낱말을 쓰긴 하지만, 이 글이 다루는 화제에 무엇을 더하나요?',
    explanation:
      '화제는 「전문가용 조리법을 가정용으로 옮길 때 무엇을 적어 넣어야 하는가」다. ④는 주방과 제과점의 영업시간 비교로 화제가 완전히 옮겨 간다. 문장을 빼고 ③에서 ⑤로 이으면 The added sentences 가 ③의 내용을 그대로 받는다.',
    rule: '무관한 문장은 대개 「같은 분야, 다른 화제」다. 화제어를 한 마디로 적어 두고 비교한다.',
    keyVocab: [
      { word: 'reduce', meaning: '(액체를) 졸이다', note: '「줄이다」의 요리 용법이다.' },
      { word: 'tacit', meaning: '말로 표현되지 않은, 암묵적인' },
      { word: 'craft', meaning: '기술, 손일' },
    ],
    keySyntax: [
      {
        sentence: 'Translating such a recipe therefore means adding the checks that a trained hand performs without naming them.',
        chunks: ['Translating such a recipe', 'therefore means', 'adding the checks', 'that a trained hand performs', 'without naming them.'],
        translation: '따라서 그런 조리법을 옮긴다는 것은, 숙련된 손이 이름 붙이지 않은 채 수행하는 확인 절차들을 적어 넣는 일을 뜻한다.',
        point: '동명사 주어 + means + 동명사 목적어. means to 부정사와 뜻이 달라지므로 형태를 확인한다.',
      },
    ],
  },
  {
    id: 'order-1',
    type: 'order',
    difficulty: 4,
    vocabLevel: 'csatBase',
    expectedSeconds: 100,
    source: ORIGINAL,
    instruction: '주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?',
    passage: [
      'In 1854 a London doctor drew a simple map of a neighborhood where hundreds had died of cholera, marking each death as a small bar on the street where it occurred.',
      '(A) That refusal is the reason the map is remembered. It did not prove the cause by itself, but it made a competing explanation hard to hold, and the pump handle was removed within days.',
      '(B) The bars piled up around one water pump on Broad Street. At the time most physicians believed the disease traveled through foul air, and a map of air would have shown nothing so sharp.',
      '(C) Critics answered that the pump merely stood in a poor and crowded district. The doctor then pointed to a workhouse and a brewery inside the cluster whose residents drank their own water and who had almost no deaths.',
    ],
    choices: [
      { id: 1, text: '(A) - (C) - (B)', whyWrong: '(A)의 That refusal 이 가리킬 대상이 앞에 없다.', cause: 'logic' },
      { id: 2, text: '(B) - (A) - (C)', whyWrong: '(A)의 That refusal 은 (C)의 반박을 받는 말이므로 (C) 뒤여야 한다.', cause: 'logic' },
      { id: 3, text: '(B) - (C) - (A)' },
      { id: 4, text: '(C) - (A) - (B)', whyWrong: '(C)의 Critics 가 무엇을 비판하는지가 아직 나오지 않았다.', cause: 'logic' },
      { id: 5, text: '(C) - (B) - (A)', whyWrong: '같은 이유로 (C)가 먼저 올 수 없다.', cause: 'logic' },
    ],
    answer: 3,
    evidenceIndex: 2,
    structureLine: '지도 제작(주어진 글) → 한 펌프로 모인 표시(B) → 비판과 재반박(C) → 그 거부가 남긴 것(A)',
    hint: '(A)의 That refusal, (C)의 Critics answered — 각각 앞에 무엇이 있어야 성립하는지 보세요.',
    explanation:
      '주어진 글은 사망을 막대로 표시한 지도를 소개한다. (B)의 The bars 가 그 막대를 그대로 받으므로 (B)가 먼저다. (C)의 Critics answered 는 (B)에서 드러난 결과에 대한 반박이다. (A)의 That refusal 은 (C)에서 물을 따로 마신 사람들이 거의 죽지 않았다는 사실이 통념을 「거부한」 것을 받으므로 마지막이다. 지시어가 가리킬 대상이 이미 나온 단락만 뒤에 올 수 있다.',
    rule: '순서 배열은 각 단락 첫머리의 지시어·연결어부터 표시하고, 가리킬 대상이 없는 단락은 앞에 둘 수 없다고 판정한다.',
    keyVocab: [
      { word: 'foul air', meaning: '나쁜 공기, 독기' },
      { word: 'cluster', meaning: '밀집한 무리' },
      { word: 'refusal', meaning: '거부' },
    ],
    keySyntax: [
      {
        sentence:
          'The doctor then pointed to a workhouse and a brewery inside the cluster whose residents drank their own water and who had almost no deaths.',
        chunks: ['The doctor then pointed to', 'a workhouse and a brewery', 'inside the cluster', 'whose residents drank their own water', 'and who had almost no deaths.'],
        translation: '그러자 그 의사는 밀집 구역 안에 있으면서 그 안의 사람들이 자기네 물을 마셨고 사망자가 거의 없었던 구빈원과 양조장을 가리켰다.',
        point: '관계절 둘(whose ~, who ~)이 and 로 병렬. 둘 다 앞의 a workhouse and a brewery 를 꾸민다.',
      },
    ],
  },
  {
    id: 'order-2',
    type: 'order',
    difficulty: 4,
    vocabLevel: 'csatBase',
    expectedSeconds: 100,
    source: ORIGINAL,
    variantOf: 'order-1',
    instruction: '주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?',
    passage: [
      'A library that lends tools instead of books opened in a small town with a single rule: borrow anything, but return it clean.',
      '(A) Neither happened. Borrowers who had met the person before them at the counter treated the drill as something shared rather than free, and the return rate stayed above ninety-five percent.',
      '(B) The founders expected two problems. Tools would come back broken, and the most useful ones would disappear entirely within a year.',
      '(C) What they had not planned was the second effect. People began asking to be shown how to use what they borrowed, and the shelves slowly grew a classroom beside them.',
    ],
    choices: [
      { id: 1, text: '(A) - (B) - (C)', whyWrong: '(A)의 Neither happened 은 두 가지 걱정이 먼저 나와야 성립한다.', cause: 'logic' },
      { id: 2, text: '(B) - (A) - (C)' },
      { id: 3, text: '(B) - (C) - (A)', whyWrong: '(C)의 the second effect 는 첫 번째 결과인 (A)가 먼저 나와야 한다.', cause: 'logic' },
      { id: 4, text: '(C) - (A) - (B)', whyWrong: '(C)의 the second effect 가 가리킬 첫 번째가 없다.', cause: 'logic' },
      { id: 5, text: '(C) - (B) - (A)', whyWrong: '같은 이유로 (C)가 먼저 올 수 없다.', cause: 'logic' },
    ],
    answer: 2,
    evidenceIndex: 2,
    structureLine: '도구 도서관 소개(주어진 글) → 예상한 두 문제(B) → 둘 다 일어나지 않음(A) → 예상 못 한 두 번째 효과(C)',
    hint: '(A) 첫 낱말 Neither, (C)의 the second effect — 각각 앞에 무엇을 요구하나요?',
    explanation:
      '(B)가 「두 가지 문제를 예상했다」로 걱정을 세우고, (A)의 Neither happened 이 그 둘을 받는다. (C)의 the second effect 는 (A)에서 나온 첫 번째 결과(높은 반납률) 다음에 와야 한다. 따라서 (B)-(A)-(C). 지시어 Neither·the second 는 앞에 반드시 짝이 있어야 하는 표현이다.',
    rule: 'Neither / the second / such 처럼 앞을 셈하는 표현은 그 자체가 순서의 증거다.',
    keyVocab: [
      { word: 'lend', meaning: '빌려주다', note: 'borrow(빌리다)와 방향이 반대다.' },
      { word: 'counter', meaning: '카운터, 접수대' },
      { word: 'shelf', meaning: '선반, 서가' },
    ],
    keySyntax: [
      {
        sentence:
          'Borrowers who had met the person before them at the counter treated the drill as something shared rather than free, and the return rate stayed above ninety-five percent.',
        chunks: ['Borrowers', 'who had met the person before them at the counter', 'treated the drill', 'as something shared rather than free,', 'and the return rate stayed above ninety-five percent.'],
        translation: '카운터에서 자기 앞사람을 만나 본 대출자들은 그 드릴을 공짜가 아니라 함께 쓰는 것으로 대했고, 반납률은 95퍼센트를 넘게 유지되었다.',
        point: 'treat A as B — 「A를 B로 여기다」. as 뒤에 something + 과거분사가 왔다.',
      },
    ],
  },
  {
    id: 'insertion-1',
    type: 'insertion',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 100,
    source: ORIGINAL,
    instruction: '글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?',
    passage: [
      '[주어진 문장] But this convenience has a cost that appears only later.',
      'Automatic translation now handles menus, signs, and short messages well enough that travelers rarely open a phrasebook. ( ① )',
      'A traveler who never struggles to ask for directions also never learns the shape of the question. ( ② )',
      'Language sits in the body through effort, and effort is exactly what the tool removes. ( ③ )',
      'Researchers who compare tourists using instant translation with those using a printed guide find the second group remembers far more of the language a week later. ( ④ )',
      'The tool is not the enemy; the difficulty it saves us from is the thing that taught us. ( ⑤ )',
    ],
    choices: [
      { id: 1, text: '①' },
      { id: 2, text: '②', whyWrong: '②는 이미 비용을 설명하기 시작한 뒤다. But 이 여기 오면 앞 문장과 같은 방향인데 역접이 된다.', cause: 'logic' },
      { id: 3, text: '③', whyWrong: '③ 앞뒤는 같은 논지를 이어 가므로 역접이 들어갈 자리가 아니다.', cause: 'logic' },
      { id: 4, text: '④', whyWrong: '연구 결과는 앞의 주장을 뒷받침한다. 역접이 아니다.', cause: 'logic' },
      { id: 5, text: '⑤', whyWrong: '마지막은 이미 결론이다.', cause: 'strategy' },
    ],
    answer: 1,
    evidenceIndex: 1,
    structureLine: '자동 번역의 편리함 → [역접] 그 대가 → 왜 그런가 → 연구 근거 → 결론',
    hint: '주어진 문장의 this convenience 가 가리킬 「편리함」은 어느 문장에 있나요?',
    explanation:
      '주어진 문장은 But 으로 시작하고 this convenience 를 받는다. 편리함을 말한 문장은 첫 문장(여행자가 회화책을 열지 않을 만큼 잘 처리한다)뿐이므로 자리는 ①이다. 넣어 읽으면 편리함 → 대가 → 그 이유 → 근거 → 결론으로 매끄럽게 이어진다. 지시어가 가리킬 대상이 아직 안 나온 자리에는 넣을 수 없다.',
    rule: '삽입 문장의 지시어(this/그것)가 가리킬 대상을 먼저 찾고, 그 문장 바로 뒤부터만 후보로 남긴다.',
    keyVocab: [
      { word: 'phrasebook', meaning: '여행 회화책' },
      { word: 'struggle', meaning: '애를 쓰다, 씨름하다' },
      { word: 'convenience', meaning: '편리함' },
    ],
    keySyntax: [
      {
        sentence: 'The tool is not the enemy; the difficulty it saves us from is the thing that taught us.',
        chunks: ['The tool is not the enemy;', 'the difficulty', 'it saves us from', 'is the thing', 'that taught us.'],
        translation: '도구가 적인 것이 아니다 — 그 도구가 우리를 면하게 해 주는 그 어려움이야말로 우리를 가르치던 것이었다.',
        point: 'the difficulty (that) it saves us from — 목적격 관계대명사 생략 + 전치사 from 이 뒤에 남았다.',
      },
    ],
  },
  {
    id: 'insertion-2',
    type: 'insertion',
    difficulty: 4,
    vocabLevel: 'csatBase',
    expectedSeconds: 95,
    source: ORIGINAL,
    variantOf: 'insertion-1',
    instruction: '글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?',
    passage: [
      '[주어진 문장] The birds that survived were not the ones that flew best, but the ones that noticed earliest.',
      'When a new predator reaches an island, the first season is the harshest. ( ① )',
      'Field notes from three such islands record the same pattern in the months that follow. ( ② )',
      'Speed helped only after a threat had been seen, and by then most attacks were already decided. ( ③ )',
      'Within a few generations the surviving population showed shorter feeding bouts and more frequent scanning, not stronger wings. ( ④ )',
      'Attention, in other words, was the trait under selection. ( ⑤ )',
    ],
    choices: [
      { id: 1, text: '①', whyWrong: '아직 어떤 패턴인지 나오지 않았다. 주어진 문장이 그 패턴의 내용이다.', cause: 'logic' },
      { id: 2, text: '②' },
      { id: 3, text: '③', whyWrong: '③ 앞의 문장이 없으면 Speed helped only after 가 무엇을 받는지 알 수 없다.', cause: 'logic' },
      { id: 4, text: '④', whyWrong: '④ 자리에 넣으면 근거보다 결론이 뒤늦게 온다.', cause: 'strategy' },
      { id: 5, text: '⑤', whyWrong: '⑤는 이미 요약 결론이다.', cause: 'strategy' },
    ],
    answer: 2,
    evidenceIndex: 2,
    structureLine: '첫 계절의 혹독함 → 세 섬의 같은 패턴 → [그 패턴의 내용] → 속도의 한계 → 관찰된 변화 → 결론(주의력)',
    hint: '「같은 패턴이 기록되었다」 다음에는 그 패턴이 무엇인지가 와야 합니다.',
    explanation:
      '②의 앞 문장은 the same pattern 이 기록되었다고만 말하고 그 내용을 말하지 않는다. 주어진 문장이 바로 그 내용(잘 나는 새가 아니라 먼저 알아챈 새가 살아남았다)이다. ③의 Speed helped only after 도 그 문장의 flew best 를 받아야 성립하므로, 주어진 문장이 ③보다 앞에 있어야 한다.',
    rule: '앞 문장이 「~한 패턴/결과가 있었다」로 끝나면 그 다음 자리가 삽입 후보 1순위다.',
    keyVocab: [
      { word: 'predator', meaning: '포식자' },
      { word: 'bout', meaning: '한 차례의 활동 기간' },
      { word: 'trait', meaning: '(생물의) 형질, 특성' },
    ],
    keySyntax: [
      {
        sentence: 'Within a few generations the surviving population showed shorter feeding bouts and more frequent scanning, not stronger wings.',
        chunks: ['Within a few generations', 'the surviving population showed', 'shorter feeding bouts', 'and more frequent scanning,', 'not stronger wings.'],
        translation: '몇 세대 지나지 않아 살아남은 개체군은 더 강한 날개가 아니라 더 짧은 섭식 시간과 더 잦은 경계를 보였다.',
        point: 'A and B, not C — 목적어 셋이 나란히 놓인 병렬. not 뒤가 버려지는 쪽이다.',
      },
    ],
  },
  {
    id: 'summary-1',
    type: 'summary',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 105,
    source: ORIGINAL,
    instruction: '다음 글의 내용을 한 문장으로 요약하고자 한다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?',
    passage: [
      'A team of designers tested two versions of a hospital discharge form.',
      'The first listed every instruction a patient might need, in careful and complete sentences.',
      'The second gave only the three actions that mattered in the first week, with the rest available on request.',
      'Patients given the complete form reported feeling well informed, yet a week later fewer than a third could name their next appointment.',
      'Patients given the short form felt they had been told less, and nearly all of them took their medicine on schedule.',
      '',
      '[요약문] Although the fuller form made patients feel better (A), the shorter one produced more accurate (B).',
    ],
    choices: [
      { id: 1, text: '(A) informed … (B) action' },
      { id: 2, text: '(A) informed … (B) memory', whyWrong: '(A)는 맞지만 (B)가 좁다. 실제로 달라진 것은 약을 제때 먹는 행동이다.', cause: 'strategy' },
      { id: 3, text: '(A) rushed … (B) action', whyWrong: '(A)가 틀렸다. 긴 서식을 받은 환자는 서둘렀다고 하지 않았다.', cause: 'careless' },
      { id: 4, text: '(A) confused … (B) satisfaction', whyWrong: '두 자리 모두 지문과 어긋난다.', cause: 'logic' },
      { id: 5, text: '(A) informed … (B) satisfaction', whyWrong: '만족도는 오히려 긴 서식 쪽이 높았다.', cause: 'logic' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '실험 설계 → 긴 서식 → 짧은 서식 → 결과 1(느낌은 좋으나 기억 못 함) → 결과 2(느낌은 덜하나 실제로 지킴)',
    hint: '(A)는 「느낌」, (B)는 「실제 결과」 자리입니다. 한 자리씩 확정하세요.',
    explanation:
      '(A)는 긴 서식을 받은 환자의 느낌 — reported feeling well informed 에서 informed. (B)는 짧은 서식이 낳은 실제 결과 — 약을 제때 먹었다는 행동이므로 action. ②의 memory 는 다음 진료일을 기억하는지에만 해당해 요약문이 덮어야 할 범위보다 좁다. 요약 문항은 두 자리를 동시에 보지 말고 하나씩 확정해 선택지를 줄인다.',
    rule: '(A)를 먼저 확정해 선택지를 줄이고, 남은 것들 사이에서 (B)를 가른다.',
    keyVocab: [
      { word: 'discharge', meaning: '퇴원(시키다)' },
      { word: 'on schedule', meaning: '예정대로' },
      { word: 'on request', meaning: '요청하면' },
    ],
    keySyntax: [
      {
        sentence:
          'Patients given the complete form reported feeling well informed, yet a week later fewer than a third could name their next appointment.',
        chunks: ['Patients', 'given the complete form', 'reported feeling well informed,', 'yet a week later', 'fewer than a third', 'could name their next appointment.'],
        translation: '완전한 서식을 받은 환자들은 잘 안내받았다고 느꼈다고 답했지만, 일주일 뒤에는 3분의 1도 안 되는 사람만이 다음 진료일을 말할 수 있었다.',
        point: '주어 뒤에 과거분사구(given ~)가 붙어 주어와 동사가 벌어졌다. reported 가 본동사다.',
      },
    ],
  },
  {
    id: 'summary-2',
    type: 'summary',
    difficulty: 4,
    vocabLevel: 'csatHard',
    expectedSeconds: 105,
    source: ORIGINAL,
    variantOf: 'summary-1',
    instruction: '다음 글의 내용을 한 문장으로 요약하고자 한다. 빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?',
    passage: [
      'For a century, orchestras chose players in open auditions where the panel could see who was performing.',
      'Beginning in the 1970s, several orchestras placed a screen between the panel and the stage.',
      'Candidates walked on carpet so that the sound of shoes revealed nothing, and no one spoke until the decision was made.',
      'The share of women advancing past the first round rose sharply, and it kept rising as more orchestras adopted the practice.',
      'The judges had not intended to favor anyone; they simply could not stop seeing what they saw.',
      '',
      '[요약문] Hiding information about the performer reduced the influence of (A) judgment, showing that unfairness can persist without (B).',
    ],
    choices: [
      { id: 1, text: '(A) unintentional … (B) intent' },
      { id: 2, text: '(A) musical … (B) training', whyWrong: '(A)가 틀렸다. 가려진 것은 음악적 판단이 아니라 시각 정보다.', cause: 'careless' },
      { id: 3, text: '(A) unintentional … (B) evidence', whyWrong: '(B)가 어긋난다. 지문은 증거가 아니라 의도의 부재를 말한다.', cause: 'logic' },
      { id: 4, text: '(A) deliberate … (B) intent', whyWrong: '마지막 문장이 심사위원에게 의도가 없었다고 못박는다.', cause: 'logic' },
      { id: 5, text: '(A) collective … (B) rules', whyWrong: '집단성이나 규정은 화제가 아니다.', cause: 'careless' },
    ],
    answer: 1,
    evidenceIndex: 4,
    structureLine: '옛 관행(보이는 심사) → 변화(가림막) → 철저한 차단 → 결과(합격 비율 상승) → 해석(의도 없이도 일어난다)',
    hint: '마지막 문장 had not intended … could not stop seeing 이 두 빈칸을 동시에 정합니다.',
    explanation:
      '마지막 문장이 핵심이다 — 심사위원에게 편애할 의도가 없었지만 본 것을 안 볼 수 없었다. 따라서 줄어든 것은 「의도하지 않은(unintentional) 판단」의 영향이고, 불공정은 「의도(intent)」 없이도 지속될 수 있다는 것이 결론이다. ④의 deliberate 는 마지막 문장과 정면으로 어긋난다.',
    rule: '요약문의 두 빈칸은 대개 지문의 마지막 한두 문장에서 동시에 정해진다.',
    keyVocab: [
      { word: 'audition', meaning: '오디션, 실기 심사' },
      { word: 'panel', meaning: '심사위원단' },
      { word: 'advance', meaning: '(다음 단계로) 진출하다' },
    ],
    keySyntax: [
      {
        sentence: 'The judges had not intended to favor anyone; they simply could not stop seeing what they saw.',
        chunks: ['The judges had not intended', 'to favor anyone;', 'they simply could not stop seeing', 'what they saw.'],
        translation: '심사위원들이 누군가를 편애하려 했던 것은 아니다 — 그들은 다만 자기가 본 것을 보지 않을 수 없었을 뿐이다.',
        point: 'stop -ing(멈추다)와 what 명사절 목적어. 과거완료(had not intended)가 결과보다 앞선 시점을 나타낸다.',
      },
    ],
  },
];
