/**
 * 성경통독도우미 콘텐츠 (English) — deuteronomy-10-18
 *
 * scripts/bilingual/ 의 원고에서 자동으로 만들어진 파일이다.
 * **여기를 고치지 말고 원고를 고쳐서 다시 쪼갤 것** — 두 언어의 자리가 어긋난다.
 *
 * memoryVerse 는 한글 파일에만 있다. 영어 본문은 앱이 쓰는 성경(open_en)에서
 * 그대로 가져오므로 여기서 옮기지 않는다.
 */

module.exports = [
  {
    book: 5,
    chapter: 10,
    summary:
      'The LORD told Moses to chisel two new tablets like the first; Moses made an acacia-wood chest and put them in it. At that time the tribe of Levi was set apart to carry the ark, to stand before the LORD and minister, and to pronounce blessings in his name — which is why Levi has no share or inheritance: the LORD himself is their inheritance. Then Moses asks: "What does the LORD your God ask of you?" — to fear him, walk in his ways, love him, serve him with all your heart and soul, and keep his commands. Heaven and earth belong to him, yet he set his affection on their ancestors and chose their descendants. So they are to circumcise their hearts and be stiff-necked no longer. He takes no bribes, he defends the cause of the fatherless and the widow, and he loves the foreigner, giving him food and clothing. Seventy people went down to Egypt; now they are as numerous as the stars.',
    questions: [
      {
        type: 'choice',
        question: 'What was Moses told to make along with the second set of tablets?',
        choices: ['A wooden chest', 'A gold lampstand', 'A bronze altar', 'New priestly garments'],
        correctIndex: 0,
        explanation: 'He made it of acacia wood and put the tablets inside.',
      },
      {
        type: 'choice',
        question: 'What work was the tribe of Levi set apart for?',
        choices: [
          'Carrying the ark, ministering before the LORD, and blessing in his name',
          'Judging the towns',
          'Leading the army into battle',
          'Surveying and dividing the land',
        ],
        correctIndex: 0,
        explanation: 'Three tasks are listed side by side.',
      },
      {
        type: 'choice',
        question: 'What was given to Levi in place of an inheritance?',
        choices: [
          'The LORD himself is their inheritance',
          'Twelve towns',
          'Half the firstfruits of every tribe',
          'The land east of the Jordan',
        ],
        correctIndex: 0,
        explanation: 'Their portion is not land but God himself.',
      },
      {
        type: 'choice',
        question: 'What is the answer to "What does the LORD ask of you?"',
        choices: [
          'To fear him, walk in his ways, love him and serve him with all your heart and soul',
          'To bring more sacrifices each year',
          'To build a great temple',
          'To conquer the neighboring nations',
        ],
        correctIndex: 0,
        explanation: 'What is asked for is not offerings but the person.',
      },
      {
        type: 'choice',
        question: 'What were they told to do to their hearts?',
        choices: ['Circumcise them', 'Write on them', 'Seal them', 'Wash them'],
        correctIndex: 0,
        explanation: 'The sign must go deeper than the body: the heart itself must turn.',
      },
      {
        type: 'choice',
        question: 'Toward whom does this chapter say God acts justly?',
        choices: [
          'The fatherless, the widow and the foreigner',
          'Kings and priests',
          'Army commanders',
          'The wealthy',
        ],
        correctIndex: 0,
        explanation: 'That is why "you also are to love the foreigner" follows at once.',
      },
      {
        type: 'choice',
        question: 'How many of their ancestors went down to Egypt?',
        choices: ['Seventy', 'Twelve', 'Six hundred thousand', 'Three hundred'],
        correctIndex: 0,
        explanation: 'The contrast is that they are now as numerous as the stars.',
      },
    ],
  },
  {
    book: 5,
    chapter: 11,
    summary:
      'Moses tells them to remember what their children never saw: the signs done in Egypt, the Red Sea closing over Pharaoh’s army, and the ground opening to swallow Dathan and Abiram. The land ahead is not like Egypt, where they irrigated by foot like a vegetable garden; Canaan drinks rain from heaven, and the eyes of the LORD are on it from the beginning of the year to its end. If they obey, he will send the autumn and spring rains in season, and there will be grain, new wine and oil; if they turn to other gods, the heavens will shut. So these words are to be fixed in heart and mind, tied on their hands, taught to their children and written on their doorframes. Moses sets before them a blessing and a curse, and tells them to proclaim the blessings on Mount Gerizim and the curses on Mount Ebal.',
    questions: [
      {
        type: 'choice',
        question: 'What were they to remember that their children had not seen?',
        choices: [
          'The sea closing over Egypt’s army, and the earth swallowing Dathan and Abiram',
          'Abraham offering up Isaac',
          'Joseph becoming ruler in Egypt',
          'The flood in Noah’s day',
        ],
        correctIndex: 0,
        explanation: 'Both were things that generation had seen with their own eyes.',
      },
      {
        type: 'choice',
        question: 'How is Canaan different from Egypt?',
        choices: [
          'It drinks rain from heaven instead of being irrigated by foot',
          'It has no river and cannot be farmed',
          'It is flat, with no hills',
          'No one lives there',
        ],
        correctIndex: 0,
        explanation: 'The point of the comparison is that they cannot water it themselves.',
      },
      {
        type: 'choice',
        question: 'What does the text say about that land?',
        choices: [
          'The eyes of the LORD are on it from the beginning of the year to its end',
          'It must be managed entirely by human hands',
          'Half of it must lie fallow each year',
          'It is handed out by a king',
        ],
        correctIndex: 0,
        explanation: 'It is a land bound each year to the one who sends the rain.',
      },
      {
        type: 'choice',
        question: 'What was promised if they obeyed?',
        choices: [
          'The autumn and spring rains in their season',
          'An end to all war',
          'Freedom from all illness',
          'A king being appointed',
        ],
        correctIndex: 0,
        explanation: 'Grain, new wine and oil all follow from that rain.',
      },
      {
        type: 'choice',
        question: 'What would happen if they turned to other gods?',
        choices: [
          'He would shut the heavens so that no rain fell',
          'The ground would split open',
          'Their livestock would vanish',
          'Nothing would happen',
        ],
        correctIndex: 0,
        explanation: 'In a land that depends on rain, the warning touches daily bread itself.',
      },
      {
        type: 'choice',
        question: 'What two things did Moses set before them?',
        choices: ['A blessing and a curse', 'War and peace', 'Land and sea', 'Law and sacrifice'],
        correctIndex: 0,
        explanation: 'It means there is a real choice to be made.',
      },
      {
        type: 'choice',
        question: 'On which mountains were the blessings and curses to be proclaimed?',
        choices: [
          'Blessings on Gerizim, curses on Ebal',
          'Blessings on Sinai, curses on Horeb',
          'Blessings on Nebo, curses on Pisgah',
          'Blessings on Hermon, curses on Hor',
        ],
        correctIndex: 0,
        explanation: 'This is actually carried out in Joshua 8.',
      },
    ],
  },
  {
    book: 5,
    chapter: 12,
    summary:
      'Every place where the nations served their gods — on high hills, on the hills, under spreading trees — is to be destroyed, with their altars, sacred stones, Asherah poles and idols. But they must not worship the LORD in that way. Instead they are to bring their burnt offerings, tithes, vows and firstborn to the one place he chooses as a dwelling for his Name, and eat there and rejoice with their households. The days of everyone doing as he saw fit are over. Meat, however, may be eaten freely in any town, as one eats gazelle or deer — only never the blood, which must be poured out on the ground like water, because the blood is the life. They must not neglect the Levites in their towns, and must never ask about the nations’ gods, "How did they serve them, that I may do the same?" — those nations burned their own children in the fire to their gods.',
    questions: [
      {
        type: 'choice',
        question: 'What were they to do with the places where the nations served their gods?',
        choices: [
          'Destroy them all, with their altars, sacred stones and idols',
          'Leave them alone and pass by',
          'Convert them into altars for the LORD',
          'Hand them over to foreigners',
        ],
        correctIndex: 0,
        explanation: 'The next verse adds, "You must not worship the LORD in their way."',
      },
      {
        type: 'choice',
        question: 'What was commanded about the place of worship?',
        choices: [
          'Bring the offerings to the one place he chooses for his Name',
          'Build an altar in every town',
          'Sacrifice in each household',
          'Offer only on high hills',
        ],
        correctIndex: 0,
        explanation: 'This is where "everyone doing as he saw fit" comes to an end.',
      },
      {
        type: 'choice',
        question: 'What was still permitted in any town?',
        choices: [
          'Slaughtering animals and eating the meat',
          'Offering burnt offerings',
          'Eating the tithe',
          'Presenting vow offerings',
        ],
        correctIndex: 0,
        explanation: 'They could eat it as they would gazelle or deer.',
      },
      {
        type: 'choice',
        question: 'What was absolutely forbidden when eating meat?',
        choices: ['Eating the blood', 'Eating the fat', 'Eating at night', 'Eating alone'],
        correctIndex: 0,
        explanation: 'The blood was to be poured out on the ground like water.',
      },
      {
        type: 'choice',
        question: 'Why was the blood forbidden?',
        choices: [
          'Because the blood is the life',
          'Because it tastes bad',
          'Because it causes disease',
          'Because it is the priest’s portion',
        ],
        correctIndex: 0,
        explanation: 'You must not eat the life along with the meat.',
      },
      {
        type: 'choice',
        question: 'Whom were they repeatedly told not to neglect?',
        choices: [
          'The Levites living in their towns',
          'The king’s officials',
          'The men away at war',
          'The merchants',
        ],
        correctIndex: 0,
        explanation: 'The Levites had no share or inheritance of their own.',
      },
      {
        type: 'choice',
        question: 'Why must they never ask how the nations served their gods?',
        choices: [
          'Because they burned their own children in the fire to their gods',
          'Because their rites were too difficult',
          'Because they would not teach it',
          'Because they already knew it all',
        ],
        correctIndex: 0,
        explanation: 'The text shows in advance where such curiosity leads.',
      },
    ],
  },
  {
    book: 5,
    chapter: 13,
    summary:
      'If a prophet or dreamer performs a sign or wonder and it actually comes true, but then says, "Let us follow other gods," they must not listen — the LORD is testing whether they love him with all their heart and soul. Even if the one enticing them in secret is a brother, a child, a beloved wife or a closest friend, they must not yield, listen, spare, shield or conceal. If a whole town is reported to have been led astray, they must first inquire, probe and investigate thoroughly; only if it is proven true is the town to be destroyed, its plunder gathered and burned as an offering, with nothing devoted kept back for themselves. Then all Israel will hear and be afraid, and such evil will not be done among them again.',
    questions: [
      {
        type: 'choice',
        question: 'When must a sign that actually comes true still be rejected?',
        choices: [
          'When it is used to say, "Let us follow other gods"',
          'When the rains fail',
          'When the king forbids it',
          'When no priest is present',
        ],
        correctIndex: 0,
        explanation: 'A sign coming true is not by itself proof of truth.',
      },
      {
        type: 'choice',
        question: 'Why does the text say such things happen?',
        choices: [
          'To test whether they love him with all their heart',
          'To punish the prophet',
          'To startle the neighboring nations',
          'To stop the rain',
        ],
        correctIndex: 0,
        explanation: 'The one being tested is not the prophet but the listener.',
      },
      {
        type: 'choice',
        question: 'What if the one enticing them secretly is family or a close friend?',
        choices: [
          'Do not yield, do not listen, and do not conceal it',
          'Forgive them if they are family',
          'Tell only a priest and cover it up',
          'Send them outside the town',
        ],
        correctIndex: 0,
        explanation: 'Closeness is granted no exemption — that is the edge of this law.',
      },
      {
        type: 'choice',
        question: 'What is the first step when a report about a town is heard?',
        choices: [
          'Inquire, probe and investigate thoroughly',
          'Send the army at once',
          'Seal off the town',
          'Ignore the report',
        ],
        correctIndex: 0,
        explanation: 'Verification is written into the law as the first step.',
      },
      {
        type: 'choice',
        question: 'What was to be done with a town proven guilty?',
        choices: [
          'Destroy it and burn all its plunder as an offering',
          'Double its taxes',
          'Move its people to another town',
          'Tear down only its altars',
        ],
        correctIndex: 0,
        explanation: 'The town was to remain a ruin, never to be rebuilt.',
      },
      {
        type: 'choice',
        question: 'What was said about the devoted things?',
        choices: [
          'Do not lay a hand on any of it',
          'Half of it could be kept',
          'Give it to the Levites',
          'Sell it and share the money',
        ],
        correctIndex: 0,
        explanation: 'Breaking this law is exactly what Achan does in Joshua 7.',
      },
      {
        type: 'choice',
        question: 'What purpose does the chapter give for such severity?',
        choices: [
          'So that all Israel would hear, be afraid, and never do such evil again',
          'To establish the king’s authority',
          'To practice for war',
          'To reduce the number of towns',
        ],
        correctIndex: 0,
        explanation: 'The text states that purpose directly.',
      },
    ],
  },
  {
    book: 5,
    chapter: 14,
    summary:
      'The chapter opens: "You are the children of the LORD your God." They are not to cut themselves or shave their foreheads for the dead, as the surrounding peoples mourned. Animals that may be eaten are those with a split hoof that also chew the cud; the camel, rabbit and hyrax chew the cud but do not have split hooves, and the pig has a split hoof but does not chew the cud, so none of them may be eaten. From the water, only what has fins and scales; among birds, all clean ones, excluding eagles, vultures, the ostrich, owls, the bat and others. Each year the tithe of the land is to be eaten at the place the LORD chooses, so that they learn to revere him always. If that place is too far, the tithe may be exchanged for silver and spent there on whatever they desire, to eat with their household. Every third year the tithe is stored in their towns so that Levites, foreigners, orphans and widows may come and eat their fill.',
    questions: [
      {
        type: 'choice',
        question: 'How does this chapter address Israel at the outset?',
        choices: [
          'The children of the LORD your God',
          'Wanderers of the wilderness',
          'A stiff-necked people',
          'Servants of a king',
        ],
        correctIndex: 0,
        explanation: 'That identity is the ground for the rules that follow.',
      },
      {
        type: 'choice',
        question: 'What mourning practices were forbidden?',
        choices: [
          'Cutting themselves or shaving the front of their heads',
          'Weeping for seven days',
          'Building a tomb',
          'Wearing mourning clothes',
        ],
        correctIndex: 0,
        explanation: 'It is not grief that is forbidden but the pagan form of it.',
      },
      {
        type: 'choice',
        question: 'What marks an animal as edible?',
        choices: [
          'A split hoof and chewing the cud',
          'A split hoof alone',
          'Chewing the cud alone',
          'Anything caught in the open field',
        ],
        correctIndex: 0,
        explanation: 'One of the two marks alone is not enough.',
      },
      {
        type: 'choice',
        question: 'Why could the pig not be eaten?',
        choices: [
          'It has a split hoof but does not chew the cud',
          'It chews the cud but has no split hoof',
          'Because it is a wild animal',
          'Because it is reserved for sacrifice',
        ],
        correctIndex: 0,
        explanation: 'The camel, rabbit and hyrax fail the test the other way around.',
      },
      {
        type: 'choice',
        question: 'What water creatures could be eaten?',
        choices: [
          'Those with fins and scales',
          'Anything caught in the sea',
          'Only what came from fresh water',
          'Anything longer than a handspan',
        ],
        correctIndex: 0,
        explanation: 'Both marks are required.',
      },
      {
        type: 'choice',
        question: 'What if the chosen place was too far to carry the tithe?',
        choices: [
          'Exchange it for silver, and buy there what they desired',
          'Skip the tithe that year',
          'Leave it with a neighbor',
          'Call a priest to their home',
        ],
        correctIndex: 0,
        explanation: 'Cattle, sheep, wine — whatever they wished — eaten with their household.',
      },
      {
        type: 'choice',
        question: 'What was done with the tithe every third year?',
        choices: [
          'Stored in their towns for Levites, foreigners, orphans and widows',
          'Given entirely to the priests',
          'Sold to build a temple',
          'Kept back for the following year',
        ],
        correctIndex: 0,
        explanation: 'Then the LORD would bless all the work of their hands.',
      },
    ],
  },
  {
    book: 5,
    chapter: 15,
    summary:
      'At the end of every seven years there is to be a cancellation of debts: what a neighbor owes is released, and no payment is demanded. If anyone eyes a needy brother grudgingly because the year of release is near and gives nothing, that is sin. They must open their hand freely and lend whatever is needed, without a grudging heart. The chapter holds two things together — the promise that if they obey there will be no poor among them, and the plain fact that there will always be poor people in the land. Hence the command: open your hand. A Hebrew servant is to be freed in the seventh year after six years of service, and never sent away empty-handed, but supplied liberally from the flock, the threshing floor and the winepress — because they themselves were slaves in Egypt. If a servant chose to stay, an awl was pushed through his ear into the door.',
    questions: [
      {
        type: 'choice',
        question: 'What was to be done at the end of every seven years?',
        choices: [
          'Cancel what was lent and demand no payment',
          'Redistribute the land',
          'Relocate the towns',
          'Appoint a new priest',
        ],
        correctIndex: 0,
        explanation: 'Payment could be required of a foreigner, but not of a fellow Israelite.',
      },
      {
        type: 'choice',
        question: 'What "wicked thought" is warned against as the year of release nears?',
        choices: [
          'Eyeing a needy brother grudgingly and giving him nothing',
          'Charging higher interest',
          'Borrowing more',
          'Selling land',
        ],
        correctIndex: 0,
        explanation: 'If he cries out to the LORD, the text says, you will be guilty of sin.',
      },
      {
        type: 'choice',
        question: 'What does the text say plainly about the poor?',
        choices: [
          'There will always be poor people in the land',
          'They will vanish as soon as people obey',
          'Poverty is a punishment',
          'It is the king’s problem to solve',
        ],
        correctIndex: 0,
        explanation: 'That is why the command that follows is, "Open your hand."',
      },
      {
        type: 'choice',
        question: 'When was a Hebrew servant to be set free?',
        choices: [
          'In the seventh year, after six years of service',
          'Only in the Year of Jubilee',
          'After the master died',
          'Only after paying a price',
        ],
        correctIndex: 0,
        explanation: 'It follows the same rhythm as the year of release.',
      },
      {
        type: 'choice',
        question: 'How was a freed servant to be sent off?',
        choices: [
          'Not empty-handed, but supplied liberally',
          'With nothing at all',
          'Only after he repaid his debt',
          'Handed on to another master',
        ],
        correctIndex: 0,
        explanation: 'From the flock, the threshing floor and the winepress.',
      },
      {
        type: 'choice',
        question: 'What were they to remember as the reason for this?',
        choices: [
          'That they were slaves in Egypt and the LORD redeemed them',
          'That their ancestors were wealthy',
          'That they ate manna in the wilderness',
          'That the land came to them by lot',
        ],
        correctIndex: 0,
        explanation: 'The freedom they received becomes the ground of the freedom they give.',
      },
      {
        type: 'choice',
        question: 'What was done if a servant chose to stay?',
        choices: [
          'An awl was pushed through his ear into the door',
          'A mark was cut into his forehead',
          'A deed was written and left with a priest',
          'Nothing formal was done',
        ],
        correctIndex: 0,
        explanation: 'The same was to be done for a female servant.',
      },
    ],
  },
  {
    book: 5,
    chapter: 16,
    summary:
      'This chapter sets out the three pilgrim festivals. Passover is kept in the month of Aviv at the place the LORD chooses, with seven days of unleavened bread — "the bread of affliction" — so that all their lives they remember the day they left Egypt in haste. Seven weeks are counted from when the sickle is first put to the standing grain, and the Festival of Weeks is kept; after the produce of the threshing floor and winepress is gathered, the Festival of Tabernacles is kept for seven days. At each festival their sons and daughters, servants, Levites, foreigners, orphans and widows are to rejoice together. Every man is to appear before the LORD three times a year, never empty-handed, but each with a gift in proportion to the blessing he has received. Then come the rules for judges: do not pervert justice, show no partiality, take no bribe — for a bribe blinds the eyes of the wise. "Follow justice and justice alone."',
    questions: [
      {
        type: 'choice',
        question: 'In which month is Passover kept?',
        choices: ['The month of Aviv', 'The seventh month', 'The ninth month', 'The twelfth month'],
        correctIndex: 0,
        explanation: 'It was in that month, by night, that he brought them out of Egypt.',
      },
      {
        type: 'choice',
        question: 'What does the text call the unleavened bread?',
        choices: [
          'The bread of affliction',
          'The bread of angels',
          'The bread of joy',
          'The bread of the Presence',
        ],
        correctIndex: 0,
        explanation: 'The name recalls the day they left in haste.',
      },
      {
        type: 'choice',
        question: 'How was the Festival of Weeks counted?',
        choices: [
          'Seven weeks from when the sickle is first put to the grain',
          'Forty days from the day after Passover',
          'From the first day of the seventh month',
          'On the same fixed date each year',
        ],
        correctIndex: 0,
        explanation: 'It moves with the start of the harvest.',
      },
      {
        type: 'choice',
        question: 'Who was to rejoice together at the festivals?',
        choices: [
          'Sons and daughters, servants, Levites, foreigners, orphans and widows',
          'Priests and elders only',
          'The fighting men only',
          'Only those who owned land',
        ],
        correctIndex: 0,
        explanation: 'Those without land are named one by one.',
      },
      {
        type: 'choice',
        question: 'Which three festivals were kept each year?',
        choices: [
          'Unleavened Bread, Weeks and Tabernacles',
          'Passover, Day of Atonement and Trumpets',
          'Sabbath, New Moon and Jubilee',
          'Firstfruits, Ingathering and Purim',
        ],
        correctIndex: 0,
        explanation: 'At these times every man went up to the chosen place.',
      },
      {
        type: 'choice',
        question: 'How were they to appear before the LORD?',
        choices: [
          'Not empty-handed, but each in proportion to the blessing received',
          'Each giving the same fixed amount',
          'Paying whatever the priest set',
          'With no gift at all',
        ],
        correctIndex: 0,
        explanation: 'Not a flat amount, but a gift measured against what was received.',
      },
      {
        type: 'choice',
        question: 'What single line does this chapter leave about justice?',
        choices: [
          '"Follow justice and justice alone"',
          '"Leave judgment to the elders"',
          '"Side with your brother"',
          '"A small bribe does no harm"',
        ],
        correctIndex: 0,
        explanation: 'Just before it stands the warning that a bribe blinds the eyes of the wise.',
      },
    ],
  },
  {
    book: 5,
    chapter: 17,
    summary:
      'No ox or sheep with a defect or serious flaw may be offered. If anyone is reported to have bowed to other gods or to the sun, moon or stars, the matter must be investigated thoroughly; if true, the person is executed on the testimony of two or three witnesses — never one — and the witnesses must be the first to raise a hand, for an accusation carries its own weight. Cases too difficult to decide go up to the Levitical priests and the judge at the place the LORD chooses, and their verdict is to be followed. The law of the king stands here too: he must be one the LORD chooses, from among their own people, never a foreigner. He must not acquire great numbers of horses, or many wives who would lead his heart astray, or great amounts of silver and gold. And he is to write for himself a copy of this law and read it all the days of his life, so that his heart is not lifted above his fellow Israelites.',
    questions: [
      {
        type: 'choice',
        question: 'What kind of offering was unacceptable?',
        choices: [
          'An ox or sheep with any defect or serious flaw',
          'Any animal taken in the open field',
          'A firstborn animal',
          'A male animal',
        ],
        correctIndex: 0,
        explanation: 'The text calls it detestable to the LORD.',
      },
      {
        type: 'choice',
        question: 'How many witnesses were needed for a death sentence?',
        choices: ['Two or three', 'One was enough', 'Seven', 'The whole town'],
        correctIndex: 0,
        explanation: 'No one was to be put to death on the testimony of only one witness.',
      },
      {
        type: 'choice',
        question: 'Who had to strike first at an execution?',
        choices: ['The witnesses', 'The priest', 'The judge', 'The victim’s family'],
        correctIndex: 0,
        explanation: 'The accuser has to share the weight of the accusation.',
      },
      {
        type: 'choice',
        question: 'Where were cases too hard to judge to be taken?',
        choices: [
          'To the Levitical priests and the judge at the place the LORD chooses',
          'To the elders of a neighboring town',
          'To the king',
          'They were decided by lot',
        ],
        correctIndex: 0,
        explanation: 'From that verdict they were not to turn aside to the right or the left.',
      },
      {
        type: 'choice',
        question: 'What conditions applied to appointing a king?',
        choices: [
          'One the LORD chooses, from among their own people, never a foreigner',
          'The strongest soldier is chosen',
          'The wealthiest man is chosen',
          'The priest becomes king himself',
        ],
        correctIndex: 0,
        explanation: 'Having a king is not forbidden, but it comes with conditions.',
      },
      {
        type: 'choice',
        question: 'What three things was the king forbidden?',
        choices: [
          'Many horses, many wives, and great hoards of silver and gold',
          'Waging war, collecting taxes and building walls',
          'Judging, sacrificing and traveling',
          'Nothing was forbidden him',
        ],
        correctIndex: 0,
        explanation: 'Solomon would later break all three.',
      },
      {
        type: 'choice',
        question: 'What was the king to do once enthroned?',
        choices: [
          'Write out a copy of the law and read it all his life',
          'Build a new temple',
          'Double the size of the army',
          'Make treaties with neighboring nations',
        ],
        correctIndex: 0,
        explanation: 'So that his heart would not be lifted above his fellow Israelites.',
      },
    ],
  },
  {
    book: 5,
    chapter: 18,
    summary:
      'The Levitical priests and the whole tribe of Levi have no share or inheritance; they eat the food offerings of the LORD, for he is their inheritance. The priest’s portion is the shoulder, the jowls and the inner parts of an ox or sheep, together with the firstfruits of grain, new wine and oil and the first wool from the sheep. Then comes the ban on Canaanite practice: no one who sacrifices a son or daughter in the fire, no divination, no sorcery, no interpreting omens, no medium, spiritist or consulting of the dead. "You must be blameless before the LORD your God." In their place, the LORD promises to raise up for them a prophet like Moses from among their own people, and to put his words in that prophet’s mouth. And he gives them a test: if what a prophet proclaims in the LORD’s name does not take place or come true, the LORD has not spoken it.',
    questions: [
      {
        type: 'choice',
        question: 'What is the inheritance of the tribe of Levi?',
        choices: [
          'The LORD himself is their inheritance',
          'The land east of the Jordan',
          'Six towns',
          'A wage from the king’s storehouse',
        ],
        correctIndex: 0,
        explanation: 'That is why they eat the food offerings made to the LORD.',
      },
      {
        type: 'choice',
        question: 'What was set aside as the priest’s portion?',
        choices: [
          'The shoulder, the jowls and the inner parts',
          'Half the animal',
          'The hide and the horns',
          'The blood and the fat',
        ],
        correctIndex: 0,
        explanation: 'The firstfruits of grain, wine and oil and the first wool go with it.',
      },
      {
        type: 'choice',
        question: 'Which Canaanite practices were banned?',
        choices: [
          'Sacrificing children in the fire, divination, sorcery, mediums and consulting the dead',
          'Farming and herding',
          'Singing and dancing',
          'Trade and commerce',
        ],
        correctIndex: 0,
        explanation: 'It is because of these very practices that the nations are driven out.',
      },
      {
        type: 'choice',
        question: 'What single word completes "You must be ___ before the LORD your God"?',
        choices: ['Blameless', 'Silent', 'Strong', 'Diligent'],
        correctIndex: 0,
        explanation: 'The line stands immediately after the ban on divination.',
      },
      {
        type: 'choice',
        question: 'Whom did the LORD promise to raise up?',
        choices: [
          'A prophet like Moses, from among their own people',
          'A king from a neighboring nation',
          'A new high priest',
          'Twelve judges',
        ],
        correctIndex: 0,
        explanation: 'He would put his own words in that prophet’s mouth.',
      },
      {
        type: 'choice',
        question: 'What occasioned that promise?',
        choices: [
          'Their plea at Horeb not to hear that voice again',
          'Their request for a king',
          'Their craving for meat',
          'Their demand for water',
        ],
        correctIndex: 0,
        explanation: 'The LORD answered, "What they say is good."',
      },
      {
        type: 'choice',
        question: 'What test is given for a true prophet?',
        choices: [
          'If what he says does not take place or come true, the LORD has not spoken',
          'Performing a sign proves him true',
          'A priest’s approval proves him true',
          'Eloquence proves him true',
        ],
        correctIndex: 0,
        explanation: 'Chapter 13 said even a fulfilled sign can be false; the two tests go together.',
      },
    ],
  },
];
