/**
 * 성경통독도우미 콘텐츠 (English) — deuteronomy-01-09
 *
 * scripts/bilingual/ 의 원고에서 자동으로 만들어진 파일이다.
 * **여기를 고치지 말고 원고를 고쳐서 다시 쪼갤 것** — 두 언어의 자리가 어긋난다.
 *
 * memoryVerse 는 한글 파일에만 있다. 영어 본문은 앱이 쓰는 성경(open_en)에서
 * 그대로 가져오므로 여기서 옮기지 않는다.
 */

module.exports = [
  {
    book: 5,
    chapter: 1,
    summary:
      'Deuteronomy is the law as Moses explained it in Moab, east of the Jordan, on the first day of the eleventh month of the fortieth year, after Sihon and Og had been defeated. Moses retraces the road from Horeb. Unable to carry the people’s burden alone, he had appointed wise and respected men from each tribe as commanders of thousands, hundreds, fifties and tens, and charged the judges to hear rich and poor alike without partiality, since judgment belongs to God. At Kadesh Barnea the scouts reported that the land was good, but the people refused to go up and grumbled, and that generation forfeited the land — all but Caleb and Joshua. Those who then went up on their own were chased by the Amorites like a swarm of bees, all the way to Hormah.',
    questions: [
      {
        type: 'choice',
        question: 'When did Moses deliver these words?',
        choices: [
          'The first day of the eleventh month of the fortieth year',
          'The first month of the year they left Egypt',
          'The third month, when they reached Horeb',
          'The second year, while they stayed at Kadesh Barnea',
        ],
        correctIndex: 0,
        explanation: 'It was after Sihon and Og were defeated, just before the Jordan crossing.',
      },
      {
        type: 'choice',
        question: 'How many days’ journey was it from Horeb to Kadesh Barnea?',
        choices: ['Eleven days', 'Forty days', 'Three days', 'Seven days'],
        correctIndex: 0,
        explanation: 'An eleven-day road took them forty years — that is the weight of this line.',
      },
      {
        type: 'choice',
        question: 'What did Moses do when he could not carry the people alone?',
        choices: [
          'He appointed wise, respected men from each tribe as leaders',
          'He reduced the number of the people',
          'He handed everything over to Aaron',
          'He split the camp in two',
        ],
        correctIndex: 0,
        explanation: 'He made them commanders of thousands, hundreds, fifties and tens.',
      },
      {
        type: 'choice',
        question: 'What did Moses charge the judges to do?',
        choices: [
          'Judge without partiality, hearing high and low alike',
          'Favor the tribal leaders',
          'Refuse cases brought by foreigners',
          'Settle the hardest cases themselves',
        ],
        correctIndex: 0,
        explanation: 'Judgment belongs to God; the hardest cases were to be brought to Moses.',
      },
      {
        type: 'choice',
        question: 'How did the people respond when the scouts said the land was good?',
        choices: [
          'They refused to go up and grumbled in their tents',
          'They rejoiced and went up at once',
          'They cast lots to decide who would go first',
          'They asked Moses to go ahead of them',
        ],
        correctIndex: 0,
        explanation: 'They even said, "The LORD hates us."',
      },
      {
        type: 'choice',
        question: 'Who in that generation was named as one who would see the land?',
        choices: ['Caleb son of Jephunneh', 'Aaron', 'Miriam', 'Moses'],
        correctIndex: 0,
        explanation: 'Joshua enters too, but this passage names Caleb outright.',
      },
      {
        type: 'choice',
        question: 'What happened when they went up the hill country against the command?',
        choices: [
          'The Amorites chased them like bees, all the way to Hormah',
          'They captured three towns',
          'The Anakites surrendered',
          'Nothing happened',
        ],
        correctIndex: 0,
        explanation: 'The LORD had warned them in advance, "I will not be with you."',
      },
    ],
  },
  {
    book: 5,
    chapter: 2,
    summary:
      'Israel circled the hill country of Seir and then turned north. The LORD said not to quarrel with the descendants of Esau — not one footstep of their land would be given to Israel — but to buy food and water from them with silver; Moab and Ammon were likewise off limits, since that land belonged to Lot’s descendants. Thirty-eight years passed between leaving Kadesh Barnea and crossing the Zered Valley, and in that time the whole fighting generation died out. Crossing the Arnon, Moses sent a peaceful request to Sihon king of Heshbon for passage, but Sihon refused, for the LORD had made his heart obstinate. Israel fought at Jahaz and took the land. Moses reminds them that through those forty years the LORD was with them and they lacked nothing.',
    questions: [
      {
        type: 'choice',
        question: 'Why would none of Esau’s land be given to Israel?',
        choices: [
          'The LORD had given Mount Seir to Esau as his possession',
          'The land was barren',
          'Esau’s descendants were too strong',
          'Israel already had land enough',
        ],
        correctIndex: 0,
        explanation: 'Leaving a kinsman’s inheritance untouched is the principle of this chapter.',
      },
      {
        type: 'choice',
        question: 'Why were Moab and Ammon not to be harassed?',
        choices: [
          'That land had been given to Lot’s descendants',
          'They had helped Israel',
          'They worshiped the LORD',
          'The land was no good for grazing',
        ],
        correctIndex: 0,
        explanation: 'Lot was Abraham’s nephew, so these peoples too were kin.',
      },
      {
        type: 'choice',
        question: 'How long was it from leaving Kadesh Barnea to crossing the Zered Valley?',
        choices: ['Thirty-eight years', 'Forty years', 'Twenty years', 'Four years'],
        correctIndex: 0,
        explanation: 'Within the whole forty years, this was the span of the wandering.',
      },
      {
        type: 'choice',
        question: 'What happened during that time?',
        choices: [
          'That generation of fighting men all died off in the camp',
          'The population doubled',
          'A new tabernacle was built',
          'The book of the law was completed',
        ],
        correctIndex: 0,
        explanation: 'It happened exactly as the LORD had sworn.',
      },
      {
        type: 'choice',
        question: 'What message did Moses send to Sihon?',
        choices: [
          'They would keep to the main road and pay for food and water',
          'He demanded half the land',
          'He announced he was coming to fight',
          'He offered to pay tribute',
        ],
        correctIndex: 0,
        explanation: 'The text calls it a message "with offers of peace."',
      },
      {
        type: 'choice',
        question: 'Why does the text say Sihon refused passage?',
        choices: [
          'The LORD had made his heart obstinate',
          'Israel had attacked first',
          'He was allied with Moab',
          'The road was already blocked',
        ],
        correctIndex: 0,
        explanation: 'It was so that the LORD might give him into Israel’s hand.',
      },
      {
        type: 'choice',
        question: 'What does Moses say about those forty years in the wilderness?',
        choices: [
          'The LORD was with them and they lacked nothing',
          'There was hunger every year',
          'No one remembered that time',
          'Nothing worth recording happened',
        ],
        correctIndex: 0,
        explanation: 'Even in a season of discipline, the care never stopped.',
      },
    ],
  },
  {
    book: 5,
    chapter: 3,
    summary:
      'Og king of Bashan came out to fight at Edrei, but the LORD handed him over, and Israel took all sixty towns of the region of Argob. Og was the last of the Rephaites; his iron bed was nine cubits long and four wide. Moses gave the land taken from the Arnon to Mount Hermon to Reuben and Gad, and the rest of Gilead with all Bashan to the half-tribe of Manasseh — on condition that their fighting men cross the Jordan armed, ahead of their fellow Israelites. Moses told Joshua not to be afraid, for the LORD himself would fight for them. He begged to cross over too, but the LORD answered, "That is enough; do not speak to me about this again," and told him to look at the land from the top of Pisgah instead.',
    questions: [
      {
        type: 'choice',
        question: 'Which king fought Israel at Edrei?',
        choices: ['Og king of Bashan', 'Sihon king of Heshbon', 'The king of Arad', 'Balak king of Moab'],
        correctIndex: 0,
        explanation: 'Sihon is the king who fought at Jahaz in the previous chapter.',
      },
      {
        type: 'choice',
        question: 'How many towns were taken in the region of Argob?',
        choices: ['Sixty', 'Six', 'Forty-eight', 'Twelve'],
        correctIndex: 0,
        explanation: 'They were fortified towns with high walls, gates and bars.',
      },
      {
        type: 'choice',
        question: 'What detail does the text add about Og?',
        choices: [
          'He was the last of the Rephaites, with an iron bed nine cubits long',
          'He surrendered to Israel',
          'He summoned Balaam',
          'He was a relative of Moses',
        ],
        correctIndex: 0,
        explanation: 'The bed is said to have been kept in Rabbah of the Ammonites.',
      },
      {
        type: 'choice',
        question: 'Which tribes received the land east of the Jordan?',
        choices: [
          'Reuben, Gad and the half-tribe of Manasseh',
          'Judah, Benjamin and Levi',
          'Ephraim and Dan',
          'Asher and Naphtali',
        ],
        correctIndex: 0,
        explanation: 'The agreement of Numbers 32 is confirmed again here.',
      },
      {
        type: 'choice',
        question: 'What condition was placed on them?',
        choices: [
          'Their fighting men must cross over armed, ahead of their brothers',
          'They must send grain every year',
          'They could keep only half their towns',
          'They must share out their livestock',
        ],
        correctIndex: 0,
        explanation: 'Their wives, children and livestock stayed in the towns given to them.',
      },
      {
        type: 'choice',
        question: 'What did Moses say to Joshua?',
        choices: [
          'Do not be afraid; the LORD himself will fight for you',
          'Do not cross the Jordan',
          'Hand your place over to Caleb',
          'Wait another forty days',
        ],
        correctIndex: 0,
        explanation: 'He had seen what was done to Sihon and Og; he was to trust that.',
      },
      {
        type: 'choice',
        question: 'How did the LORD answer Moses’ plea to cross over?',
        choices: [
          '"That is enough; do not speak to me about this again"',
          '"Go over as you wish"',
          '"Cross over together with Aaron"',
          '"Wait one more year"',
        ],
        correctIndex: 0,
        explanation: 'Instead he was to look north, south, east and west from Pisgah.',
      },
    ],
  },
  {
    book: 5,
    chapter: 4,
    summary:
      'Moses urges them to keep the decrees without adding to them or subtracting from them. This is Israel’s wisdom in the eyes of the nations: what other nation has a God so near whenever they pray? At Horeb the people heard a voice out of the fire but saw no form — so they must never carve an image of any kind. The LORD is a consuming fire, a jealous God. If they turn to idols they will quickly perish from the land and be scattered among the nations; yet even there, if they seek him with all their heart and soul, they will find him, for he is merciful and will not forget the covenant he swore to their ancestors. Moses then set apart three cities of refuge east of the Jordan: Bezer, Ramoth in Gilead, and Golan in Bashan.',
    questions: [
      {
        type: 'choice',
        question: 'What were they told never to do with the LORD’s commands?',
        choices: [
          'Neither add to them nor subtract from them',
          'Never write them down',
          'Not teach them to their children',
          'Not make them known to foreigners',
        ],
        correctIndex: 0,
        explanation: 'Adding and subtracting are forbidden with equal weight.',
      },
      {
        type: 'choice',
        question: 'What did the people see at Horeb?',
        choices: [
          'No form at all — they only heard a voice',
          'They saw the LORD from behind',
          'They saw the form of an angel',
          'They saw two stone tablets come down from heaven',
        ],
        correctIndex: 0,
        explanation: 'That fact is itself the ground for the ban on images.',
      },
      {
        type: 'choice',
        question: 'What does the text call the LORD?',
        choices: [
          'A consuming fire, a jealous God',
          'A silent God',
          'A God who is far off',
          'A God seen only in images',
        ],
        correctIndex: 0,
        explanation: 'The phrase follows immediately after the warning not to forget the covenant.',
      },
      {
        type: 'choice',
        question: 'What way remains even after they are scattered among the nations?',
        choices: [
          'If they seek him with all their heart and soul, they will find him',
          'They can never find him again',
          'They must bring many sacrifices',
          'A new covenant must be made',
        ],
        correctIndex: 0,
        explanation: 'The promise stands in the very next verse after the scattering.',
      },
      {
        type: 'choice',
        question: 'How many cities of refuge did Moses set apart east of the Jordan?',
        choices: ['Three', 'Six', 'One', 'Twelve'],
        correctIndex: 0,
        explanation: 'The other three were to be set in Canaan.',
      },
      {
        type: 'choice',
        question: 'What were the names of those three cities?',
        choices: [
          'Bezer, Ramoth in Gilead, and Golan in Bashan',
          'Heshbon, Edrei and Aroer',
          'Dibon, Jazer and Nebo',
          'Shechem, Hebron and Kedesh',
        ],
        correctIndex: 0,
        explanation: 'They served Reuben, Gad and Manasseh respectively.',
      },
      {
        type: 'choice',
        question: 'What did Moses say was Israel’s wisdom before the nations?',
        choices: [
          'Keeping and doing these decrees and laws',
          'Raising a large army',
          'Building strong fortified cities',
          'Making treaties with neighboring nations',
        ],
        correctIndex: 0,
        explanation: 'The nations would say, "Surely this is a wise and understanding people."',
      },
    ],
  },
  {
    book: 5,
    chapter: 5,
    summary:
      'Moses repeats the Ten Commandments, insisting that this covenant was made not with their ancestors but with them, the ones alive here today. No other gods; no carved image; not misusing the LORD’s name; keeping the Sabbath; honoring father and mother; and the prohibitions of murder, adultery, theft, false testimony and coveting. Unlike Exodus, the Sabbath is grounded not in creation but in the exodus — remember that you were slaves in Egypt — and male and female servants are to rest just as their masters do. Terrified by the voice from the fire, the people asked Moses to listen for them and pass on what he heard. The LORD said they had spoken well, and added, "Oh, that their hearts would always be inclined to fear me."',
    questions: [
      {
        type: 'choice',
        question: 'With whom did Moses insist this covenant was made?',
        choices: [
          'Not with their ancestors, but with those alive there that day',
          'Only with Abraham, Isaac and Jacob',
          'Only with the tribe of Levi',
          'Only with descendants yet to be born',
        ],
        correctIndex: 0,
        explanation: 'It is a declaration that this is not old history but present business.',
      },
      {
        type: 'choice',
        question: 'What reason does Deuteronomy give for keeping the Sabbath?',
        choices: [
          'They were slaves in Egypt and the LORD brought them out',
          'God created the world in six days',
          'The manna fell double on the sixth day',
          'Their ancestors had always done so',
        ],
        correctIndex: 0,
        explanation: 'Exodus grounds it in creation; Deuteronomy in liberation.',
      },
      {
        type: 'choice',
        question: 'What was commanded about servants on the Sabbath?',
        choices: [
          'Male and female servants must rest just as you do',
          'Servants were to keep working that day',
          'Servants were to be sent outside the town',
          'The rule did not apply to servants',
        ],
        correctIndex: 0,
        explanation: 'The memory of being slaves becomes a law that gives servants rest.',
      },
      {
        type: 'choice',
        question: 'What promise is attached to honoring father and mother?',
        choices: [
          'That you may live long and it may go well with you',
          'That you will have many children',
          'That your wealth will increase',
          'That your enemies will retreat',
        ],
        correctIndex: 0,
        explanation: 'It is the one commandment tied to a blessing in the land.',
      },
      {
        type: 'choice',
        question: 'Where were the Ten Commandments written?',
        choices: [
          'On two stone tablets',
          'On a leather scroll',
          'On the curtain of the tabernacle',
          'On the pillars of the altar',
        ],
        correctIndex: 0,
        explanation: 'The LORD wrote them himself and gave them to Moses.',
      },
      {
        type: 'choice',
        question: 'What did the people ask Moses after hearing the voice from the fire?',
        choices: [
          '"You go near and listen, and tell us what he says"',
          '"Let us climb the mountain too"',
          '"Carve the law on tablets for us"',
          '"Put Aaron in your place"',
        ],
        correctIndex: 0,
        explanation: 'They added, "We will listen and obey."',
      },
      {
        type: 'choice',
        question: 'How did the LORD respond to what they said?',
        choices: [
          'He said they had spoken well, and wished their hearts would always be so',
          'He struck the people in anger',
          'He gave no answer at all',
          'He rebuked Moses',
        ],
        correctIndex: 0,
        explanation: 'He did not scold their fear but longed for that heart to last.',
      },
    ],
  },
  {
    book: 5,
    chapter: 6,
    summary:
      'Here is the Shema, the heart of Israel’s faith: "Hear, O Israel: the LORD our God, the LORD is one. Love the LORD your God with all your heart and with all your soul and with all your strength." These words are to be kept on the heart, taught diligently to children, spoken of at home and on the road, lying down and getting up, tied on the hand and forehead and written on doorframes and gates. When they eat their fill in towns they did not build, from wells they did not dig and vineyards they did not plant, they must take care not to forget the LORD. They are not to test him as they did at Massah. And when a son later asks what these laws mean, the answer is the story itself: we were slaves in Egypt, and the LORD brought us out with a mighty hand.',
    questions: [
      {
        type: 'choice',
        question: 'How does the Shema begin?',
        choices: [
          '"Hear, O Israel: the LORD our God, the LORD is one"',
          '"I am the LORD who brought you out of Egypt"',
          '"In the beginning God created the heavens and the earth"',
          '"The LORD is my shepherd"',
        ],
        correctIndex: 0,
        explanation: 'These are the words Jews recite morning and evening.',
      },
      {
        type: 'choice',
        question: 'With what are they to love the LORD?',
        choices: [
          'With all their heart, soul and strength',
          'With all their wealth',
          'With all their sacrifices',
          'With all their words',
        ],
        correctIndex: 0,
        explanation: 'This is the verse Jesus named as the greatest commandment.',
      },
      {
        type: 'choice',
        question: 'When were they to talk about these words?',
        choices: [
          'At home, on the road, lying down and getting up',
          'Only at the festivals',
          'Only on the Sabbath',
          'Only when a priest was present',
        ],
        correctIndex: 0,
        explanation: 'The whole of daily life is the place for these words.',
      },
      {
        type: 'choice',
        question: 'Where were these words to be written?',
        choices: [
          'On the doorframes of the house and on the gates',
          'On the tabernacle curtain',
          'On the horns of the altar',
          'On the king’s scepter',
        ],
        correctIndex: 0,
        explanation: 'They were also to be tied on the hand and bound on the forehead.',
      },
      {
        type: 'choice',
        question: 'What were they to guard against once they ate their fill?',
        choices: [
          'Forgetting the LORD who brought them out',
          'Quarreling with their neighbors',
          'Losing their wealth',
          'Losing their towns',
        ],
        correctIndex: 0,
        explanation: 'The danger comes with towns they did not build and wells they did not dig.',
      },
      {
        type: 'choice',
        question: 'Where does Moses point to as an example of testing the LORD?',
        choices: ['Massah', 'Horeb', 'Elim', 'The Arnon'],
        correctIndex: 0,
        explanation: 'It was the place where they quarreled over water.',
      },
      {
        type: 'choice',
        question: 'What answer were they to give a son who asks what the laws mean?',
        choices: [
          '"We were slaves in Egypt, and the LORD brought us out"',
          '"It is a custom kept since our ancestors’ time"',
          '"It is a rule the priests set"',
          '"You do not need to know"',
        ],
        correctIndex: 0,
        explanation: 'The law is taught not as a rulebook but as a story.',
      },
    ],
  },
  {
    book: 5,
    chapter: 7,
    summary:
      'When the LORD drives out the seven nations of Canaan, Israel is to make no treaty and no marriage with them, since sons- and daughters-in-law would bring other gods into the house. Their altars are to be torn down, their sacred stones smashed, their Asherah poles cut and their idols burned. The LORD chose Israel not because they were numerous — they were the fewest of all peoples — but because he loved them and kept the oath sworn to their ancestors. He is faithful, keeping his covenant of love to a thousand generations of those who love him and keep his commands. However many the nations seem, Israel is not to fear but to remember what was done in Egypt. Yet the nations would be driven out little by little, so that wild animals would not multiply against them. The silver and gold on their idols is not to be coveted or taken.',
    questions: [
      {
        type: 'choice',
        question: 'How many nations were to be driven out of Canaan?',
        choices: ['Seven', 'Five', 'Twelve', 'Three'],
        correctIndex: 0,
        explanation: 'Hittites, Girgashites, Amorites, Canaanites, Perizzites, Hivites and Jebusites.',
      },
      {
        type: 'choice',
        question: 'Why were they not to intermarry with those nations?',
        choices: [
          'Because they would turn the children to other gods',
          'Because they spoke another language',
          'Because they were poor',
          'Because it would shrink their land',
        ],
        correctIndex: 0,
        explanation: 'What this chapter guards is not bloodline but worship.',
      },
      {
        type: 'choice',
        question: 'Why did the LORD choose Israel?',
        choices: [
          'Because he loved them and kept the oath sworn to their ancestors',
          'Because they were the most numerous',
          'Because they were the most righteous',
          'Because they were the strongest',
        ],
        correctIndex: 0,
        explanation: 'The text says plainly that they were "the fewest of all peoples."',
      },
      {
        type: 'choice',
        question: 'Where did Israel stand among the nations?',
        choices: [
          'They were the fewest',
          'They were the most numerous',
          'They were about average',
          'They were the wealthiest',
        ],
        correctIndex: 0,
        explanation: 'The ground of their election lay nowhere in themselves.',
      },
      {
        type: 'choice',
        question: 'What does he do for those who love him and keep his commands?',
        choices: [
          'He keeps his covenant of love to a thousand generations',
          'He repays only one generation',
          'He repays only with wealth',
          'He enlarges their territory',
        ],
        correctIndex: 0,
        explanation: 'It is paired with the warning that he repays those who hate him at once.',
      },
      {
        type: 'choice',
        question: 'Why would the nations be driven out little by little?',
        choices: [
          'So that wild animals would not multiply against them',
          'Because Israel’s army was weak',
          'To give the nations a chance to repent',
          'Because dividing the land would take time',
        ],
        correctIndex: 0,
        explanation: 'Land emptied all at once would have gone to the beasts.',
      },
      {
        type: 'choice',
        question: 'What were they told about the silver and gold on the idols?',
        choices: [
          'Do not covet it or take it',
          'Use it for the sanctuary furnishings',
          'Give it to the Levites',
          'Sell it and give to the poor',
        ],
        correctIndex: 0,
        explanation: 'It could become a snare, so it was not even to be brought into the house.',
      },
    ],
  },
  {
    book: 5,
    chapter: 8,
    summary:
      'Remember the forty years in the wilderness, Moses says: the LORD humbled and tested them to know what was in their heart. He let them hunger and fed them manna to teach that people do not live on bread alone but on every word that comes from the mouth of the LORD. Through those forty years their clothes did not wear out and their feet did not swell. The land ahead is one of streams and springs, of wheat and barley, vines, figs, pomegranates, olive oil and honey, where the rocks are iron and copper can be mined from the hills. But when they have eaten their fill, built fine houses and multiplied their silver and gold, their hearts may grow proud and forget the LORD. When they say, "My power and the strength of my hands produced this wealth," they must remember that it is he who gives the ability to produce it.',
    questions: [
      {
        type: 'choice',
        question: 'What was the purpose of the forty years in the wilderness?',
        choices: [
          'To humble and test them, to know what was in their heart',
          'To train them as an army',
          'To wait for the Canaanites to weaken',
          'To finish building the tabernacle',
        ],
        correctIndex: 0,
        explanation: 'The wilderness was discipline, but it was also teaching.',
      },
      {
        type: 'choice',
        question: 'Why did the LORD feed them manna?',
        choices: [
          'To teach that people live not on bread alone but on every word from God',
          'Because they could not farm',
          'To spare their livestock',
          'To make them forget Egyptian food',
        ],
        correctIndex: 0,
        explanation: 'This is the verse Jesus quoted when he was tempted.',
      },
      {
        type: 'choice',
        question: 'What happened to their clothes and feet over the forty years?',
        choices: [
          'Their clothes did not wear out and their feet did not swell',
          'They made new clothes every year',
          'Their clothes all wore out',
          'The text does not say',
        ],
        correctIndex: 0,
        explanation: 'It is a quiet kind of care, deliberately written down.',
      },
      {
        type: 'choice',
        question: 'What produce is listed for the land ahead?',
        choices: [
          'Wheat and barley, vines, figs and pomegranates, olive oil and honey',
          'Rice and millet',
          'Only dates and spices',
          'Nothing at all — it was barren',
        ],
        correctIndex: 0,
        explanation: 'Seven items are listed, one after another.',
      },
      {
        type: 'choice',
        question: 'What is said about the rocks and hills of that land?',
        choices: [
          'The rocks are iron and copper is mined from the hills',
          'It is flat land with no stones',
          'Gold is found in the hills',
          'It is too stony to farm',
        ],
        correctIndex: 0,
        explanation: 'It is a land with not only food but the raw materials of life.',
      },
      {
        type: 'choice',
        question: 'What danger comes with plenty?',
        choices: [
          'A proud heart that forgets the LORD',
          'The envy of neighboring nations',
          'Having their wealth stolen',
          'The land drying up',
        ],
        correctIndex: 0,
        explanation: 'A heart that held in the wilderness can fail in abundance.',
      },
      {
        type: 'choice',
        question: 'What must they remember when they say, "My own power produced this wealth"?',
        choices: [
          'That it is the LORD who gives the ability to produce wealth',
          'That wealth does not last',
          'That all wealth must be given away',
          'That wealth is itself sin',
        ],
        correctIndex: 0,
        explanation: 'Wealth is not forbidden; forgetting its source is.',
      },
    ],
  },
  {
    book: 5,
    chapter: 9,
    summary:
      'They are about to cross the Jordan against nations stronger than themselves, including the Anakites — but the LORD goes ahead of them like a consuming fire. Still, they must not say the land is theirs because of their own righteousness: it is because of the wickedness of those nations, and to keep the oath sworn to their ancestors. "You are a stiff-necked people." As proof Moses recounts the golden calf. He had been on the mountain forty days and forty nights without bread or water; coming down and seeing the cast calf, he threw the two tablets and broke them. He lay prostrate another forty days and nights, and prayed for Aaron, who was also under judgment. The calf he burned, ground to dust and threw into the stream. At Taberah, Massah and Kibroth Hattaavah, and at Kadesh Barnea too, they had rebelled.',
    questions: [
      {
        type: 'choice',
        question: 'What were they told never to say about taking the land?',
        choices: [
          '"The LORD brought me here because of my righteousness"',
          '"This land was always ours"',
          '"We paid for it"',
          '"Our ancestors are buried here"',
        ],
        correctIndex: 0,
        explanation: 'The real reasons are the nations’ wickedness and the oath to the ancestors.',
      },
      {
        type: 'choice',
        question: 'What did Moses call Israel?',
        choices: ['A stiff-necked people', 'A wise people', 'The fewest of peoples', 'A kingdom of priests'],
        correctIndex: 0,
        explanation: 'It is not praise but a fact they were meant to remember.',
      },
      {
        type: 'choice',
        question: 'How long did Moses stay on the mountain to receive the tablets?',
        choices: [
          'Forty days and forty nights, without bread or water',
          'Seven days',
          'Three days',
          'A year',
        ],
        correctIndex: 0,
        explanation: 'He later lay prostrate for another forty days and nights.',
      },
      {
        type: 'choice',
        question: 'Why did Moses throw down and break the two tablets?',
        choices: [
          'He saw that the people had cast an idol calf',
          'The tablets were too heavy',
          'The LORD had told him to',
          'Aaron told him to',
        ],
        correctIndex: 0,
        explanation: 'The broken tablets picture the broken covenant itself.',
      },
      {
        type: 'choice',
        question: 'What did Moses do for Aaron?',
        choices: [
          'He prayed for him',
          'He sent him outside the camp',
          'He took away his priesthood',
          'He did nothing',
        ],
        correctIndex: 0,
        explanation: 'The LORD had been angry enough with Aaron to destroy him.',
      },
      {
        type: 'choice',
        question: 'What was done with the golden calf?',
        choices: [
          'It was burned, ground to dust and thrown into the stream',
          'It was buried in the ground',
          'It was kept in the tabernacle',
          'It was sent back to Egypt',
        ],
        correctIndex: 0,
        explanation: 'Nothing of it was to be left behind.',
      },
      {
        type: 'choice',
        question: 'What other places of rebellion does the chapter name?',
        choices: [
          'Taberah, Massah and Kibroth Hattaavah',
          'Elim, Marah and Rephidim',
          'Sukkoth, Etham and Pi Hahiroth',
          'Heshbon, Edrei and Jahaz',
        ],
        correctIndex: 0,
        explanation: 'The rebellion at Kadesh Barnea is set in the same line.',
      },
    ],
  },
];
