/**
 * 성경통독도우미 콘텐츠 (English) — deuteronomy-19-27
 *
 * scripts/bilingual/ 의 원고에서 자동으로 만들어진 파일이다.
 * **여기를 고치지 말고 원고를 고쳐서 다시 쪼갤 것** — 두 언어의 자리가 어긋난다.
 *
 * memoryVerse 는 한글 파일에만 있다. 영어 본문은 앱이 쓰는 성경(open_en)에서
 * 그대로 가져오므로 여기서 옮기지 않는다.
 */

module.exports = [
  {
    book: 5,
    chapter: 19,
    summary:
      'Three cities of refuge are to be set apart inside the land, with the territory divided in three and roads built, so that anyone can reach one. The example given of accidental killing is an axe head flying off its handle and striking a neighbor — if the road is long the avenger may overtake him, which is why roads must be built. If their territory is enlarged, three more cities are to be added. But a man who lay in wait out of hatred, killed, and then fled to such a city is to be seized by the elders of his own town and handed over to the avenger. The chapter then forbids moving a neighbor’s boundary stone set up by forebears, and requires that every charge be established by two or three witnesses, never one. If a witness is proven false, he receives exactly what he intended for his brother — life for life, eye for eye.',
    questions: [
      {
        type: 'choice',
        question: 'What was commanded along with setting apart the cities of refuge?',
        choices: [
          'Divide the land in three and build roads',
          'Build their walls high',
          'Post watchmen at every gate',
          'Offer a sacrifice there each year',
        ],
        correctIndex: 0,
        explanation: 'If the road is long, the avenger overtakes him.',
      },
      {
        type: 'choice',
        question: 'What example is given of accidental killing?',
        choices: [
          'An axe head flying off its handle and striking a neighbor',
          'Killing someone in battle',
          'A wrong verdict in court',
          'An ox goring a person',
        ],
        correctIndex: 0,
        explanation: 'It happens while two men are out cutting wood together.',
      },
      {
        type: 'choice',
        question: 'What if a man who killed out of hatred fled to a city of refuge?',
        choices: [
          'The elders of his own town seize him and hand him to the avenger',
          'He is protected just the same',
          'He is released if he pays',
          'He waits until the high priest dies',
        ],
        correctIndex: 0,
        explanation: 'A city of refuge was never meant to shelter a murderer.',
      },
      {
        type: 'choice',
        question: 'What were they forbidden to move?',
        choices: [
          'A neighbor’s boundary stone set up by their forebears',
          'The gates of the town',
          'The stones of the altar',
          'The markers of the cities of refuge',
        ],
        correctIndex: 0,
        explanation: 'A boundary is an inheritance; moving it is theft of a family’s portion.',
      },
      {
        type: 'choice',
        question: 'How many witnesses were needed to establish a charge?',
        choices: ['Two or three', 'One', 'Five', 'The entire town'],
        correctIndex: 0,
        explanation: 'The rule from chapter 17 is here widened to every offense.',
      },
      {
        type: 'choice',
        question: 'What happens to a witness proven false?',
        choices: [
          'He receives exactly what he intended for his brother',
          'He only pays a fine',
          'He is driven out of the town',
          'He is only warned',
        ],
        correctIndex: 0,
        explanation: 'If the lie aimed at a death sentence, he takes that place himself.',
      },
      {
        type: 'choice',
        question: 'How does the text phrase this principle?',
        choices: [
          'Life for life, eye for eye, tooth for tooth',
          'Do not repay evil for evil',
          'Repay sevenfold',
          'Forgive and forget',
        ],
        correctIndex: 0,
        explanation: 'Not a licence for revenge but a ceiling: the penalty may not exceed the crime.',
      },
    ],
  },
  {
    book: 5,
    chapter: 20,
    summary:
      'These are the laws of war. However many horses and chariots the enemy has, they are not to be afraid, for the LORD who brought them out of Egypt is with them. As the battle nears, the priest steps forward and tells them not to lose heart, and the officers send four groups home: anyone who has built a new house and not dedicated it, planted a vineyard and not enjoyed it, become engaged and not married, or is simply afraid and fainthearted. When they approach a town, they must first make an offer of peace; if it is accepted, its people become subject to forced labor, and if refused, the town is besieged. The towns of the Canaanite nations given to them as an inheritance are treated differently. And even in a long siege, fruit trees must not be cut down — "Are the trees of the field people?"',
    questions: [
      {
        type: 'choice',
        question: 'What were they told when the enemy looked stronger?',
        choices: [
          'Do not be afraid; the LORD is with you',
          'Fall back and wait',
          'Offer tribute',
          'Seek an alliance',
        ],
        correctIndex: 0,
        explanation: 'The ground is not the size of the army but the exodus from Egypt.',
      },
      {
        type: 'choice',
        question: 'Who addresses the troops first as the battle nears?',
        choices: ['The priest', 'The king', 'The commander of a thousand', 'An elder'],
        correctIndex: 0,
        explanation: 'The first word before battle is not a military order but a word of faith.',
      },
      {
        type: 'choice',
        question: 'Who was sent home from the army?',
        choices: [
          'The one with an undedicated house, an unenjoyed vineyard, an unfinished marriage, and the fainthearted',
          'Only the old',
          'Only the sick',
          'Only the Levites',
        ],
        correctIndex: 0,
        explanation: 'The fainthearted were sent home so their fear would not spread.',
      },
      {
        type: 'choice',
        question: 'What had to come first when approaching a town?',
        choices: [
          'Making an offer of peace',
          'Breaking down the gate',
          'Blocking the wells',
          'Burning their camp',
        ],
        correctIndex: 0,
        explanation: 'If accepted, its people became subject to forced labor.',
      },
      {
        type: 'choice',
        question: 'How did distant towns differ from the Canaanite towns?',
        choices: [
          'In the Canaanite towns nothing that breathed was to be left alive',
          'Peace was offered twice to Canaanite towns',
          'Distant towns were never attacked',
          'There was no difference',
        ],
        correctIndex: 0,
        explanation: 'The stated reason is that living among them would teach their worship.',
      },
      {
        type: 'choice',
        question: 'What was said about trees during a long siege?',
        choices: [
          'Do not cut down fruit trees — are the trees of the field people?',
          'Cut down every tree for siege works',
          'Burn all the trees',
          'Leave the trees to the townspeople',
        ],
        correctIndex: 0,
        explanation: 'Only non-fruit trees could be used for siege works.',
      },
      {
        type: 'choice',
        question: 'Why were fruit trees to be spared?',
        choices: [
          'Because they would be food for the besiegers themselves',
          'Because a god was thought to live in them',
          'Because the enemy prized them',
          'Because they do not burn',
        ],
        correctIndex: 0,
        explanation: 'The law looks past the war to the living that follows it.',
      },
    ],
  },
  {
    book: 5,
    chapter: 21,
    summary:
      'The chapter opens with an unsolved killing: a body found in the open country. The elders and judges measure the distance to the nearest towns, and the elders of the closest town take a heifer that has never been worked or yoked down to a valley with running water, break its neck there, and wash their hands over it, declaring, "Our hands did not shed this blood." Unclaimed blood is not simply let go. A captive woman taken as a wife must first shave her head, trim her nails, put aside her captive’s clothing and mourn her parents a full month; if her husband is later not pleased with her, she must be let go free and never sold for money. The son of an unloved wife, if he is the firstborn, must be recognized as such and given a double portion. And a body hung on a pole must not remain overnight but be buried the same day.',
    questions: [
      {
        type: 'choice',
        question: 'What was done when a body was found and the killer was unknown?',
        choices: [
          'Distances were measured and the nearest town performed a rite with a heifer',
          'The body was simply buried and forgotten',
          'A neighboring nation was held responsible',
          'Lots were cast to name a culprit',
        ],
        correctIndex: 0,
        explanation: 'The point is that unclaimed blood is never simply let go.',
      },
      {
        type: 'choice',
        question: 'What kind of heifer was used in that rite?',
        choices: [
          'One never worked and never yoked',
          'The oldest in the herd',
          'Any animal, even a blemished one',
          'One raised by a priest',
        ],
        correctIndex: 0,
        explanation: 'It had to be an animal never put to human use.',
      },
      {
        type: 'choice',
        question: 'What did the elders say as they washed their hands?',
        choices: [
          '"Our hands did not shed this blood"',
          '"We know who did this"',
          '"This town is above judgment"',
          '"Let the blood fall on us"',
        ],
        correctIndex: 0,
        explanation: 'A prayer follows that innocent blood not remain among the people.',
      },
      {
        type: 'choice',
        question: 'What had to precede marrying a captive woman?',
        choices: [
          'A full month of mourning for her parents',
          'Paying a price for her',
          'Getting a priest’s permission',
          'Nothing at all',
        ],
        correctIndex: 0,
        explanation: 'She also shaved her head, trimmed her nails and set aside her captive’s clothes.',
      },
      {
        type: 'choice',
        question: 'What if he was later not pleased with her?',
        choices: [
          'Let her go free; never sell her for money',
          'Make her a slave',
          'Give her to someone else',
          'Keep her in the house anyway',
        ],
        correctIndex: 0,
        explanation: '"Since you have dishonored her, you must not treat her as a slave."',
      },
      {
        type: 'choice',
        question: 'What if the firstborn son was the son of an unloved wife?',
        choices: [
          'He must be recognized as firstborn and given a double portion',
          'The loved wife’s son becomes the firstborn',
          'The father decides as he pleases',
          'The sons share equally',
        ],
        correctIndex: 0,
        explanation: 'A father’s affection may not rewrite the order of inheritance.',
      },
      {
        type: 'choice',
        question: 'What was to be done with a body hung on a pole?',
        choices: [
          'Do not leave it overnight; bury it the same day',
          'Leave it there seven days',
          'Throw it outside the town',
          'Burn it',
        ],
        correctIndex: 0,
        explanation: '"Anyone hung on a pole is under God’s curse" — Paul quotes this in Galatians.',
      },
    ],
  },
  {
    book: 5,
    chapter: 22,
    summary:
      'If you see a fellow Israelite’s ox or sheep straying, do not ignore it but take it back; if you do not know the owner, keep it until he comes looking. If a donkey or ox has fallen on the road, do not ignore it but help lift it up. A woman must not wear men’s clothing nor a man women’s. A mother bird must be let go and only the young taken. A new house must have a parapet on the roof so that no one falls and blood comes on the house. Do not sow two kinds of seed in a vineyard, do not plow with an ox and a donkey yoked together, do not wear cloth woven of wool and linen, and make tassels on the four corners of your cloak. The latter part gives laws on marriage and sexual conduct: a husband who falsely slanders his bride is punished, fined a hundred shekels of silver, and may never divorce her as long as he lives.',
    questions: [
      {
        type: 'choice',
        question: 'What if you see a neighbor’s ox or sheep straying?',
        choices: [
          'Do not ignore it — take it back to him',
          'Keep it for yourself',
          'Hand it over to the elders',
          'Walk on past',
        ],
        correctIndex: 0,
        explanation: 'If the owner is unknown, keep it until he comes looking.',
      },
      {
        type: 'choice',
        question: 'What if a donkey or ox has fallen on the road?',
        choices: [
          'Do not ignore it — help lift it up',
          'Wait for its owner',
          'Just move it off the road',
          'Help only for a fee',
        ],
        correctIndex: 0,
        explanation: '"Do not ignore it" is the repeated command of this chapter.',
      },
      {
        type: 'choice',
        question: 'What rule applies when you come upon a bird’s nest?',
        choices: [
          'Let the mother go and take only the young',
          'Take both the mother and the young',
          'Take nothing at all',
          'Take only the eggs',
        ],
        correctIndex: 0,
        explanation: 'A promise of long life and blessing is attached to it.',
      },
      {
        type: 'choice',
        question: 'What had to be built into a new house?',
        choices: [
          'A parapet on the roof',
          'A nameplate on the doorpost',
          'An altar in the courtyard',
          'A cellar',
        ],
        correctIndex: 0,
        explanation: 'If anyone falls, the blood comes on the house.',
      },
      {
        type: 'choice',
        question: 'What were they to make on their cloaks?',
        choices: ['Tassels on the four corners', 'An embroidered name', 'A leather belt', 'Gold buttons'],
        correctIndex: 0,
        explanation: 'A reminder of the commands, seen every time the cloak is worn.',
      },
      {
        type: 'choice',
        question: 'Which pairing was forbidden?',
        choices: [
          'Plowing with an ox and a donkey yoked together',
          'Yoking two oxen together',
          'Loading a donkey with burdens',
          'Grazing sheep and goats together',
        ],
        correctIndex: 0,
        explanation: 'Animals of different strength and stride are not put under one yoke.',
      },
      {
        type: 'choice',
        question: 'What happens to a husband whose slander of his bride is proven false?',
        choices: [
          'He is punished, fined a hundred shekels, and may never divorce her',
          'He need only write a certificate of divorce',
          'There is no penalty',
          'He is expelled from the town',
        ],
        correctIndex: 0,
        explanation: 'The fine was given to the young woman’s father.',
      },
    ],
  },
  {
    book: 5,
    chapter: 23,
    summary:
      'The chapter opens with who may enter the assembly of the LORD. Ammonites and Moabites are excluded forever, because they did not meet Israel with bread and water on the way out of Egypt and hired Balaam to curse them — yet the LORD turned that curse into a blessing. Edomites, however, are not to be despised, for they are kin, nor Egyptians, for Israel lived as foreigners in their land; their third generation may enter the assembly. On campaign, a latrine is to be kept outside the camp and covered with a spade, since the LORD moves about in the camp. A slave who has escaped from his master must not be handed back, but may settle wherever he chooses and must not be oppressed. No interest is to be charged to a fellow Israelite; vows must be paid without delay; and one may eat one’s fill in a neighbor’s vineyard but put nothing in a basket.',
    questions: [
      {
        type: 'choice',
        question: 'Why were Ammonites and Moabites excluded from the assembly?',
        choices: [
          'They did not meet Israel with food and water, and hired Balaam to curse them',
          'They had defeated Israel in battle',
          'Because they descended from Lot',
          'Because they worshiped idols',
        ],
        correctIndex: 0,
        explanation: 'The reason given is how they treated travelers passing through.',
      },
      {
        type: 'choice',
        question: 'What became of Balaam’s attempted curse?',
        choices: [
          'The LORD turned the curse into a blessing',
          'The curse fell as spoken',
          'Balaam gave it up himself',
          'The king of Moab called it off',
        ],
        correctIndex: 0,
        explanation: 'The reason given is simply, "because the LORD your God loves you."',
      },
      {
        type: 'choice',
        question: 'Which two peoples were not to be despised?',
        choices: [
          'Edomites and Egyptians',
          'Ammonites and Moabites',
          'Amalekites and Midianites',
          'Canaanites and Hittites',
        ],
        correctIndex: 0,
        explanation: 'Edom is kin, and in Egypt Israel itself lived as a foreigner.',
      },
      {
        type: 'choice',
        question: 'What was commanded about the camp on campaign?',
        choices: [
          'Keep a latrine outside the camp and cover it with a spade',
          'Build an altar inside the camp',
          'Light no fires at night',
          'Move the camp every day',
        ],
        correctIndex: 0,
        explanation: 'The LORD moves about in the camp, so the camp must be kept holy.',
      },
      {
        type: 'choice',
        question: 'What was to be done with a slave who had escaped his master?',
        choices: [
          'Do not hand him back; let him live where he chooses, and do not oppress him',
          'Return him to his master',
          'Sell him for a price',
          'Send him outside the town',
        ],
        correctIndex: 0,
        explanation: 'This runs directly against the law of the surrounding nations.',
      },
      {
        type: 'choice',
        question: 'What was forbidden when lending to a fellow Israelite?',
        choices: ['Charging interest', 'Taking a pledge', 'Writing a contract', 'Setting a deadline'],
        correctIndex: 0,
        explanation: 'Interest could be charged to a foreigner but never to a brother.',
      },
      {
        type: 'choice',
        question: 'What was allowed and what forbidden in a neighbor’s field or vineyard?',
        choices: [
          'Eat your fill or pluck heads by hand, but put none in a basket and use no sickle',
          'Touch nothing at all',
          'Harvest as much as you like',
          'Anything goes if you pay for it',
        ],
        correctIndex: 0,
        explanation: 'The hungry traveler is fed, but the harvest stays the owner’s.',
      },
    ],
  },
  {
    book: 5,
    chapter: 24,
    summary:
      'The chapter begins with the certificate of divorce and the rule against remarrying a former wife who has since married another. A newly married man is exempt from the army and from any duty for one year, so that he can bring happiness to his wife. A millstone may not be taken as a pledge — that is taking a life in pledge. Anyone who kidnaps a fellow Israelite and enslaves or sells him must die. A creditor may not enter a house to seize a pledge but must wait outside, and a poor man’s pledge must be returned by sunset. A hired worker’s wages must be paid the same day, before sunset. Parents are not put to death for their children, nor children for their parents; each dies for his own sin. Justice must not be denied the foreigner or the fatherless, a widow’s cloak may not be taken in pledge, and the forgotten sheaf, the olives left on the branch and the grapes left on the vine belong to the foreigner, the fatherless and the widow.',
    questions: [
      {
        type: 'choice',
        question: 'What rule applied to a newly married man?',
        choices: [
          'For one year he is free from the army and from any duty',
          'He goes to the army at once',
          'He may not leave town for two years',
          'There was no such rule',
        ],
        correctIndex: 0,
        explanation: 'The stated reason is "to bring happiness to the wife he has married."',
      },
      {
        type: 'choice',
        question: 'What could never be taken as a pledge?',
        choices: ['A millstone, or even its upper stone', 'A cloak', 'A donkey', 'A plow'],
        correctIndex: 0,
        explanation: 'Taking it, the text says, is taking a life in pledge.',
      },
      {
        type: 'choice',
        question: 'How was a pledge to be collected?',
        choices: [
          'Stay outside; do not enter the house',
          'Go in and choose it yourself',
          'Enter together with an elder',
          'Collect it at night',
        ],
        correctIndex: 0,
        explanation: 'It keeps the creditor from stepping across a poor man’s threshold.',
      },
      {
        type: 'choice',
        question: 'What was said about a hired worker’s wages?',
        choices: [
          'Pay the same day, before sunset',
          'Pay once a week',
          'Pay once a month',
          'Pay after the harvest',
        ],
        correctIndex: 0,
        explanation: 'Because he is poor and is counting on it.',
      },
      {
        type: 'choice',
        question: 'What does the chapter say about guilt?',
        choices: [
          'Each person dies for his own sin',
          'Children bear their father’s guilt',
          'The whole household is punished together',
          'The town shares the guilt',
        ],
        correctIndex: 0,
        explanation: 'Fathers are not put to death for children, nor children for fathers.',
      },
      {
        type: 'choice',
        question: 'What was forbidden regarding a widow?',
        choices: [
          'Taking her cloak in pledge',
          'Lending to her',
          'Hiring her as a worker',
          'Harvesting her field',
        ],
        correctIndex: 0,
        explanation: 'It stands beside the command not to deny justice to the foreigner or the fatherless.',
      },
      {
        type: 'choice',
        question: 'What was to be left behind at harvest?',
        choices: [
          'The forgotten sheaf and what remains on the olive trees and vines',
          'Half the field',
          'The best of the crop',
          'Nothing was left',
        ],
        correctIndex: 0,
        explanation: 'This law is what lets Ruth glean in the book of Ruth.',
      },
    ],
  },
  {
    book: 5,
    chapter: 25,
    summary:
      'A flogging may not exceed forty lashes; beyond that, a brother would be degraded in your eyes. Do not muzzle an ox while it is treading out the grain. If a man dies without a son, his brother is to marry the widow, and her first son carries on the dead brother’s name; if the brother refuses, she takes off his sandal before the elders, spits in his face, and his family is called "The Family of the Unsandaled." Do not keep two differing weights in your bag or two differing measures in your house, but only honest and accurate ones. Finally, remember what Amalek did: they met Israel on the road when they were weary, cut down all who were lagging behind, and had no fear of God.',
    questions: [
      {
        type: 'choice',
        question: 'What was the limit on a flogging?',
        choices: ['Forty lashes', 'Ten lashes', 'A hundred lashes', 'There was no limit'],
        correctIndex: 0,
        explanation: 'Beyond that, the text says, your brother would be degraded in your eyes.',
      },
      {
        type: 'choice',
        question: 'What must not be done to an ox treading out grain?',
        choices: ['Do not muzzle it', 'Do not let it rest', 'Do not give it water', 'Do not yoke it'],
        correctIndex: 0,
        explanation: 'The animal that works is to eat from the work it does.',
      },
      {
        type: 'choice',
        question: 'What if a man died without a son?',
        choices: [
          'His brother marries the widow, and her first son carries on the dead man’s name',
          'The widow returns to her father’s house',
          'The inheritance goes to the king',
          'The inheritance goes to the priests',
        ],
        correctIndex: 0,
        explanation: 'This is the law Boaz acts on in the book of Ruth.',
      },
      {
        type: 'choice',
        question: 'What happened if the brother refused that duty?',
        choices: [
          'His sandal was removed before the elders and she spat in his face',
          'He paid a fine',
          'He was driven from the town',
          'Nothing happened',
        ],
        correctIndex: 0,
        explanation: 'His family was called "The Family of the Unsandaled."',
      },
      {
        type: 'choice',
        question: 'What must not be kept in the bag or the house?',
        choices: [
          'Two differing weights and two differing measures',
          'Foreign money',
          'Images of idols',
          'Borrowed tools',
        ],
        correctIndex: 0,
        explanation: 'Only honest and accurate weights and measures were allowed.',
      },
      {
        type: 'choice',
        question: 'Which nation were they told never to forget?',
        choices: ['Amalek', 'Moab', 'Ammon', 'Edom'],
        correctIndex: 0,
        explanation: 'They were even told to blot out the memory of Amalek from under heaven.',
      },
      {
        type: 'choice',
        question: 'What had that nation done?',
        choices: [
          'They cut down the weak lagging behind when Israel was weary',
          'They blocked the road and refused passage',
          'They hired Balaam to curse Israel',
          'They filled in the wells',
        ],
        correctIndex: 0,
        explanation: 'The text’s verdict on them: "they had no fear of God."',
      },
    ],
  },
  {
    book: 5,
    chapter: 26,
    summary:
      'Once they are settled in the land and have gathered its first produce, they are to put the firstfruits in a basket, carry them to the place the LORD chooses, and make a confession before the priest: "My father was a wandering Aramean, and he went down into Egypt with a few people and became a great nation there. The Egyptians mistreated us, and we cried out, and the LORD brought us out with a mighty hand and gave us this land." Then they set the basket down, bow in worship, and rejoice with the Levite and the foreigner. In the third year, after completing the tithe, they give it to the Levite, the foreigner, the fatherless and the widow to eat their fill in their towns, and declare that they have obeyed and neither violated nor forgotten the command. On this day two declarations are exchanged: the people declare the LORD to be their God, and he declares them his treasured possession.',
    questions: [
      {
        type: 'choice',
        question: 'How were the firstfruits of the land to be brought?',
        choices: [
          'In a basket, carried to the chosen place and set before the priest',
          'Burned at home',
          'Left standing in the field',
          'Sold, with the money given instead',
        ],
        correctIndex: 0,
        explanation: 'The act of carrying it comes with a confession attached.',
      },
      {
        type: 'choice',
        question: 'How does that confession begin?',
        choices: [
          '"My father was a wandering Aramean"',
          '"I am a righteous man"',
          '"This land was always ours"',
          '"I earned this by my own labor"',
        ],
        correctIndex: 0,
        explanation: 'The confession starts not with merit but with a wandering ancestor.',
      },
      {
        type: 'choice',
        question: 'What story does that confession tell?',
        choices: [
          'Down to Egypt, oppression, crying out, deliverance, and this land',
          'Creation and the flood',
          'The line of kings',
          'The order of the festivals',
        ],
        correctIndex: 0,
        explanation: 'Israel’s creed turns out to be a story.',
      },
      {
        type: 'choice',
        question: 'With whom were they to rejoice after presenting the firstfruits?',
        choices: [
          'The Levite and the foreigner living among them',
          'The priests only',
          'The elders only',
          'They were to do it alone and in silence',
        ],
        correctIndex: 0,
        explanation: 'Those without land are brought into the place of joy.',
      },
      {
        type: 'choice',
        question: 'To whom was the third-year tithe given?',
        choices: [
          'The Levite, the foreigner, the fatherless and the widow',
          'The king and his officials',
          'The men at war',
          'The priests alone',
        ],
        correctIndex: 0,
        explanation: 'They were to eat in the towns and be satisfied.',
      },
      {
        type: 'choice',
        question: 'What declaration accompanied that tithe?',
        choices: [
          '"I have done everything you commanded; I have not violated or forgotten"',
          '"I will bring even more"',
          '"I have kept back my share"',
          'Nothing was said',
        ],
        correctIndex: 0,
        explanation: 'It is a report rendered once the sharing is done.',
      },
      {
        type: 'choice',
        question: 'What two declarations were exchanged that day?',
        choices: [
          'The people declared the LORD their God, and he declared them his treasured possession',
          'A promise of a king and a promise of taxes',
          'An oath of war and an oath of alliance',
          'A promise to divide land and a promise to build a temple',
        ],
        correctIndex: 0,
        explanation: 'A covenant is not one side declaring but two.',
      },
    ],
  },
  {
    book: 5,
    chapter: 27,
    summary:
      'On the day they cross the Jordan they are to set up large stones, coat them with plaster and write on them all the words of this law, clearly and carefully. The stones are to be set up on Mount Ebal, and there an altar of uncut stones, on which no iron tool has been used, is to be built for burnt offerings and fellowship offerings, and they are to rejoice. Moses and the Levitical priests declare: "Be silent, Israel, and listen! You have now become the people of the LORD your God." After crossing, Simeon, Levi, Judah, Issachar, Joseph and Benjamin stand on Mount Gerizim to bless, and Reuben, Gad, Asher, Zebulun, Dan and Naphtali stand on Mount Ebal to pronounce curses. The Levites recite twelve curses in a loud voice and all the people answer "Amen" to each — against idols, dishonoring parents, moving a boundary stone, misleading the blind, denying justice to the foreigner, the fatherless and the widow, secret murder, bribery, and finally anyone who does not uphold the words of this law.',
    questions: [
      {
        type: 'choice',
        question: 'What were they to do on the day they crossed the Jordan?',
        choices: [
          'Set up large stones, coat them with plaster and write the law on them',
          'Found a town and name it',
          'Raise the banners of the twelve tribes',
          'Appoint a king',
        ],
        correctIndex: 0,
        explanation: 'They were to write it "very clearly."',
      },
      {
        type: 'choice',
        question: 'On which mountain were the stones to be set up?',
        choices: ['Mount Ebal', 'Mount Gerizim', 'Mount Sinai', 'Mount Nebo'],
        correctIndex: 0,
        explanation: 'The stones and the altar stand on the mountain of the curses.',
      },
      {
        type: 'choice',
        question: 'What rule applied to building that altar?',
        choices: [
          'Use uncut stones; do not use any iron tool on them',
          'Use the twelve largest stones',
          'Overlay it with bronze',
          'Build it of earth only',
        ],
        correctIndex: 0,
        explanation: 'It is an altar untouched by human shaping.',
      },
      {
        type: 'choice',
        question: 'What did Moses and the Levitical priests proclaim?',
        choices: [
          '"Be silent and listen — today you have become the people of the LORD your God"',
          '"Today you have received a king"',
          '"This land is now yours"',
          '"Tomorrow you will cross the Jordan"',
        ],
        correctIndex: 0,
        explanation: 'It is the declaration of the day the covenant is inscribed.',
      },
      {
        type: 'choice',
        question: 'Which tribes stood on Mount Gerizim to bless?',
        choices: [
          'Simeon, Levi, Judah, Issachar, Joseph and Benjamin',
          'Reuben, Gad, Asher, Zebulun, Dan and Naphtali',
          'Judah and Benjamin only',
          'Levi alone',
        ],
        correctIndex: 0,
        explanation: 'The other six stood on Mount Ebal for the curses.',
      },
      {
        type: 'choice',
        question: 'Who recited the curses, and how did the people answer?',
        choices: [
          'The Levites recited them aloud and the people answered "Amen"',
          'A priest read silently and the people said nothing',
          'Moses recited them alone',
          'The elders took turns reciting them',
        ],
        correctIndex: 0,
        explanation: 'To each of the twelve curses the people said "Amen" for themselves.',
      },
      {
        type: 'choice',
        question: 'Whom did the final curse fall on?',
        choices: [
          'Anyone who does not uphold the words of this law',
          'Anyone who makes an idol',
          'Anyone who takes a bribe',
          'Anyone who dishonors a parent',
        ],
        correctIndex: 0,
        explanation: 'Paul quotes this verse in Galatians 3.',
      },
    ],
  },
];
