/**
 * 성경통독도우미 콘텐츠 (English) — numbers-01-24
 *
 * scripts/bilingual/ 의 원고에서 자동으로 만들어진 파일이다.
 * **여기를 고치지 말고 원고를 고쳐서 다시 쪼갤 것** — 두 언어의 자리가 어긋난다.
 *
 * memoryVerse 는 한글 파일에만 있다. 영어 본문은 앱이 쓰는 성경(open_en)에서
 * 그대로 가져오므로 여기서 옮기지 않는다.
 */

module.exports = [
  {
    book: 4,
    chapter: 1,
    summary:
      'Numbers begins, and true to its name it opens by counting. On the first day of the second month of the second year after leaving Egypt, God tells Moses to count, tribe by tribe, everyone twenty years old or more who can serve in the army, with one man from each tribe helping. The total comes to 603,550. The tribe of Levi is left out of this count: instead of going to war they were given charge of the tabernacle, to guard it and carry it. It is a chapter of long lists, but its point is clear — God does not look at a crowd as a lump. He counts one person at a time.',
    questions: [
      {
        type: 'choice',
        question: 'When does Numbers begin?',
        choices: [
          'The first day of the second month of the second year after leaving Egypt',
          'The first month of the year they left Egypt',
          'After entering Canaan',
          'After forty years had passed',
        ],
        correctIndex: 0,
        explanation: 'It is about a month after the tabernacle was set up (Exodus 40).',
      },
      {
        type: 'choice',
        question: 'Who was to be counted?',
        choices: [
          'Everyone twenty years old or more able to serve in the army',
          'All the men and women',
          'Only the priests',
          'Only the heads of families',
        ],
        correctIndex: 0,
        explanation: 'They were counted by tribe, by clan and by family, name by name.',
      },
      {
        type: 'choice',
        question: 'What was the total?',
        choices: ['603,550', '400,000', '1,000,000', '100,000'],
        correctIndex: 0,
        explanation: 'This counts only men twenty and over, so the whole company was far larger.',
      },
      {
        type: 'choice',
        question: 'Which tribe was left out of the count?',
        choices: ['Levi', 'Judah', 'Benjamin', 'Dan'],
        correctIndex: 0,
        explanation:
          'Instead of going to war they were given charge of the tabernacle, to guard and carry it.',
      },
      {
        type: 'choice',
        question: 'Did Moses do the counting alone?',
        choices: [
          'No — one man from each tribe helped',
          'Yes — he did it alone',
          'Only the priests did it',
          'The people wrote themselves down',
        ],
        correctIndex: 0,
        explanation: 'Their names are written down. One man counting alone leaves no way to check.',
      },
      {
        type: 'choice',
        question: 'What was the tribe of Levi given to do?',
        choices: [
          'To guard the tabernacle and carry it',
          'To farm the land',
          'To make roads',
          'To lead the fighting',
        ],
        correctIndex: 0,
        explanation: 'They also took it down and set it up, and no one else was to come near.',
      },
      {
        type: 'choice',
        question: 'What does this chapter show?',
        choices: [
          'God does not treat a crowd as a lump; He counts one by one',
          'That the army was strong',
          'That Israel was wealthy',
          'That numbers do not matter',
        ],
        correctIndex: 0,
        explanation: 'That is what "counting them by name" means.',
      },
    ],
  },
  {
    book: 4,
    chapter: 2,
    summary:
      'This chapter arranges the camp. The tabernacle stands in the middle and the twelve tribes surround it, three on each side. Judah leads on the east, Reuben on the south, Ephraim on the west and Dan on the north, and the Levites camp right around the tabernacle itself. What the arrangement says is plain: God is in the middle of His people, and everyone faces Him. When they set out, they moved in the same order. The chapter closes with one short line — the Israelites did everything the LORD commanded.',
    questions: [
      {
        type: 'choice',
        question: 'What stood at the centre of the camp?',
        choices: ['The tabernacle', 'Moses’ tent', 'A well', 'The grain store'],
        correctIndex: 0,
        explanation: 'The layout itself says that God is in the middle of His people.',
      },
      {
        type: 'choice',
        question: 'Which tribe led on the east side?',
        choices: ['Judah', 'Reuben', 'Ephraim', 'Dan'],
        correctIndex: 0,
        explanation:
          'It is where the sun rises and where the tabernacle entrance faced. Judah also set out first.',
      },
      {
        type: 'choice',
        question: 'How many tribes stood on each side?',
        choices: ['Three', 'Two', 'Four', 'Six'],
        correctIndex: 0,
        explanation: 'The twelve tribes were divided three to a side, east, south, west and north.',
      },
      {
        type: 'choice',
        question: 'Where did the Levites camp?',
        choices: ['Right around the tabernacle', 'Outside the camp', 'At the far east end', 'It was not set'],
        correctIndex: 0,
        explanation: 'They stood between the tabernacle and the people, guarding it.',
      },
      {
        type: 'choice',
        question: 'How was the marching order set?',
        choices: [
          'The same as the camping order',
          'The largest tribes first',
          'By casting lots',
          'It changed each time',
        ],
        correctIndex: 0,
        explanation: 'The way they camped was the way they marched.',
      },
      {
        type: 'choice',
        question: 'How does the chapter close?',
        choices: [
          'They did everything the LORD commanded',
          'The people grumbled',
          'They lost their way',
          'A fight broke out',
        ],
        correctIndex: 0,
        explanation: 'Against the grumbling that follows, this obedience stands out.',
      },
      {
        type: 'choice',
        question: 'What does this arrangement say?',
        choices: [
          'God is at the centre and everyone faces Him',
          'The strongest tribe takes the best spot',
          'The places mean nothing',
          'The priests stand furthest out',
        ],
        correctIndex: 0,
        explanation: 'The crowd around the throne in Revelation is the same picture.',
      },
    ],
  },
  {
    book: 4,
    chapter: 3,
    summary:
      'The Levites are counted separately and their duties divided. Of Aaron’s four sons, Nadab and Abihu died offering unauthorised fire, so Eleazar and Ithamar remain to serve as priests. The Levites are divided into three families — Gershon, Kohath and Merari — and each is assigned a part of the tabernacle: Gershon the curtains and coverings, Kohath the ark and the furnishings, Merari the frames and posts. Then comes an important word. On the day God struck down the firstborn in Egypt He claimed Israel’s firstborn as His own, and now He takes the Levites in their place. One group stands in for another.',
    questions: [
      {
        type: 'choice',
        question: 'Which two sons of Aaron remained to serve as priests?',
        choices: ['Eleazar and Ithamar', 'Nadab and Abihu', 'Gershon and Kohath', 'Kohath and Merari'],
        correctIndex: 0,
        explanation: 'Nadab and Abihu died offering unauthorised fire (Leviticus 10).',
      },
      {
        type: 'choice',
        question: 'Into how many families were the Levites divided?',
        choices: ['Three', 'Two', 'Four', 'Twelve'],
        correctIndex: 0,
        explanation: 'Gershon, Kohath and Merari.',
      },
      {
        type: 'choice',
        question: 'Which family was given charge of the ark and the furnishings?',
        choices: ['Kohath', 'Gershon', 'Merari', 'Aaron'],
        correctIndex: 0,
        explanation: 'They carried the holiest things, so the rules for handling them were the strictest.',
      },
      {
        type: 'choice',
        question: 'Whom did God take the Levites in place of?',
        choices: ['The firstborn of Israel', 'The priests', 'The elders', 'The soldiers'],
        correctIndex: 0,
        explanation: 'On the day He struck Egypt’s firstborn He claimed Israel’s firstborn as His own.',
      },
      {
        type: 'choice',
        question: 'Which family was given charge of the curtains and coverings?',
        choices: ['Gershon', 'Kohath', 'Merari', 'Judah'],
        correctIndex: 0,
        explanation: 'Merari was given the frames, posts and bases.',
      },
      {
        type: 'choice',
        question: 'How did counting the Levites differ from the earlier count?',
        choices: [
          'Every male a month old or more was counted',
          'Only those twenty and over',
          'Only the heads of families',
          'They were not counted',
        ],
        correctIndex: 0,
        explanation:
          'They were being counted as those who belong to God, not as soldiers, so the standard differed.',
      },
      {
        type: 'choice',
        question: 'What picture of redemption does this chapter give?',
        choices: [
          'One standing in the place of another',
          'Paying double',
          'Putting off a punishment',
          'No picture at all',
        ],
        correctIndex: 0,
        explanation:
          'The Levites stood in for the firstborn, and where the numbers fell short a price was paid.',
      },
    ],
  },
  {
    book: 4,
    chapter: 4,
    summary:
      'This chapter sets out in detail what each Levite family carries and how. The work belongs to men from thirty to fifty years old. The Kohathites carry the holiest things, but before they come near, Aaron and his sons go in first and cover everything with the curtains. Only then do the Kohathites come and lift them, and they are warned that touching or looking at the holy things means death. It sounds severe, but the rule was there to protect them. Gershon and Merari could use carts; Kohath had to carry on their shoulders. Later, in David’s day, breaking this rule cost Uzzah his life.',
    questions: [
      {
        type: 'choice',
        question: 'From what age did this work begin?',
        choices: ['Thirty', 'Twenty', 'Twenty-five', 'Forty'],
        correctIndex: 0,
        explanation: 'From thirty to fifty years old they served at the tabernacle.',
      },
      {
        type: 'choice',
        question: 'Who went in before the Kohathites carried the holy things?',
        choices: ['Aaron and his sons', 'Moses', 'The Gershonites', 'The tribal leaders'],
        correctIndex: 0,
        explanation:
          'They went in and covered everything, and only then did the Kohathites come and lift it.',
      },
      {
        type: 'choice',
        question: 'How did the Kohathites carry their load?',
        choices: ['On their shoulders', 'On carts', 'On donkeys', 'They dragged it'],
        correctIndex: 0,
        explanation: 'Gershon and Merari used carts, but Kohath had to carry theirs.',
      },
      {
        type: 'choice',
        question: 'What was said about touching or looking at the holy things?',
        choices: [
          'They would die',
          'They would pay a fine',
          'They would be unclean for a day',
          'Nothing would happen',
        ],
        correctIndex: 0,
        explanation:
          'It sounds severe, but the rule protected them — which is why everything was covered first.',
      },
      {
        type: 'choice',
        question: 'Who later died for breaking this rule?',
        choices: ['Uzzah', 'Saul', 'Achan', 'Korah'],
        correctIndex: 0,
        explanation:
          'In David’s day the ark was carried on a cart, and he reached out to steady it (2 Samuel 6).',
      },
      {
        type: 'choice',
        question: 'What does this chapter set out?',
        choices: [
          'Who carries what, and how',
          'Who offers the sacrifices',
          'Where to camp',
          'When to keep the festivals',
        ],
        correctIndex: 0,
        explanation: 'The tabernacle travelled, so carrying it was itself an act of service.',
      },
      {
        type: 'choice',
        question: 'What lies behind such detailed rules?',
        choices: [
          'The holier the thing you handle, the more there is to keep',
          'To make the work difficult',
          'To punish the Levites',
          'Nothing in particular',
        ],
        correctIndex: 0,
        explanation: 'The rules were a fence that protected them, not one that shut them out.',
      },
    ],
  },
  {
    book: 4,
    chapter: 5,
    summary:
      'These are rules for keeping the camp clean. The first part deals with wronging another person — and notice that it is called "being unfaithful to the LORD." A wrong done to a person is treated as a sin against God. So the wrongdoer confesses, and repays in full with a fifth added to the person harmed; if there is no one to repay, it goes to the priest. The second part is a hard passage about a husband who suspects his wife. It should be read knowing that in that world a husband could put his wife away on his own judgement — this required the matter to be brought to the tabernacle, before God.',
    questions: [
      {
        type: 'choice',
        question: 'What does this chapter call wronging another person?',
        choices: [
          'Being unfaithful to the LORD',
          'A small mistake',
          'A matter between neighbours',
          'Something unavoidable',
        ],
        correctIndex: 0,
        explanation: 'A wrong done to a person is treated as a sin against God.',
      },
      {
        type: 'choice',
        question: 'How much had to be added when repaying?',
        choices: ['A fifth', 'A tenth', 'Half', 'Double'],
        correctIndex: 0,
        explanation: 'It is the same rule as in Leviticus 5 and 6.',
      },
      {
        type: 'choice',
        question: 'What had to be done before repaying?',
        choices: ['Confessing the sin', 'Fasting', 'Bringing witnesses', 'Waiting'],
        correctIndex: 0,
        explanation: 'Admitting it comes before the ritual.',
      },
      {
        type: 'choice',
        question: 'What if there was no one to repay?',
        choices: [
          'It went to the priest',
          'Nothing had to be repaid',
          'It went to the king',
          'It was burned',
        ],
        correctIndex: 0,
        explanation: 'A debt did not vanish just because the person to repay was gone.',
      },
      {
        type: 'choice',
        question: 'Who was to be sent outside the camp?',
        choices: [
          'Those with a skin disease or a discharge, and those unclean from a dead body',
          'The poor',
          'Foreigners',
          'Children',
        ],
        correctIndex: 0,
        explanation: 'The cleanness rules of Leviticus carry straight into life in the camp.',
      },
      {
        type: 'choice',
        question: 'What did the procedure in the second half prevent in that world?',
        choices: [
          'A husband putting his wife away on his own judgement',
          'A wife leaving home',
          'Divorce itself',
          'It prevented nothing',
        ],
        correctIndex: 0,
        explanation: 'The matter had to be brought to the tabernacle, before God.',
      },
      {
        type: 'choice',
        question: 'What is the theme of this chapter as a whole?',
        choices: [
          'Keeping the place where they live together clean',
          'Preparing for war',
          'Rules for festivals',
          'Ordaining priests',
        ],
        correctIndex: 0,
        explanation: 'God dwelt in the middle of the camp, so what went on inside it mattered.',
      },
    ],
  },
  {
    book: 4,
    chapter: 6,
    summary:
      'The first part gives the rules for the Nazirite vow. For a period the person chooses, they drink no wine or anything from grapes, do not cut their hair, and stay away from dead bodies. Unlike the priesthood you did not have to be born into it — anyone could step forward, man or woman. The second part holds the best-known blessing in the Bible: "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you; the LORD turn his face toward you and give you peace." Churches still send people out with these words today.',
    questions: [
      {
        type: 'choice',
        question: 'Which was NOT forbidden to a Nazirite?',
        choices: ['Working', 'Drinking wine', 'Cutting their hair', 'Going near a dead body'],
        correctIndex: 0,
        explanation: 'They lived their normal life, keeping these three things for the set period.',
      },
      {
        type: 'choice',
        question: 'Who could take the Nazirite vow?',
        choices: [
          'Anyone, man or woman, who chose to',
          'Only priestly families',
          'Only the tribe of Levi',
          'Only leaders',
        ],
        correctIndex: 0,
        explanation: 'It was not something you had to be born into; it was chosen.',
      },
      {
        type: 'choice',
        question: '"The LORD bless you and ____ you."',
        choices: ['Keep', 'Exalt', 'Call', 'Send'],
        correctIndex: 0,
        explanation: 'It is the first line of the best-known blessing in the Bible.',
      },
      {
        type: 'choice',
        question: 'How many lines does this blessing have?',
        choices: ['Three', 'Two', 'Four', 'Seven'],
        correctIndex: 0,
        explanation: 'It moves from blessing and keeping, to grace, to peace.',
      },
      {
        type: 'choice',
        question: 'Who was told to speak this blessing?',
        choices: ['Aaron and his sons', 'Moses alone', 'The elders', 'Anyone at all'],
        correctIndex: 0,
        explanation: 'God said, "So they will put my name on the Israelites, and I will bless them."',
      },
      {
        type: 'choice',
        question: 'What happened when the Nazirite period ended?',
        choices: [
          'They shaved their head and put the hair in the fire of the sacrifice',
          'Nothing',
          'They extended the period',
          'They left the camp',
        ],
        correctIndex: 0,
        explanation: 'It was a vow with a clear beginning and a clear end.',
      },
      {
        type: 'choice',
        question: 'What does the last line of the blessing give?',
        choices: ['Peace', 'Wealth', 'Victory', 'Long life'],
        correctIndex: 0,
        explanation: 'The Hebrew shalom is not just quiet; it means everything being whole.',
      },
    ],
  },
  {
    book: 4,
    chapter: 7,
    summary:
      'This is one of the longest chapters in the Bible. On the day the tabernacle was set up, the leaders of the twelve tribes brought their dedication offerings — and although all twelve brought exactly the same things, the Bible writes out the same list twelve times over. It could have been shortened; it was not. Each person’s giving is recorded with their name. Earlier in the chapter carts and oxen are given to the Levites, but none to the Kohathites: what they carried had to go on their shoulders. The chapter ends quietly — when Moses entered the tent, he heard the voice speaking from between the two cherubim above the atonement cover.',
    questions: [
      {
        type: 'choice',
        question: 'Why does this chapter repeat the same list twelve times?',
        choices: [
          'To record each person’s giving with their own name',
          'To fill up space',
          'A copying mistake',
          'No one knows why',
        ],
        correctIndex: 0,
        explanation: 'It could have been shortened; it was not.',
      },
      {
        type: 'choice',
        question: 'Which Levite family received no carts or oxen?',
        choices: ['Kohath', 'Gershon', 'Merari', 'Aaron'],
        correctIndex: 0,
        explanation: 'The holy things they carried had to go on their shoulders.',
      },
      {
        type: 'choice',
        question: 'Who brought the offerings?',
        choices: ['The leaders of the twelve tribes', 'The priests', 'The Levites', 'All the people'],
        correctIndex: 0,
        explanation: 'One leader brought his offering each day, over twelve days.',
      },
      {
        type: 'choice',
        question: 'What did Moses hear at the end of the chapter?',
        choices: [
          'The voice speaking from between the two cherubim above the atonement cover',
          'The people singing',
          'The sound of trumpets',
          'Nothing at all',
        ],
        correctIndex: 0,
        explanation: 'It is the very place God said in Exodus 25, "There I will meet with you."',
      },
      {
        type: 'choice',
        question: 'How was the order of the offerings decided?',
        choices: [
          'By the camping order, one leader a day',
          'First come, first served',
          'The largest tribes first',
          'By casting lots',
        ],
        correctIndex: 0,
        explanation: 'Judah came first — the same order as the camp in chapter 2.',
      },
      {
        type: 'choice',
        question: 'How did the twelve offerings compare?',
        choices: [
          'They were identical',
          'Each tribe brought something different',
          'Larger tribes gave more',
          'It is not recorded',
        ],
        correctIndex: 0,
        explanation: 'No one gave more or less — and still all twelve are written out.',
      },
      {
        type: 'choice',
        question: 'What does this chapter say to us today?',
        choices: [
          'God does not lump giving together; He remembers each person',
          'Those who give more are better',
          'Giving should be kept secret',
          'Only leaders should give',
        ],
        correctIndex: 0,
        explanation: 'It is the same heart as counting people by name in chapter 1.',
      },
    ],
  },
  {
    book: 4,
    chapter: 8,
    summary:
      'The first part is a short instruction to set up the seven lamps so they light the space in front of the lampstand. The second is the ceremony for setting apart the Levites — and it differs from ordaining priests. They are sprinkled with water, shave their whole bodies, wash their clothes, and are then presented before the whole assembly, and the assembly lays hands on them. The people laying on hands says, "These men serve in our place." Levites began at twenty-five and retired at fifty — but after retiring they still helped their brothers. They were released from carrying the load, but kept a place alongside.',
    questions: [
      {
        type: 'choice',
        question: 'Where were the seven lamps to shine?',
        choices: [
          'The space in front of the lampstand',
          'Inside the Most Holy Place',
          'Outside the courtyard',
          'The tabernacle entrance',
        ],
        correctIndex: 0,
        explanation: 'The light did not shine on itself but on what stood in front.',
      },
      {
        type: 'choice',
        question: 'Who laid hands on the Levites?',
        choices: ['The whole assembly', 'Moses alone', 'Aaron alone', 'No one did'],
        correctIndex: 0,
        explanation: 'It says, "These men serve in our place."',
      },
      {
        type: 'choice',
        question: 'At what age did a Levite begin service?',
        choices: ['Twenty-five', 'Thirty', 'Twenty', 'Forty'],
        correctIndex: 0,
        explanation: 'The thirty in chapter 4 refers to the heavy carrying work.',
      },
      {
        type: 'choice',
        question: 'What did a Levite do after retiring at fifty?',
        choices: [
          'He still helped his brothers',
          'He left the tabernacle',
          'He joined another tribe',
          'It is not recorded',
        ],
        correctIndex: 0,
        explanation: 'He was released from carrying the load but kept a place alongside.',
      },
      {
        type: 'choice',
        question: 'Which was NOT part of setting apart the Levites?',
        choices: [
          'Pouring anointing oil on their heads',
          'Sprinkling water on them',
          'Shaving their whole bodies',
          'Washing their clothes',
        ],
        correctIndex: 0,
        explanation: 'Anointing belonged to ordaining priests; the Levites had a different ceremony.',
      },
      {
        type: 'choice',
        question: 'Why did the Levites belong to God?',
        choices: [
          'Because they stood in place of Israel’s firstborn',
          'Because they were the most numerous',
          'Because they were the strongest',
          'Because they volunteered',
        ],
        correctIndex: 0,
        explanation: 'The picture of redemption given in chapter 3 becomes a ceremony here.',
      },
      {
        type: 'choice',
        question: 'What does this chapter say about service?',
        choices: [
          'There is a time to step back, and a place alongside even after',
          'Once taken up, it can never be laid down',
          'Only the young can serve',
          'Age does not matter',
        ],
        correctIndex: 0,
        explanation: 'Both the age to begin and the age to step back are set.',
      },
    ],
  },
  {
    book: 4,
    chapter: 9,
    summary:
      'They keep the second Passover in the wilderness — and a problem comes up. Some men had become unclean by touching a dead body and could not keep it that day. They come to Moses and ask, "Why should we be kept from it?" Moses does not decide on his own; he asks God. The answer is remarkable: such a person, and anyone away on a journey, is to keep it **one month later**. A new path was opened inside the rule. The rest of the chapter is about the cloud. When it settled on the tabernacle they camped; when it lifted they set out — a day, two days, a month or a year, they moved by the cloud.',
    questions: [
      {
        type: 'choice',
        question: 'What did the men who could not keep the Passover do?',
        choices: [
          'They came and asked Moses',
          'They just let it pass',
          'They kept it in secret',
          'They left the camp',
        ],
        correctIndex: 0,
        explanation: 'They asked, "Why should we be kept from it?"',
      },
      {
        type: 'choice',
        question: 'What did Moses do with their question?',
        choices: [
          'He did not decide on his own; he asked God',
          'He said no at once',
          'He said yes at once',
          'He handed it to the elders',
        ],
        correctIndex: 0,
        explanation: 'Where a new rule was needed, a person did not make it up.',
      },
      {
        type: 'choice',
        question: 'What was God’s answer?',
        choices: [
          'Keep it one month later',
          'Keep it next year',
          'Do not keep it',
          'Let someone else keep it for you',
        ],
        correctIndex: 0,
        explanation: 'A new path was opened inside the rule.',
      },
      {
        type: 'choice',
        question: 'Who else did this exception cover?',
        choices: [
          'Anyone away on a journey',
          'Anyone who was ill',
          'Anyone who was poor',
          'Anyone who was old',
        ],
        correctIndex: 0,
        explanation: 'What is unavoidable is treated differently from carelessness.',
      },
      {
        type: 'choice',
        question: 'What decided when they camped and when they set out?',
        choices: [
          'The cloud over the tabernacle',
          'Moses’ judgement',
          'A fixed calendar',
          'What the people wanted',
        ],
        correctIndex: 0,
        explanation: 'When the cloud settled they camped; when it lifted they set out.',
      },
      {
        type: 'choice',
        question: 'How long did the cloud stay?',
        choices: [
          'A day, a month or a year — it was never fixed',
          'Always seven days',
          'Always a month',
          'Always one night',
        ],
        correctIndex: 0,
        explanation: 'Never knowing when they would move was what wilderness life looked like.',
      },
      {
        type: 'choice',
        question: 'What does this chapter show?',
        choices: [
          'The rules were not there to shut people out',
          'That rules can never change',
          'That the unclean are abandoned',
          'That Passover does not matter',
        ],
        correctIndex: 0,
        explanation: 'For those who could not keep it, a way to keep it was opened.',
      },
    ],
  },
  {
    book: 4,
    chapter: 10,
    summary:
      'Two silver trumpets are made as signals. Both sounded, and the whole assembly gathered; one, and the leaders came. A loud blast meant the camp was setting out. Trumpets sounded for battle and at the festivals too. And then at last they leave Sinai: on the twentieth day of the second month of the second year, the cloud lifted and the people marched in their set order. Moses twice asks Hobab, his father-in-law’s son, to come with them. And here is what Moses said whenever the ark set out: "Rise up, LORD! May your enemies be scattered; may your foes flee before you."',
    questions: [
      {
        type: 'choice',
        question: 'What did sounding both trumpets mean?',
        choices: ['The whole assembly was to gather', 'Go out to battle', 'Break camp', 'Rest'],
        correctIndex: 0,
        explanation: 'One trumpet called only the leaders.',
      },
      {
        type: 'choice',
        question: 'When did Israel leave Sinai?',
        choices: [
          'The twentieth day of the second month of the second year',
          'The first month of the first year',
          'The third month of the third year',
          'It is not recorded',
        ],
        correctIndex: 0,
        explanation: 'They had stayed at Sinai for nearly a year.',
      },
      {
        type: 'choice',
        question: 'What did Moses say whenever the ark set out?',
        choices: [
          '"Rise up, LORD! May your enemies be scattered"',
          '"Give us rest, LORD"',
          '"Wait, LORD"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'There were also words for whenever the ark came to rest.',
      },
      {
        type: 'choice',
        question: 'Whom did Moses ask to come with them?',
        choices: ['Hobab', 'Jethro', 'Aaron', 'Joshua'],
        correctIndex: 0,
        explanation: 'He knew the wilderness, so Moses said, "You can be our eyes."',
      },
      {
        type: 'choice',
        question: 'What did the marching order follow?',
        choices: [
          'The camp arrangement set in chapter 2',
          'It was decided each day',
          'They cast lots',
          'The largest tribes first',
        ],
        correctIndex: 0,
        explanation: 'Judah led the way and Dan brought up the rear.',
      },
      {
        type: 'choice',
        question: 'Who was to blow the trumpets?',
        choices: ['The priests, Aaron’s sons', 'The tribal leaders', 'Anyone', 'All the Levites'],
        correctIndex: 0,
        explanation: 'It was set as a lasting ordinance for the generations to come.',
      },
      {
        type: 'choice',
        question: 'Where does this chapter stand in the story?',
        choices: [
          'The preparations are done and the journey finally begins',
          'Entering Canaan',
          'Leaving Egypt',
          'The end of the forty years',
        ],
        correctIndex: 0,
        explanation: 'Chapters 1–10 were preparation; from 11 the journey itself begins.',
      },
    ],
  },
  {
    book: 4,
    chapter: 11,
    summary:
      'They have barely set out when the grumbling breaks out: they miss the fish, cucumbers, melons, leeks, onions and garlic of Egypt. They remember the table of the place where they were slaves and forget what the place was. Moses breaks down too: "Did I conceive all these people?" God answers in two ways — He shares the Spirit that was on Moses with seventy elders so they can carry the load with him, and He sends quail. But the heart of the chapter is what He says about the meat: "Is the LORD’s arm too short?" When two men prophesy out in the camp and Joshua wants them stopped, Moses answers, "I wish that all the LORD’s people were prophets."',
    questions: [
      {
        type: 'choice',
        question: 'What did the people long for?',
        choices: [
          'The fish, cucumbers and garlic they ate in Egypt',
          'Their houses in Egypt',
          'Their clothes in Egypt',
          'Their work in Egypt',
        ],
        correctIndex: 0,
        explanation: 'They remembered the table and forgot what the place actually was.',
      },
      {
        type: 'choice',
        question: '"Is the LORD’s arm too ____?" Fill in the blank.',
        choices: ['Short', 'Heavy', 'Far', 'Small'],
        correctIndex: 0,
        explanation: 'It was His answer when Moses asked how meat could be found for 600,000.',
      },
      {
        type: 'choice',
        question: 'How did God lighten Moses’ load?',
        choices: [
          'He shared the Spirit with seventy elders so they carried it with him',
          'He reduced the number of people',
          'He gave Moses a rest',
          'He handed it to Aaron',
        ],
        correctIndex: 0,
        explanation: 'It runs the same direction as Jethro’s advice in Exodus 18.',
      },
      {
        type: 'choice',
        question: 'What did Moses say about the two men prophesying in the camp?',
        choices: [
          '"I wish that all the LORD’s people were prophets"',
          '"Stop them"',
          '"Send them out of the camp"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'When Joshua wanted them stopped, Moses asked, "Are you jealous for my sake?"',
      },
      {
        type: 'choice',
        question: 'What meat did God send?',
        choices: ['Quail', 'Sheep', 'Cattle', 'Fish'],
        correctIndex: 0,
        explanation: 'A wind drove them in from the sea and they fell all around the camp.',
      },
      {
        type: 'choice',
        question: 'What did Moses say to God?',
        choices: [
          '"Did I conceive all these people?"',
          '"Give me more to carry"',
          '"Punish the people"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'The Bible does not hide that a leader can break down.',
      },
      {
        type: 'choice',
        question: 'What does this chapter say about the manna?',
        choices: [
          'It tasted like something made with olive oil',
          'It had no taste',
          'It could not be eaten',
          'It is not recorded',
        ],
        correctIndex: 0,
        explanation: 'The problem was not the manna but the eyes that looked at it.',
      },
    ],
  },
  {
    book: 4,
    chapter: 12,
    summary:
      'This time it is the people closest to Moses who turn against him — his sister Miriam and his brother Aaron. The stated reason is the Cushite woman he married, but the next line shows what was really underneath: "Has the LORD spoken only through Moses? Hasn’t he also spoken through us?" It was about position. Right here the Bible sets down one line about Moses: he was more humble than anyone else on the face of the earth. God calls the three of them out, and Miriam becomes leprous. And Moses cries out, "Please, God, heal her!" The first person to pray for the sister who had turned on him was Moses.',
    questions: [
      {
        type: 'choice',
        question: 'Which two spoke against Moses?',
        choices: ['Miriam and Aaron', 'Korah and Dathan', 'Joshua and Caleb', 'Nadab and Abihu'],
        correctIndex: 0,
        explanation: 'That it was his own brother and sister is what makes this chapter sting.',
      },
      {
        type: 'choice',
        question: 'Which words showed what was really underneath?',
        choices: [
          '"Has the LORD spoken only through Moses?"',
          '"Moses has grown old"',
          '"Moses is lazy"',
          'Nothing was said',
        ],
        correctIndex: 0,
        explanation: 'The stated reason was the marriage; what it was really about was position.',
      },
      {
        type: 'choice',
        question: 'What one line does the Bible set down about Moses here?',
        choices: [
          'He was more humble than anyone else on the face of the earth',
          'He was the strongest of all',
          'He was the wisest of all',
          'He lived longer than anyone',
        ],
        correctIndex: 0,
        explanation: 'The line comes exactly where he does not defend himself.',
      },
      {
        type: 'choice',
        question: 'What happened to Miriam?',
        choices: ['She became leprous', 'She lost her voice', 'She left the camp', 'Nothing happened'],
        correctIndex: 0,
        explanation:
          'She stayed outside the camp seven days, and the people did not move on until she returned.',
      },
      {
        type: 'choice',
        question: 'Who prayed for Miriam first?',
        choices: ['Moses', 'Aaron', 'Joshua', 'The people'],
        correctIndex: 0,
        explanation: 'He cried out for the sister who had turned against him.',
      },
      {
        type: 'choice',
        question: 'What did God say about Moses?',
        choices: [
          'With him I speak face to face, clearly',
          'He does not know me',
          'I will replace him',
          'Nothing was said',
        ],
        correctIndex: 0,
        explanation: 'To other prophets, He said, He speaks in visions and dreams.',
      },
      {
        type: 'choice',
        question: 'What does this chapter show?',
        choices: [
          'God defends the one who does not defend himself',
          'That siblings must never quarrel',
          'That marriage needs care',
          'That illness is punishment',
        ],
        correctIndex: 0,
        explanation: 'Moses said not a word in reply, and God stepped in Himself.',
      },
    ],
  },
  {
    book: 4,
    chapter: 13,
    summary:
      'Twelve men are sent to explore Canaan — one leader from each tribe. Among them is Hoshea of Ephraim, whose name Moses changes to Joshua. After forty days they come back. The land is so good that a single cluster of grapes has to be carried on a pole between two men. But the reports split. Ten of them say, "The people are strong and the cities are fortified; we seemed like grasshoppers." Caleb quiets the people and says, "We should go up and take possession of the land, for we can certainly do it." They saw the same land and said different things.',
    questions: [
      {
        type: 'choice',
        question: 'How many men were sent to explore?',
        choices: ['Twelve', 'Two', 'Seven', 'Seventy'],
        correctIndex: 0,
        explanation: 'One from each tribe, and all of them leaders.',
      },
      {
        type: 'choice',
        question: 'Whose name did Moses change?',
        choices: ['Hoshea → Joshua', 'Caleb → Jephunneh', 'Aaron → Eleazar', 'No one’s'],
        correctIndex: 0,
        explanation: 'Joshua means "the LORD saves."',
      },
      {
        type: 'choice',
        question: 'How many days did they explore?',
        choices: ['Forty days', 'Seven days', 'A month', 'A hundred days'],
        correctIndex: 0,
        explanation: 'These forty days become the reason for the forty years that follow.',
      },
      {
        type: 'choice',
        question: 'What did Caleb say?',
        choices: [
          '"We should go up and take possession of the land, for we can certainly do it"',
          '"Let us wait a while"',
          '"Let us go back"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'He said it after quieting the people.',
      },
      {
        type: 'choice',
        question: 'What did the ten compare themselves to?',
        choices: ['Grasshoppers', 'Sheep', 'Dust', 'Children'],
        correctIndex: 0,
        explanation: 'They said, "We seemed like grasshoppers in our own eyes."',
      },
      {
        type: 'choice',
        question: 'How was the single cluster of grapes carried?',
        choices: [
          'Two men carried it on a pole',
          'One man carried it',
          'It was put on a cart',
          'It was loaded on a donkey',
        ],
        correctIndex: 0,
        explanation: 'Even the ten did not deny that the land was good.',
      },
      {
        type: 'choice',
        question: 'What does the split in this chapter show?',
        choices: [
          'People can look at the same thing and say different things',
          'That scouting was a mistake',
          'That the land was bad',
          'That Caleb was lying',
        ],
        correctIndex: 0,
        explanation: 'What split them was not what they saw but whom they measured it against.',
      },
    ],
  },
  {
    book: 4,
    chapter: 14,
    summary:
      'This is the heaviest chapter in Numbers. Hearing the report of the ten, the whole assembly weeps all night and says they should go back to Egypt — some even talk of choosing a leader to take them back. Joshua and Caleb tear their clothes and plead: "The LORD is with us. Do not be afraid of them." The people talk of stoning them. When God’s anger burns, Moses intercedes again — and this time he takes his stand on the very words God used to describe Himself: slow to anger, abounding in love. God forgives, but that generation will not enter the land. For each of the forty days they explored it, a year: forty years.',
    questions: [
      {
        type: 'choice',
        question: 'What did the people say they should do?',
        choices: ['Choose a leader and go back to Egypt', 'Send more scouts', 'Wait', 'Go up at once'],
        correctIndex: 0,
        explanation: 'They wept all night and grumbled against Moses and Aaron.',
      },
      {
        type: 'choice',
        question: 'What did Joshua and Caleb say?',
        choices: [
          '"The LORD is with us. Do not be afraid of them"',
          '"We saw it wrongly"',
          '"It is better to go back"',
          'They said nothing',
        ],
        correctIndex: 0,
        explanation: 'They tore their clothes and pleaded, but the people talked of stoning them.',
      },
      {
        type: 'choice',
        question: 'What did Moses base his plea on?',
        choices: [
          'That God is slow to anger and abounding in love',
          'That the people had done well',
          'His own hard work',
          'That the land was good',
        ],
        correctIndex: 0,
        explanation: 'He quoted back the very words God spoke about Himself in Exodus 34.',
      },
      {
        type: 'choice',
        question: 'Where do the forty years come from?',
        choices: [
          'A year for each of the forty days they explored',
          'From Moses’ age',
          'From the size of the land',
          'There is no reason given',
        ],
        correctIndex: 0,
        explanation: 'God said, "For forty years you will suffer for your sins."',
      },
      {
        type: 'choice',
        question: 'Who from that generation did enter the land?',
        choices: ['Joshua and Caleb', 'Moses and Aaron', 'Miriam', 'No one'],
        correctIndex: 0,
        explanation: 'Of Caleb it says he "has a different spirit."',
      },
      {
        type: 'choice',
        question: 'What happened to those who tried to go up afterwards?',
        choices: [
          'They went up without the ark or Moses, and were beaten',
          'They took Canaan',
          'Nothing happened',
          'They turned back',
        ],
        correctIndex: 0,
        explanation: 'Obedience after the moment had passed was not obedience.',
      },
      {
        type: 'choice',
        question: 'What did God do even while forgiving?',
        choices: [
          'He kept that generation from entering the land',
          'Nothing at all',
          'He brought them straight in',
          'He replaced Moses',
        ],
        correctIndex: 0,
        explanation: 'Forgiveness and consequence stand together here; you cannot read only one half.',
      },
    ],
  },
  {
    book: 4,
    chapter: 15,
    summary:
      'Right after the heavy verdict of chapter 14 come these words: "After you enter the land where you are to live…" In the very place where He said they would not enter, God gives rules for after they enter. That generation would not go in, but the promise itself was still standing. Then the grain and drink offerings that go with sacrifices are set, and it is stated plainly that the same rules apply to the foreigner. Unintentional sin and defiant sin are dealt with separately, and there is the case of a man caught gathering wood on the Sabbath. At the end God tells them to put tassels with a blue cord on their garments — so that every time they see them they remember the commands.',
    questions: [
      {
        type: 'choice',
        question: 'How do the words right after chapter 14 begin?',
        choices: [
          '"After you enter the land where you are to live"',
          '"You will die in the wilderness"',
          '"Go back to Egypt"',
          'Nothing is said',
        ],
        correctIndex: 0,
        explanation: 'That generation would not enter, but the promise itself was still standing.',
      },
      {
        type: 'choice',
        question: 'What is the rule about the foreigner?',
        choices: [
          'The same law applies to you and to the foreigner',
          'A foreigner may not bring offerings',
          'A foreigner brings only half',
          'There is no rule',
        ],
        correctIndex: 0,
        explanation: 'This principle keeps coming back through Numbers.',
      },
      {
        type: 'choice',
        question: 'What were the tassels on their garments for?',
        choices: [
          'So that every time they saw them they remembered the LORD’s commands',
          'To make the clothes stronger',
          'To tell the tribes apart',
          'To set a price',
        ],
        correctIndex: 0,
        explanation: 'Remembering does not happen by itself, so something visible was tied on.',
      },
      {
        type: 'choice',
        question: 'What colour was the cord on the tassels?',
        choices: ['Blue', 'Scarlet', 'Purple', 'White'],
        correctIndex: 0,
        explanation: 'It is the same colour used in the tabernacle curtains.',
      },
      {
        type: 'choice',
        question: 'Which two kinds of sin does this chapter separate?',
        choices: [
          'Unintentional sin and defiant sin',
          'Big sins and small sins',
          'Adults’ sins and children’s sins',
          'It does not separate them',
        ],
        correctIndex: 0,
        explanation: 'For unintentional sin there was a path of atonement through an offering.',
      },
      {
        type: 'choice',
        question: 'What was the man caught on the Sabbath doing?',
        choices: ['Gathering wood', 'Trading', 'Fighting', 'Travelling'],
        correctIndex: 0,
        explanation: 'Here too the people did not decide on their own; they asked God.',
      },
      {
        type: 'choice',
        question: 'What was set to accompany the sacrifices?',
        choices: [
          'A grain offering of flour and oil, and a drink offering of wine',
          'Incense and salt',
          'Bread and water',
          'Nothing',
        ],
        correctIndex: 0,
        explanation: 'The amounts differed according to the size of the sacrifice.',
      },
    ],
  },
  {
    book: 4,
    chapter: 16,
    summary:
      'Korah, Dathan and Abiram, with 250 leaders, rise against Moses and Aaron. Their words sound reasonable: "The whole community is holy — why then do you set yourselves above them?" Moses does not defend himself; he falls face down. Then he proposes that they all stand before the LORD with censers and let God choose. The next day the ground splits and swallows Korah’s company, and fire consumes the 250 who were offering incense. Yet the day after, the people grumble against Moses again. When a plague breaks out, Aaron takes a censer and stands between the dead and the living to stop it — putting his own body between the plague and the people who had turned on him.',
    questions: [
      {
        type: 'choice',
        question: 'What did those who rose against Moses say?',
        choices: [
          '"The whole community is holy — why do you set yourselves above them?"',
          '"Moses is old"',
          '"The land is bad"',
          '"There is no food"',
        ],
        correctIndex: 0,
        explanation: 'It was not untrue. The question was what they meant to do with it.',
      },
      {
        type: 'choice',
        question: 'What did Moses do first when he heard it?',
        choices: ['He fell face down', 'He argued back', 'He got angry', 'He walked away'],
        correctIndex: 0,
        explanation: 'As in chapter 12, he did not defend himself.',
      },
      {
        type: 'choice',
        question: 'What did Moses propose?',
        choices: [
          'Stand before the LORD with censers and let God choose',
          'Take a vote',
          'Let the elders decide',
          'He would step down',
        ],
        correctIndex: 0,
        explanation: 'Instead of fighting it out among themselves, he left it to God.',
      },
      {
        type: 'choice',
        question: 'What did Aaron do when the plague broke out?',
        choices: [
          'He took a censer and stood between the dead and the living',
          'He left the camp',
          'He hid',
          'He did nothing',
        ],
        correctIndex: 0,
        explanation: 'He put his own body between the plague and the people who had turned on him.',
      },
      {
        type: 'choice',
        question: 'What happened to Korah’s company?',
        choices: [
          'The ground split open and swallowed them',
          'They were sent out of the camp',
          'They fell ill',
          'Nothing happened',
        ],
        correctIndex: 0,
        explanation: 'The 250 who were offering incense were consumed by fire.',
      },
      {
        type: 'choice',
        question: 'What did the people do the next day?',
        choices: ['They grumbled against Moses again', 'They repented', 'They stayed quiet', 'They left'],
        correctIndex: 0,
        explanation: 'The chapter shows that seeing does not by itself change anyone.',
      },
      {
        type: 'choice',
        question: 'How was the censer used twice in this chapter?',
        choices: [
          'Once to fight over position, once to save lives',
          'Both times to fight over position',
          'Both times to save lives',
          'It was used only once',
        ],
        correctIndex: 0,
        explanation: 'The same object; what it was used for is what differed.',
      },
    ],
  },
  {
    book: 4,
    chapter: 17,
    summary:
      'To end the conflict of chapter 16, God chooses not another punishment but a quiet sign. Twelve staffs, one for each tribe with the leader’s name on it, are placed in the tent before the ark. The staff of the man God chooses will sprout. The next day Moses goes in and finds that Aaron’s staff has not only sprouted but budded, blossomed and produced almonds. A dead stick had borne fruit. God tells him to put that staff back before the ark as a sign to those who grumble. He answered not with an argument but with life.',
    questions: [
      {
        type: 'choice',
        question: 'What method did God choose?',
        choices: ['Making a staff sprout', 'Another punishment', 'Casting lots', 'Letting the people decide'],
        correctIndex: 0,
        explanation: 'He answered not with an argument but with life.',
      },
      {
        type: 'choice',
        question: 'How many staffs were placed there?',
        choices: ['Twelve', 'Two', 'Seven', 'Twenty-five'],
        correctIndex: 0,
        explanation: 'One for each tribe, with the leader’s name written on it.',
      },
      {
        type: 'choice',
        question: 'What fruit did Aaron’s staff produce?',
        choices: ['Almonds', 'Grapes', 'Figs', 'Olives'],
        correctIndex: 0,
        explanation: 'It sprouted, budded, blossomed and bore fruit.',
      },
      {
        type: 'choice',
        question: 'Where was the staff to be kept?',
        choices: [
          'Before the ark of the covenant law',
          'In Aaron’s house',
          'At the camp entrance',
          'It was destroyed',
        ],
        correctIndex: 0,
        explanation: 'It was to be a sign to those who grumble.',
      },
      {
        type: 'choice',
        question: 'What does the staff stand for?',
        choices: [
          'That God, not people, does the appointing',
          'That Aaron was strong',
          'That the wood was good',
          'Nothing in particular',
        ],
        correctIndex: 0,
        explanation: 'All twelve lay in the same place; only one came alive.',
      },
      {
        type: 'choice',
        question: 'How did the people react to the sign?',
        choices: [
          'They were afraid, saying they would all die',
          'They rejoiced',
          'They argued again',
          'They said nothing',
        ],
        correctIndex: 0,
        explanation: 'Chapter 18 deals with that fear.',
      },
      {
        type: 'choice',
        question: 'How does this chapter follow chapter 16?',
        choices: [
          'It settles the dispute over who was appointed',
          'It gives new rules',
          'It records a war',
          'It is unrelated',
        ],
        correctIndex: 0,
        explanation: 'It did not end in punishment but in a sign.',
      },
    ],
  },
  {
    book: 4,
    chapter: 18,
    summary:
      'When the people are afraid at the end of chapter 17, God answers: responsibility for the sanctuary rests on Aaron, his sons and the Levites. They stand in between so that the people do not come too near and die. Then the portions of the priests and Levites are set. They receive no land; instead, part of what the people bring becomes their living. The Levites receive the tithe — and from that tithe they give a tenth to the priests. Those who receive are also those who give. And one sentence stands out: "I am your share and your inheritance." Instead of land, they were given God.',
    questions: [
      {
        type: 'choice',
        question: 'Who bears responsibility for the sanctuary?',
        choices: ['Aaron, his sons and the Levites', 'All the people', 'The tribal leaders', 'Moses alone'],
        correctIndex: 0,
        explanation: 'They stood in between so the people would not come too near and die.',
      },
      {
        type: 'choice',
        question: 'What did the priests and Levites not receive?',
        choices: ['Land of their own', 'Food', 'Clothing', 'Houses'],
        correctIndex: 0,
        explanation: 'Instead, part of what the people brought became their living.',
      },
      {
        type: 'choice',
        question: 'What did the Levites do with the tithe they received?',
        choices: [
          'They gave a tenth of it to the priests',
          'They kept all of it',
          'They gave it back to the people',
          'They burned it',
        ],
        correctIndex: 0,
        explanation: 'Those who receive are also those who give.',
      },
      {
        type: 'choice',
        question: '"I am your ____ and your inheritance." Fill in the blank.',
        choices: ['Share', 'Shield', 'Strength', 'Light'],
        correctIndex: 0,
        explanation: 'Instead of land, they were given God.',
      },
      {
        type: 'choice',
        question: 'What kind of tenth were the Levites to give?',
        choices: ['The best of it', 'What was left over', 'Anything at all', 'It was not specified'],
        correctIndex: 0,
        explanation: 'Being on the receiving end did not mean giving carelessly.',
      },
      {
        type: 'choice',
        question: 'How does this chapter answer the fear at the end of chapter 17?',
        choices: [
          'By appointing those who will do the drawing near',
          'By simply saying "do not be afraid"',
          'By moving the tabernacle',
          'It does not answer',
        ],
        correctIndex: 0,
        explanation: 'The fear was answered not with words but with an arrangement.',
      },
      {
        type: 'choice',
        question: 'How does this carry into the New Testament?',
        choices: [
          'Jesus standing between God and people',
          'The tithe being abolished',
          'The tribe of Levi becoming kings',
          'It does not carry over',
        ],
        correctIndex: 0,
        explanation: 'Hebrews picks this up and explains Jesus as the great high priest.',
      },
    ],
  },
  {
    book: 4,
    chapter: 19,
    summary:
      'This is the rule for cleansing someone made unclean by touching a dead body. A red heifer without defect is slaughtered and burned outside the camp, and its ashes are mixed with water and kept, to be sprinkled on the unclean person — twice, on the third day and the seventh. One detail is worth noticing: the person who sprinkles that water to cleanse another becomes unclean himself. Making others clean came at a cost. Through forty years in the wilderness people were always dying, so this rule was used often. Hebrews takes up these ashes of the red heifer to explain the blood of Jesus.',
    questions: [
      {
        type: 'choice',
        question: 'Which animal was used in this rule?',
        choices: ['A red heifer without defect', 'A white ram', 'A black goat', 'A young dove'],
        correctIndex: 0,
        explanation: 'It had to be one that had never been under a yoke.',
      },
      {
        type: 'choice',
        question: 'Where was it slaughtered?',
        choices: ['Outside the camp', 'At the entrance to the tent', 'In the Most Holy Place', 'Anywhere'],
        correctIndex: 0,
        explanation: 'Hebrews connects this to Jesus suffering outside the city gate.',
      },
      {
        type: 'choice',
        question: 'When was the water with the ashes sprinkled?',
        choices: ['Twice — on the third day and the seventh', 'Once only', 'Every day', 'It was not set'],
        correctIndex: 0,
        explanation: 'Both sprinklings were needed before he was clean that evening.',
      },
      {
        type: 'choice',
        question: 'What happened to the man who sprinkled the water?',
        choices: ['He became unclean himself', 'He became holier', 'Nothing happened', 'He became a priest'],
        correctIndex: 0,
        explanation: 'Making others clean came at a cost.',
      },
      {
        type: 'choice',
        question: 'Why was this rule used so often?',
        choices: [
          'Because through forty years in the wilderness people were always dying',
          'Because there were many animals',
          'Because there was plenty of water',
          'It was not used often',
        ],
        correctIndex: 0,
        explanation: 'After the verdict in chapter 14, that generation died off in the wilderness.',
      },
      {
        type: 'choice',
        question: 'Which New Testament book uses these ashes to explain Jesus?',
        choices: ['Hebrews', 'Romans', 'Revelation', 'Acts'],
        correctIndex: 0,
        explanation: 'It says that if ashes cleanse the body, the blood of Christ cleanses the conscience.',
      },
      {
        type: 'choice',
        question: 'What made a person unclean in this rule?',
        choices: ['Touching a dead body', 'Eating the wrong food', 'Working too much', 'Travelling far'],
        correctIndex: 0,
        explanation: 'If someone died in a tent, everyone and everything in it became unclean too.',
      },
    ],
  },
  {
    book: 4,
    chapter: 20,
    summary:
      'Sorrow comes on sorrow in this chapter. Miriam dies and is buried at Kadesh. There is no water, and the people quarrel again. God tells Moses to **speak** to the rock. Instead, Moses strikes it twice with his staff — and first says, "Must we bring you water out of this rock?" Water comes, but God tells Moses and Aaron they will not bring the people into the land. Then Edom refuses to let them pass, and Aaron dies on Mount Hor, his garments passing to his son Eleazar. It becomes plain in this chapter that even the leaders will not set foot in the land.',
    questions: [
      {
        type: 'choice',
        question: 'What did God tell Moses to do to the rock?',
        choices: ['Speak to it', 'Strike it', 'Move it', 'Split it'],
        correctIndex: 0,
        explanation: 'Earlier He said to strike it (Exodus 17); this time He said to speak to it.',
      },
      {
        type: 'choice',
        question: 'What did Moses actually do?',
        choices: ['He struck it twice with his staff', 'He spoke to it', 'He did nothing', 'He only prayed'],
        correctIndex: 0,
        explanation: 'He also said, "Must we bring you water out of this rock?"',
      },
      {
        type: 'choice',
        question: 'What came of it?',
        choices: [
          'Moses and Aaron would not bring the people into the land',
          'No water came',
          'The people died',
          'Nothing happened',
        ],
        correctIndex: 0,
        explanation: 'God said, "Because you did not trust me enough to honour me as holy."',
      },
      {
        type: 'choice',
        question: 'Which two people die in this chapter?',
        choices: ['Miriam and Aaron', 'Moses and Aaron', 'Korah and Dathan', 'Nadab and Abihu'],
        correctIndex: 0,
        explanation: 'Miriam died at Kadesh and Aaron on Mount Hor.',
      },
      {
        type: 'choice',
        question: 'Who received Aaron’s garments?',
        choices: ['Eleazar', 'Ithamar', 'Joshua', 'Moses'],
        correctIndex: 0,
        explanation: 'On the mountain the garments were taken off Aaron and put on his son.',
      },
      {
        type: 'choice',
        question: 'Which nation refused to let them pass?',
        choices: ['Edom', 'Moab', 'Midian', 'Amalek'],
        correctIndex: 0,
        explanation: 'They were descendants of Esau — a brother nation — and still refused passage.',
      },
      {
        type: 'choice',
        question: 'What does this chapter make plain?',
        choices: [
          'That even the leaders will not set foot in the land',
          'That water is always available',
          'That Edom was friendly',
          'That the people had changed',
        ],
        correctIndex: 0,
        explanation: 'It is the chapter where a whole generation is passing away.',
      },
    ],
  },
  {
    book: 4,
    chapter: 21,
    summary:
      'The road is long and the people grow impatient. Again they speak against God and against Moses: "We detest this miserable food!" Venomous snakes come among them, and when they are bitten they admit their sin and ask for prayer. God’s remedy is unexpected. A bronze snake is made and put on a pole, and anyone bitten who looks at it lives. He did not take the snakes away; He gave them something to look at. Jesus later takes up this scene to explain Himself: "Just as Moses lifted up the snake in the wilderness, so the Son of Man must be lifted up." The end of the chapter tells of victories over Sihon and Og.',
    questions: [
      {
        type: 'choice',
        question: 'What did the people say as they grumbled?',
        choices: [
          '"We detest this miserable food!"',
          '"The road is good"',
          '"There is plenty of water"',
          'They said nothing',
        ],
        correctIndex: 0,
        explanation: 'They called the manna He gave them every day "miserable."',
      },
      {
        type: 'choice',
        question: 'What remedy did God give?',
        choices: [
          'A bronze snake on a pole for them to look at',
          'Taking all the snakes away',
          'Giving them medicine',
          'Moving the camp',
        ],
        correctIndex: 0,
        explanation: 'He did not take the snakes away; He gave them something to look at.',
      },
      {
        type: 'choice',
        question: 'Who later used this scene to explain Himself?',
        choices: ['Jesus', 'Paul', 'Peter', 'John'],
        correctIndex: 0,
        explanation: 'He said it to Nicodemus in John 3.',
      },
      {
        type: 'choice',
        question: 'What did a bitten person have to do to live?',
        choices: ['Look at the bronze snake', 'Touch it', 'Pay a price', 'Offer a sacrifice'],
        correctIndex: 0,
        explanation: 'It was the simplest thing anyone could do.',
      },
      {
        type: 'choice',
        question: 'What did the people do after being bitten?',
        choices: [
          'They admitted their sin and asked Moses to pray',
          'They left the camp',
          'They blamed Moses',
          'They did nothing',
        ],
        correctIndex: 0,
        explanation: 'Moses prayed again for the people who had been grumbling at him.',
      },
      {
        type: 'choice',
        question: 'Which two kings were defeated at the end of the chapter?',
        choices: [
          'Sihon king of the Amorites and Og king of Bashan',
          'The kings of Edom and Moab',
          'The kings of Egypt and Philistia',
          'None',
        ],
        correctIndex: 0,
        explanation: 'It is the first step in taking the land east of the Jordan.',
      },
      {
        type: 'choice',
        question: 'Is it known what became of the bronze snake?',
        choices: [
          'Hezekiah later broke it up — people had begun burning incense to it',
          'It still stands in the temple',
          'It was left in the wilderness',
          'No one knows',
        ],
        correctIndex: 0,
        explanation:
          'Even something God used becomes an idol when the thing itself is worshipped (2 Kings 18).',
      },
    ],
  },
  {
    book: 4,
    chapter: 22,
    summary:
      'Balak king of Moab is afraid of Israel and sends for a man named Balaam to curse them. Balaam asks God and is told not to go. When Balak sends higher officials and a bigger reward, Balaam asks again. In the end he goes — and something strange happens on the road. His donkey sees the angel of the LORD and stops three times, and Balaam, seeing nothing, beats her. Then God opens the donkey’s mouth. When Balaam’s own eyes are opened he falls face down. A man famous for seeing what lies ahead could not see what stood in front of him, and an animal saw it first.',
    questions: [
      {
        type: 'choice',
        question: 'Why did Balak send for Balaam?',
        choices: ['To curse Israel', 'To guide him on the road', 'To heal the sick', 'To fight for him'],
        correctIndex: 0,
        explanation: 'He was afraid because Israel was so numerous.',
      },
      {
        type: 'choice',
        question: 'Who saw the angel of the LORD first on the road?',
        choices: ['The donkey', 'Balaam', 'Balak', 'The servants'],
        correctIndex: 0,
        explanation: 'The man famous for seeing ahead could not see what was right there.',
      },
      {
        type: 'choice',
        question: 'How many times did the donkey stop?',
        choices: ['Three times', 'Once', 'Twice', 'Seven times'],
        correctIndex: 0,
        explanation: 'Each time, Balaam beat her.',
      },
      {
        type: 'choice',
        question: 'What did God do with the donkey?',
        choices: ['He opened her mouth', 'He shut her eyes', 'He made her run', 'Nothing'],
        correctIndex: 0,
        explanation: 'The donkey speaks — and Balaam answers back. That exchange is the heart of the scene.',
      },
      {
        type: 'choice',
        question: 'What did Balak change when he sent again?',
        choices: ['Higher officials and a bigger reward', 'A shorter road', 'A better donkey', 'Nothing'],
        correctIndex: 0,
        explanation: 'It knows what a bigger price does to a person’s heart.',
      },
      {
        type: 'choice',
        question: 'What was God’s first answer to Balaam?',
        choices: ['Do not go with them', 'Go and curse them', 'Ask for more money', 'He gave no answer'],
        correctIndex: 0,
        explanation: 'Asking again about something already answered is the trouble in this chapter.',
      },
      {
        type: 'choice',
        question: 'What did Balaam do when his eyes were opened?',
        choices: ['He fell face down', 'He ran away', 'He beat the donkey again', 'He did nothing'],
        correctIndex: 0,
        explanation: 'He said, "I have sinned," and even offered to turn back.',
      },
    ],
  },
  {
    book: 4,
    chapter: 23,
    summary:
      'Balak takes Balaam up to a place where he can see Israel. Seven altars are built and sacrifices offered, all so that he can curse them — but what comes out of Balaam’s mouth is blessing, not cursing. Balak moves him to another spot and tries again, with the same result. This chapter holds one of the great verses of the Bible: "God is not human, that he should lie, not a human being, that he should change his mind. Does he speak and then not act? Does he promise and not fulfil?" The chapter shows that a man may pay for words, but no one can buy God’s word.',
    questions: [
      {
        type: 'choice',
        question: 'What came out of Balaam’s mouth?',
        choices: ['Blessing, not cursing', 'Cursing', 'Nothing at all', 'A curse on Balak'],
        correctIndex: 0,
        explanation: 'Balak moved him and tried again, with the same result.',
      },
      {
        type: 'choice',
        question: '"God is not ____, that he should lie." Fill in the blank.',
        choices: ['Human', 'A king', 'A stranger', 'A judge'],
        correctIndex: 0,
        explanation: 'People change what they say; God does not.',
      },
      {
        type: 'choice',
        question: 'How many altars were built?',
        choices: ['Seven', 'Three', 'Twelve', 'One'],
        correctIndex: 0,
        explanation: 'Each time they moved, seven altars were built again.',
      },
      {
        type: 'choice',
        question: 'Why did Balak move Balaam to another place?',
        choices: [
          'Hoping a curse would come from a different spot',
          'Because the view was better',
          'Because the road was long',
          'Because Balaam wanted it',
        ],
        correctIndex: 0,
        explanation: 'The place was never the point; who was doing the speaking was.',
      },
      {
        type: 'choice',
        question: 'What did Balaam say to Balak?',
        choices: [
          '"I must speak only what the LORD puts in my mouth"',
          '"Pay more and I will curse them"',
          '"Let us try again tomorrow"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'A man who came for a fee could not say what the fee had bought.',
      },
      {
        type: 'choice',
        question: 'What does this chapter show?',
        choices: [
          'No one can buy God’s word with a price',
          'That curses always come true',
          'That more altars are better',
          'That Balaam was a fine man',
        ],
        correctIndex: 0,
        explanation: 'Balaam himself is not well remembered later. The word was simply bigger than the man.',
      },
      {
        type: 'choice',
        question: 'What did Balaam say about Israel?',
        choices: [
          'A people who live apart, not considering themselves one of the nations',
          'They will soon be scattered',
          'They will lose in battle',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'God had a stranger’s mouth say that they were a people set apart.',
      },
    ],
  },
  {
    book: 4,
    chapter: 24,
    summary:
      'This time Balaam does not resort to divination; he simply looks out at Israel. The Spirit of God comes on him and a third blessing follows: "How beautiful are your tents, Jacob." Balak is furious, strikes his hands together and tells him to go home — but Balaam has one more thing to say, and it looks further ahead than anything else in the chapter: "A star will come out of Jacob; a sceptre will rise out of Israel." It is read together with the wise men who later followed a star. Out of the mouth of a man hired to curse came words pointing to the Messiah.',
    questions: [
      {
        type: 'choice',
        question: 'What did Balaam say in the third blessing?',
        choices: [
          '"How beautiful are your tents, Jacob"',
          '"Jacob, you will perish"',
          '"Jacob, go back"',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'This time he did not resort to divination; he simply looked.',
      },
      {
        type: 'choice',
        question: '"A ____ will come out of Jacob." Fill in the blank.',
        choices: ['Star', 'Light', 'King', 'Road'],
        correctIndex: 0,
        explanation: 'It is read together with the wise men who later followed a star.',
      },
      {
        type: 'choice',
        question: 'How did Balak react?',
        choices: [
          'He was furious, struck his hands together and told him to go home',
          'He paid him more',
          'He worshipped with him',
          'He said nothing',
        ],
        correctIndex: 0,
        explanation: 'The man he had paid for was saying the exact opposite.',
      },
      {
        type: 'choice',
        question: 'What did Balaam not use this time?',
        choices: ['Divination', 'Altars', 'His donkey', 'Words'],
        correctIndex: 0,
        explanation: 'It says, "When Balaam looked out and saw Israel, the Spirit of God came on him."',
      },
      {
        type: 'choice',
        question: 'Why is the last word of this chapter special?',
        choices: [
          'Words pointing to the Messiah came from a man hired to curse',
          'Because it is the longest',
          'Because Balak liked it',
          'It is not special',
        ],
        correctIndex: 0,
        explanation: 'God uses unexpected mouths.',
      },
      {
        type: 'choice',
        question: 'How many times did Balaam bless Israel?',
        choices: ['Three times, and then one final prophecy', 'Once', 'Seven times', 'He never blessed them'],
        correctIndex: 0,
        explanation: 'The place changed three times; what came out was blessing every time.',
      },
      {
        type: 'choice',
        question: 'How is Balaam remembered in the rest of the Bible?',
        choices: [
          'Not well — he later gave advice that made Israel stumble',
          'As a great prophet',
          'There is no record',
          'He became a king',
        ],
        correctIndex: 0,
        explanation: 'The word was simply bigger than the man (Numbers 31; 2 Peter 2).',
      },
    ],
  },
];
