import type { Grade, Morph, Pos, Word } from '../lib/types.ts';

/**
 * 1차 출시 단어(초3~중3, 기획서 §8).
 *
 * **편집 초안이다.** 2022 개정 교육과정 기본 어휘 목록의 성격(생활·교과 기본
 * 어휘)을 기준으로 골라 학년에 **앱이 배치한 것**이지, 교육과정이 학년별로
 * 지정한 목록이 아니다(§2). 뜻의 순서·예문·형태소 분해는 출시 전에 영어교육
 * 전문가 검수를 받는다(§7).
 *
 * 형태소 표기(`m`):
 *   `re-:다시 + write:쓰다`  —  `-` 로 끝나면 접두사, `-` 로 시작하면 접미사,
 *   `*port:나르다` 처럼 `*` 가 붙으면 홀로 쓰이지 않는 어근, 나머지는 바탕 단어.
 * 분해가 뜻 연결에 도움이 될 때만 적는다. `return`·`report` 처럼 쪼개도 뜻이
 * 안 이어지는 말은 쪼개지 않는다(§7 「뜻 연결이 불분명한 단어는 가족에 편입하지 않는다」).
 *
 * 예문의 `[ ]` 는 빈칸 문항의 자리이며 문장에 맞는 형태 그대로 둔다(`[played]`).
 */

type Extra = { m?: string; c?: string; a?: string[] };
type Row = [en: string, ko: string, pos: Pos, level: 1 | 2 | 3, example: string, exampleKo: string, extra?: Extra];

const E34: Row[] = [
  ['mother', '어머니; 엄마', 'n', 1, 'My [mother] cooks dinner every day.', '우리 어머니는 매일 저녁을 요리하신다.'],
  ['father', '아버지; 아빠', 'n', 1, 'My [father] reads the newspaper.', '우리 아버지는 신문을 읽으신다.'],
  ['sister', '여자 형제; 언니; 누나; 여동생', 'n', 1, 'My [sister] is ten years old.', '내 여동생은 열 살이다.'],
  ['brother', '남자 형제; 형; 오빠; 남동생', 'n', 1, 'I play games with my [brother].', '나는 남동생과 게임을 한다.'],
  ['friend', '친구', 'n', 1, 'Minji is my best [friend].', '민지는 나의 가장 친한 친구다.'],
  ['school', '학교', 'n', 1, 'I go to [school] by bus.', '나는 버스를 타고 학교에 간다.'],
  ['book', '책', 'n', 1, 'This [book] is very funny.', '이 책은 정말 재미있다.'],
  ['desk', '책상', 'n', 1, 'My bag is on the [desk].', '내 가방은 책상 위에 있다.'],
  ['chair', '의자', 'n', 1, 'Please sit on the [chair].', '의자에 앉으세요.'],
  ['window', '창문', 'n', 1, 'Can you open the [window]?', '창문 좀 열어 줄래?'],
  ['door', '문', 'n', 1, 'Close the [door], please.', '문 좀 닫아 주세요.'],
  ['water', '물', 'n', 1, 'I drink [water] after I run.', '나는 달리고 나서 물을 마신다.'],
  ['milk', '우유', 'n', 1, 'I have [milk] for breakfast.', '나는 아침으로 우유를 마신다.'],
  ['apple', '사과', 'n', 1, 'She eats an [apple] every morning.', '그녀는 매일 아침 사과를 먹는다.'],
  ['dog', '개', 'n', 1, 'My [dog] likes to run.', '우리 개는 달리는 것을 좋아한다.'],
  ['cat', '고양이', 'n', 1, 'The [cat] is sleeping on the sofa.', '고양이가 소파에서 자고 있다.'],
  ['bird', '새', 'n', 1, 'A [bird] is singing in the tree.', '새 한 마리가 나무에서 노래하고 있다.'],
  ['fish', '물고기; 생선', 'n', 1, 'There are many [fish] in the river.', '강에 물고기가 많다.'],
  ['tree', '나무', 'n', 1, 'We sat under a big [tree].', '우리는 큰 나무 아래 앉았다.'],
  ['flower', '꽃', 'n', 1, 'This [flower] smells sweet.', '이 꽃은 향기가 달콤하다.'],
  ['sun', '해; 태양', 'n', 1, 'The [sun] is very bright today.', '오늘은 해가 아주 밝다.'],
  ['rain', '비', 'n', 1, 'We stayed home because of the [rain].', '우리는 비 때문에 집에 있었다.'],
  ['snow', '눈', 'n', 1, 'The mountain is white with [snow].', '산이 눈으로 하얗다.'],
  ['ball', '공', 'n', 1, 'Throw the [ball] to me!', '나한테 공을 던져!'],
  ['big', '큰', 'adj', 1, 'An elephant is a [big] animal.', '코끼리는 큰 동물이다.'],
  ['small', '작은', 'adj', 1, 'The mouse is very [small].', '그 생쥐는 아주 작다.'],
  ['happy', '행복한; 기쁜', 'adj', 1, 'I am [happy] to see you.', '너를 만나서 기뻐.'],
  ['sad', '슬픈', 'adj', 1, 'He was [sad] when his team lost.', '그는 자기 팀이 졌을 때 슬펐다.'],
  ['hot', '더운; 뜨거운', 'adj', 1, 'It is very [hot] in summer.', '여름에는 아주 덥다.'],
  ['cold', '추운; 차가운', 'adj', 1, 'The water is too [cold].', '물이 너무 차갑다.'],
  ['eat', '먹다', 'v', 1, 'We [eat] lunch at noon.', '우리는 정오에 점심을 먹는다.'],
  ['drink', '마시다', 'v', 1, 'Cats [drink] a little water.', '고양이는 물을 조금 마신다.'],
  ['run', '달리다', 'v', 1, 'I [ran] to the bus stop.', '나는 버스 정류장까지 달렸다.'],
  ['walk', '걷다', 'v', 1, 'We [walk] to the park together.', '우리는 함께 공원까지 걸어간다.'],
  ['jump', '뛰다; 점프하다', 'v', 1, 'The frog [jumped] into the pond.', '개구리가 연못으로 뛰어들었다.'],
  ['swim', '수영하다', 'v', 1, 'Can you [swim] in the sea?', '너는 바다에서 수영할 수 있니?'],
  ['read', '읽다', 'v', 1, 'I [read] a book before bed.', '나는 자기 전에 책을 읽는다.'],
  ['write', '쓰다', 'v', 1, 'Please [write] your name here.', '여기에 이름을 쓰세요.'],
  ['sing', '노래하다', 'v', 1, 'We [sing] a song in music class.', '우리는 음악 시간에 노래를 부른다.'],
  ['play', '놀다; (운동·악기를) 하다', 'v', 1, 'We [played] soccer after school.', '우리는 방과 후에 축구를 했다.'],
  ['red', '빨간', 'adj', 1, 'She has a [red] umbrella.', '그녀는 빨간 우산을 가지고 있다.'],
  ['blue', '파란', 'adj', 1, 'The sky is [blue] today.', '오늘 하늘이 파랗다.'],
  ['morning', '아침', 'n', 1, 'I get up at seven in the [morning].', '나는 아침 7시에 일어난다.'],
  ['night', '밤', 'n', 1, 'The stars shine at [night].', '별은 밤에 빛난다.'],
  ['day', '날; 하루', 'n', 1, 'It is a sunny [day].', '맑은 날이다.'],
  ['bed', '침대', 'n', 1, 'I go to [bed] at nine.', '나는 9시에 잠자리에 든다.'],
  ['class', '수업; 반', 'n', 1, 'Our English [class] starts at ten.', '우리 영어 수업은 10시에 시작한다.'],
  ['room', '방', 'n', 1, 'My [room] is on the second floor.', '내 방은 2층에 있다.'],
  ['home', '집; 가정', 'n', 1, 'I stay [home] on Sundays.', '나는 일요일에는 집에 있다.'],
  ['work', '일; 일하다', 'n', 1, 'My mom goes to [work] early.', '우리 엄마는 일찍 일하러 가신다.'],
  ['teach', '가르치다', 'v', 2, 'Mr. Kim [teaches] us math.', '김 선생님은 우리에게 수학을 가르치신다.'],
  ['teacher', '선생님; 교사', 'n', 2, 'Our [teacher] is very kind.', '우리 선생님은 아주 친절하시다.', { m: 'teach:가르치다 + -er:~하는 사람' }],
  ['player', '선수; 경기하는 사람', 'n', 2, 'He is a fast soccer [player].', '그는 빠른 축구 선수다.', { m: 'play:(경기를) 하다 + -er:~하는 사람' }],
  ['singer', '가수', 'n', 2, 'My sister wants to be a [singer].', '내 여동생은 가수가 되고 싶어 한다.', { m: 'sing:노래하다 + -er:~하는 사람' }],
  ['dance', '춤추다; 춤', 'v', 2, 'Let’s [dance] to the music.', '음악에 맞춰 춤추자.'],
  ['dancer', '무용수; 춤추는 사람', 'n', 2, 'She is a great [dancer].', '그녀는 훌륭한 무용수다.', { m: 'dance:춤추다 + -er:~하는 사람', c: 'dance 가 e 로 끝나서 -r 만 붙는다.' }],
  ['sunflower', '해바라기', 'n', 2, 'The [sunflower] is taller than me.', '그 해바라기는 나보다 키가 크다.', { m: 'sun:해 + flower:꽃' }],
  ['rainbow', '무지개', 'n', 2, 'Look! There is a [rainbow] in the sky.', '봐! 하늘에 무지개가 있어.', { m: 'rain:비 + bow:활(모양)' }],
  ['snowman', '눈사람', 'n', 2, 'We made a [snowman] in the yard.', '우리는 마당에 눈사람을 만들었다.', { m: 'snow:눈 + man:사람' }],
  ['bedroom', '침실', 'n', 2, 'My [bedroom] has a big window.', '내 침실에는 큰 창문이 있다.', { m: 'bed:침대 + room:방' }],
  ['classroom', '교실', 'n', 2, 'Our [classroom] is on the third floor.', '우리 교실은 3층에 있다.', { m: 'class:수업 + room:방' }],
  ['homework', '숙제', 'n', 2, 'I finished my [homework] after dinner.', '나는 저녁 먹고 숙제를 끝냈다.', { m: 'home:집 + work:일' }],
  ['tall', '키가 큰; 높은', 'adj', 2, 'My brother is very [tall].', '우리 형은 키가 아주 크다.'],
  ['short', '짧은; 키가 작은', 'adj', 2, 'I have [short] hair.', '나는 머리가 짧다.'],
  ['fast', '빠른; 빨리', 'adj', 2, 'A cheetah is a [fast] animal.', '치타는 빠른 동물이다.'],
  ['slow', '느린', 'adj', 2, 'The turtle is [slow] but strong.', '그 거북은 느리지만 튼튼하다.'],
  ['new', '새로운', 'adj', 2, 'I got a [new] bike for my birthday.', '나는 생일 선물로 새 자전거를 받았다.'],
  ['old', '오래된; 나이 든', 'adj', 2, 'This is a very [old] house.', '이것은 아주 오래된 집이다.'],
  ['clean', '깨끗한; 청소하다', 'adj', 2, 'Keep your room [clean].', '방을 깨끗하게 유지해.'],
  ['kitchen', '부엌', 'n', 2, 'Dad is cooking in the [kitchen].', '아빠가 부엌에서 요리하고 계신다.'],
  ['bread', '빵', 'n', 2, 'I ate [bread] and jam.', '나는 빵과 잼을 먹었다.'],
  ['sleep', '자다', 'v', 2, 'Babies [sleep] a lot.', '아기들은 잠을 많이 잔다.'],
  ['today', '오늘', 'n', 2, 'What day is it [today]?', '오늘 무슨 요일이야?'],
  ['tomorrow', '내일', 'n', 2, 'See you [tomorrow]!', '내일 봐!'],
  ['week', '주; 일주일', 'n', 2, 'I swim three times a [week].', '나는 일주일에 세 번 수영한다.'],
  ['color', '색; 색깔', 'n', 2, 'What [color] do you like?', '너는 무슨 색을 좋아하니?', { a: ['colour'] }],
  ['help', '돕다; 도움', 'v', 2, 'Can you [help] me with this box?', '이 상자 옮기는 것 좀 도와줄래?'],
  ['open', '열다', 'v', 2, 'Please [open] your books.', '책을 펴세요.'],
  ['close', '닫다', 'v', 2, 'Don’t forget to [close] the window.', '창문 닫는 것 잊지 마.'],
  ['end', '끝; 끝나다', 'n', 3, 'We clapped at the [end] of the show.', '우리는 공연이 끝날 때 박수를 쳤다.'],
  ['weekend', '주말', 'n', 3, 'What did you do on the [weekend]?', '주말에 뭐 했어?', { m: 'week:주 + end:끝' }],
  ['birthday', '생일', 'n', 3, 'Happy [birthday] to you!', '생일 축하해!', { m: 'birth:태어남 + day:날' }],
  ['breakfast', '아침 식사', 'n', 3, 'I had rice for [breakfast].', '나는 아침으로 밥을 먹었다.'],
  ['lunch', '점심 식사', 'n', 3, 'Let’s have [lunch] together.', '같이 점심 먹자.'],
  ['dinner', '저녁 식사', 'n', 3, 'We have [dinner] at seven.', '우리는 7시에 저녁을 먹는다.'],
  ['hungry', '배고픈', 'adj', 3, 'I am [hungry]. Let’s eat!', '배고파. 먹자!'],
  ['thirsty', '목마른', 'adj', 3, 'After soccer, I was very [thirsty].', '축구를 하고 나서 나는 아주 목말랐다.'],
  ['cloud', '구름', 'n', 3, 'That [cloud] looks like a rabbit.', '저 구름은 토끼처럼 생겼다.'],
  ['cloudy', '흐린; 구름 낀', 'adj', 3, 'It is [cloudy] this afternoon.', '오늘 오후는 흐리다.', { m: 'cloud:구름 + -y:~이 있는' }],
  ['sunny', '맑은; 햇빛이 비치는', 'adj', 3, 'It is [sunny] and warm today.', '오늘은 맑고 따뜻하다.', { m: 'sun:해 + -y:~이 있는', c: 'sun 의 n 이 한 번 더 붙어 sunny 가 된다.' }],
  ['rainy', '비가 오는', 'adj', 3, 'I stay inside on [rainy] days.', '나는 비 오는 날에는 안에 있는다.', { m: 'rain:비 + -y:~이 있는' }],
  ['wind', '바람', 'n', 3, 'The [wind] is blowing hard.', '바람이 세게 불고 있다.'],
  ['windy', '바람이 부는', 'adj', 3, 'It is too [windy] to fly a kite.', '연을 날리기에는 바람이 너무 분다.', { m: 'wind:바람 + -y:~이 있는' }],
  ['favorite', '가장 좋아하는', 'adj', 3, 'Pizza is my [favorite] food.', '피자는 내가 가장 좋아하는 음식이다.', { a: ['favourite'] }],
  ['hobby', '취미', 'n', 3, 'My [hobby] is drawing.', '내 취미는 그림 그리기다.'],
  ['sport', '운동; 스포츠', 'n', 3, 'Soccer is a popular [sport].', '축구는 인기 있는 스포츠다.'],
];

const E56: Row[] = [
  ['science', '과학', 'n', 1, 'We did a fun experiment in [science] class.', '우리는 과학 시간에 재미있는 실험을 했다.'],
  ['history', '역사', 'n', 1, 'I like learning Korean [history].', '나는 한국 역사를 배우는 것을 좋아한다.'],
  ['library', '도서관', 'n', 1, 'I borrowed two books from the [library].', '나는 도서관에서 책 두 권을 빌렸다.'],
  ['museum', '박물관', 'n', 1, 'We visited a science [museum].', '우리는 과학 박물관을 방문했다.'],
  ['hospital', '병원', 'n', 1, 'My grandma is in the [hospital].', '우리 할머니는 병원에 입원해 계신다.'],
  ['weather', '날씨', 'n', 1, 'How is the [weather] today?', '오늘 날씨 어때?'],
  ['season', '계절', 'n', 1, 'Spring is my favorite [season].', '봄은 내가 가장 좋아하는 계절이다.'],
  ['question', '질문; 문제', 'n', 1, 'May I ask a [question]?', '질문 하나 해도 될까요?'],
  ['answer', '대답; 답; 대답하다', 'n', 1, 'I know the [answer]!', '나 답 알아!'],
  ['problem', '문제', 'n', 1, 'We solved the [problem] together.', '우리는 함께 그 문제를 풀었다.'],
  ['idea', '생각; 아이디어', 'n', 1, 'That’s a great [idea]!', '그거 좋은 생각이다!'],
  ['plan', '계획; 계획하다', 'n', 1, 'What is your [plan] for the vacation?', '방학 계획이 뭐야?'],
  ['story', '이야기', 'n', 1, 'Grandpa told us a funny [story].', '할아버지가 우리에게 재미있는 이야기를 해 주셨다.'],
  ['future', '미래', 'n', 1, 'I want to be a doctor in the [future].', '나는 미래에 의사가 되고 싶다.'],
  ['dream', '꿈; 꿈꾸다', 'n', 1, 'My [dream] is to travel the world.', '내 꿈은 세계를 여행하는 것이다.'],
  ['visit', '방문하다', 'v', 1, 'We [visited] our uncle in Busan.', '우리는 부산에 계신 삼촌을 방문했다.'],
  ['use', '사용하다', 'v', 1, 'Can I [use] your eraser?', '네 지우개 써도 돼?'],
  ['care', '돌봄; 주의; 신경 쓰다', 'n', 1, 'Plants need a lot of [care].', '식물은 많은 돌봄이 필요하다.'],
  ['kind', '친절한', 'adj', 1, 'It is [kind] of you to help me.', '나를 도와주다니 친절하구나.', { c: '「종류」라는 뜻도 있다(a kind of fruit = 과일의 한 종류). 문장 속 자리를 보고 가린다.' }],
  ['lucky', '운이 좋은', 'adj', 1, 'I was [lucky] to find my wallet.', '지갑을 찾다니 나는 운이 좋았다.'],
  ['famous', '유명한', 'adj', 1, 'This park is [famous] for its flowers.', '이 공원은 꽃으로 유명하다.'],
  ['easy', '쉬운', 'adj', 1, 'The test was [easy].', '시험이 쉬웠다.'],
  ['difficult', '어려운', 'adj', 1, 'This puzzle is [difficult].', '이 퍼즐은 어렵다.'],
  ['important', '중요한', 'adj', 1, 'Sleep is [important] for your health.', '잠은 건강에 중요하다.'],
  ['different', '다른', 'adj', 1, 'We have [different] ideas.', '우리는 생각이 다르다.'],
  ['together', '함께', 'adv', 1, 'Let’s clean the room [together].', '함께 방을 청소하자.'],
  ['always', '항상', 'adv', 1, 'She [always] smiles.', '그녀는 항상 웃는다.'],
  ['usually', '보통; 대개', 'adv', 1, 'I [usually] walk to school.', '나는 보통 학교에 걸어간다.'],
  ['sometimes', '가끔; 때때로', 'adv', 1, 'I [sometimes] eat noodles for lunch.', '나는 가끔 점심으로 국수를 먹는다.'],
  ['never', '결코 ~않다; 한 번도 ~않다', 'adv', 1, 'I have [never] seen snow.', '나는 눈을 한 번도 본 적이 없다.'],
  ['money', '돈', 'n', 1, 'I saved [money] to buy a gift.', '나는 선물을 사려고 돈을 모았다.'],
  ['save', '저축하다; 구하다; 아끼다', 'v', 1, 'Turn off the light to [save] energy.', '에너지를 아끼기 위해 불을 꺼라.', { c: '「구하다(save a life)」와 「저축하다(save money)」가 한 단어다. 뒤에 오는 말로 가린다.' }],
  ['spend', '(돈·시간을) 쓰다', 'v', 1, 'I [spent] all my money on snacks.', '나는 간식에 돈을 다 썼다.'],
  ['win', '이기다', 'v', 1, 'Our team [won] the game.', '우리 팀이 경기에서 이겼다.'],
  ['lose', '지다; 잃어버리다', 'v', 1, 'Don’t [lose] your key.', '열쇠 잃어버리지 마.'],
  ['team', '팀', 'n', 1, 'Our [team] practices every Friday.', '우리 팀은 매주 금요일에 연습한다.'],
  ['exercise', '운동; 운동하다', 'n', 1, 'Regular [exercise] keeps you healthy.', '규칙적인 운동은 너를 건강하게 해 준다.'],
  ['art', '미술; 예술', 'n', 1, 'I painted a picture in [art] class.', '나는 미술 시간에 그림을 그렸다.'],
  ['like', '좋아하다', 'v', 1, 'I [like] rainy days.', '나는 비 오는 날을 좋아한다.'],
  ['agree', '동의하다', 'v', 1, 'I [agree] with you.', '나는 네 말에 동의해.'],
  ['visitor', '방문객', 'n', 2, 'The museum had many [visitors] today.', '오늘 박물관에 방문객이 많았다.', { m: 'visit:방문하다 + -or:~하는 사람' }],
  ['useful', '유용한; 쓸모 있는', 'adj', 2, 'This app is very [useful].', '이 앱은 아주 유용하다.', { m: 'use:쓰다 + -ful:~이 가득한' }],
  ['useless', '쓸모없는', 'adj', 2, 'A broken pencil is [useless].', '부러진 연필은 쓸모가 없다.', { m: 'use:쓰다 + -less:~이 없는' }],
  ['careful', '조심하는; 주의 깊은', 'adj', 2, 'Be [careful] on the stairs.', '계단에서 조심해.', { m: 'care:주의 + -ful:~이 가득한' }],
  ['careless', '부주의한', 'adj', 2, 'I made a [careless] mistake.', '나는 부주의한 실수를 했다.', { m: 'care:주의 + -less:~이 없는' }],
  ['helpful', '도움이 되는', 'adj', 2, 'Thank you. That was very [helpful].', '고마워. 정말 도움이 됐어.', { m: 'help:도움 + -ful:~이 가득한' }],
  ['unkind', '불친절한', 'adj', 2, 'It was [unkind] to laugh at him.', '그를 비웃은 것은 불친절한 일이었다.', { m: 'un-:~이 아닌 + kind:친절한' }],
  ['unhappy', '불행한; 기분이 안 좋은', 'adj', 2, 'He looked [unhappy] this morning.', '그는 오늘 아침 기분이 안 좋아 보였다.', { m: 'un-:~이 아닌 + happy:행복한' }],
  ['unlucky', '운이 나쁜', 'adj', 2, 'I was [unlucky] to miss the bus.', '버스를 놓치다니 나는 운이 나빴다.', { m: 'un-:~이 아닌 + lucky:운이 좋은' }],
  ['rewrite', '다시 쓰다', 'v', 2, 'Please [rewrite] this sentence.', '이 문장을 다시 쓰세요.', { m: 're-:다시 + write:쓰다' }],
  ['reuse', '다시 쓰다; 재사용하다', 'v', 2, 'We can [reuse] these bottles.', '우리는 이 병들을 다시 쓸 수 있다.', { m: 're-:다시 + use:쓰다' }],
  ['cycle', '순환; 자전거', 'n', 2, 'We learned about the water [cycle].', '우리는 물의 순환에 대해 배웠다.'],
  ['recycle', '재활용하다', 'v', 2, 'We [recycle] paper and cans.', '우리는 종이와 캔을 재활용한다.', { m: 're-:다시 + cycle:순환' }],
  ['dislike', '싫어하다', 'v', 2, 'I [dislike] loud noises.', '나는 시끄러운 소리를 싫어한다.', { m: 'dis-:반대 + like:좋아하다' }],
  ['disagree', '동의하지 않다', 'v', 2, 'I [disagree] with that idea.', '나는 그 생각에 동의하지 않는다.', { m: 'dis-:반대 + agree:동의하다' }],
  ['health', '건강', 'n', 2, 'Vegetables are good for your [health].', '채소는 건강에 좋다.'],
  ['healthy', '건강한; 건강에 좋은', 'adj', 2, 'Eat [healthy] food.', '건강에 좋은 음식을 먹어라.', { m: 'health:건강 + -y:~한' }],
  ['quick', '빠른', 'adj', 2, 'Let’s have a [quick] lunch.', '점심을 빨리 먹자.'],
  ['quickly', '빨리', 'adv', 2, 'He finished his work [quickly].', '그는 일을 빨리 끝냈다.', { m: 'quick:빠른 + -ly:~하게' }],
  ['slowly', '천천히', 'adv', 2, 'Please speak [slowly].', '천천히 말해 주세요.', { m: 'slow:느린 + -ly:~하게' }],
  ['final', '마지막의', 'adj', 2, 'This is the [final] game.', '이것이 마지막 경기다.'],
  ['finally', '마침내; 마지막으로', 'adv', 2, 'We [finally] reached the top.', '우리는 마침내 정상에 도착했다.', { m: 'final:마지막의 + -ly:~하게' }],
  ['remember', '기억하다', 'v', 2, 'Do you [remember] my name?', '내 이름 기억해?'],
  ['forget', '잊다', 'v', 2, 'I [forgot] my umbrella.', '나는 우산을 잊어버렸다.'],
  ['decide', '결정하다', 'v', 2, 'I [decided] to join the club.', '나는 그 동아리에 들어가기로 결정했다.'],
  ['practice', '연습하다; 연습', 'v', 2, 'I [practice] the piano every day.', '나는 매일 피아노를 연습한다.'],
  ['explain', '설명하다', 'v', 2, 'Can you [explain] the rules?', '규칙을 설명해 줄 수 있어?'],
  ['prepare', '준비하다', 'v', 2, 'We [prepared] food for the party.', '우리는 파티 음식을 준비했다.'],
  ['collect', '모으다; 수집하다', 'v', 2, 'He [collects] stamps.', '그는 우표를 모은다.'],
  ['borrow', '빌리다', 'v', 2, 'Can I [borrow] your pen?', '네 펜 좀 빌려도 돼?'],
  ['return', '돌려주다; 돌아오다', 'v', 2, 'Please [return] the book by Friday.', '금요일까지 책을 반납해 주세요.', { c: 're- 로 시작하지만 「다시 + turn」으로 풀면 뜻이 잘 안 이어진다. 통째로 익힌다.' }],
  ['environment', '환경', 'n', 3, 'We must protect the [environment].', '우리는 환경을 보호해야 한다.'],
  ['energy', '에너지; 힘', 'n', 3, 'Solar [energy] comes from the sun.', '태양 에너지는 해에서 온다.'],
  ['planet', '행성', 'n', 3, 'Mars is a red [planet].', '화성은 붉은 행성이다.'],
  ['earth', '지구; 땅', 'n', 3, 'The [earth] goes around the sun.', '지구는 태양 주위를 돈다.'],
  ['culture', '문화', 'n', 3, 'I want to learn about Japanese [culture].', '나는 일본 문화에 대해 배우고 싶다.'],
  ['festival', '축제', 'n', 3, 'The town has a music [festival] in May.', '그 마을은 5월에 음악 축제가 열린다.'],
  ['market', '시장', 'n', 3, 'Mom bought fruit at the [market].', '엄마는 시장에서 과일을 사셨다.'],
  ['price', '가격', 'n', 3, 'The [price] of this bag is too high.', '이 가방의 가격은 너무 비싸다.'],
  ['medicine', '약', 'n', 3, 'Take this [medicine] after meals.', '식후에 이 약을 드세요.'],
  ['hope', '희망; 바라다', 'n', 3, 'Never give up [hope].', '희망을 절대 포기하지 마.'],
  ['hopeful', '희망에 찬', 'adj', 3, 'We are [hopeful] about the future.', '우리는 미래에 대해 희망에 차 있다.', { m: 'hope:희망 + -ful:~이 가득한' }],
  ['hopeless', '가망 없는; 절망적인', 'adj', 3, 'The situation looked [hopeless].', '상황이 가망 없어 보였다.', { m: 'hope:희망 + -less:~이 없는' }],
  ['build', '짓다; 세우다', 'v', 3, 'They [built] a new bridge.', '그들은 새 다리를 지었다.'],
  ['builder', '건축업자; 짓는 사람', 'n', 3, 'The [builder] finished the house in a year.', '건축업자는 1년 만에 집을 완성했다.', { m: 'build:짓다 + -er:~하는 사람' }],
  ['invent', '발명하다', 'v', 3, 'Who [invented] the telephone?', '누가 전화기를 발명했니?'],
  ['inventor', '발명가', 'n', 3, 'Edison was a great [inventor].', '에디슨은 위대한 발명가였다.', { m: 'invent:발명하다 + -or:~하는 사람' }],
  ['protect', '보호하다; 지키다', 'v', 3, 'Sunscreen [protects] your skin.', '선크림은 피부를 보호한다.'],
  ['beauty', '아름다움', 'n', 3, 'We enjoyed the [beauty] of nature.', '우리는 자연의 아름다움을 즐겼다.'],
  ['beautiful', '아름다운', 'adj', 3, 'What a [beautiful] garden!', '정말 아름다운 정원이구나!', { m: 'beauty:아름다움 + -ful:~이 가득한', c: 'beauty 의 y 가 i 로 바뀐다(beauti-ful).' }],
  ['enough', '충분한; 충분히', 'adj', 3, 'We have [enough] time.', '우리는 시간이 충분하다.'],
  ['sick', '아픈', 'adj', 3, 'I stayed home because I was [sick].', '나는 아파서 집에 있었다.'],
  ['safe', '안전한', 'adj', 3, 'This area is [safe] for children.', '이 지역은 아이들에게 안전하다.'],
  ['unsafe', '안전하지 않은', 'adj', 3, 'It is [unsafe] to swim here.', '여기서 수영하는 것은 안전하지 않다.', { m: 'un-:~이 아닌 + safe:안전한' }],
  ['danger', '위험', 'n', 3, 'The sign says “[Danger]!”', '표지판에 「위험!」이라고 쓰여 있다.'],
  ['dangerous', '위험한', 'adj', 3, 'Crossing here is [dangerous].', '여기서 길을 건너는 것은 위험하다.', { m: 'danger:위험 + -ous:~이 많은' }],
];

const M13: Row[] = [
  ['achieve', '이루다; 성취하다', 'v', 1, 'She worked hard to [achieve] her goal.', '그녀는 목표를 이루기 위해 열심히 노력했다.'],
  ['achievement', '성취; 업적', 'n', 1, 'Winning the prize was a great [achievement].', '그 상을 받은 것은 대단한 성취였다.', { m: 'achieve:이루다 + -ment:~하는 것(명사)' }],
  ['develop', '발달시키다; 개발하다', 'v', 1, 'Reading helps [develop] your mind.', '독서는 생각을 발달시키는 데 도움이 된다.'],
  ['development', '발달; 개발', 'n', 1, 'The [development] of the new game took two years.', '새 게임의 개발은 2년이 걸렸다.', { m: 'develop:개발하다 + -ment:~하는 것(명사)' }],
  ['improve', '향상시키다; 나아지다', 'v', 1, 'My English has [improved] a lot.', '내 영어 실력이 많이 늘었다.'],
  ['improvement', '향상; 개선', 'n', 1, 'There is a big [improvement] in your writing.', '네 글쓰기에 큰 향상이 있다.', { m: 'improve:향상시키다 + -ment:~하는 것(명사)' }],
  ['create', '창조하다; 만들어 내다', 'v', 1, 'The students [created] a short film.', '학생들은 짧은 영화를 만들었다.'],
  ['creative', '창의적인', 'adj', 1, 'She has many [creative] ideas.', '그녀는 창의적인 생각을 많이 가지고 있다.', { m: 'create:만들어 내다 + -ive:~하는 성질의', c: 'create 의 끝 e 가 빠진다(creat-ive).' }],
  ['inform', '알리다', 'v', 1, 'Please [inform] us of any changes.', '바뀌는 것이 있으면 저희에게 알려 주세요.'],
  ['information', '정보', 'n', 1, 'You can find more [information] online.', '온라인에서 더 많은 정보를 찾을 수 있다.', { m: 'inform:알리다 + -ation:~하는 것(명사)' }],
  ['education', '교육', 'n', 1, '[Education] is important for everyone.', '교육은 모두에게 중요하다.'],
  ['communicate', '의사소통하다', 'v', 1, 'We [communicate] by email.', '우리는 이메일로 의사소통한다.'],
  ['communication', '의사소통', 'n', 1, 'Good [communication] builds trust.', '좋은 의사소통은 신뢰를 쌓는다.', { m: 'communicate:의사소통하다 + -ion:~하는 것(명사)', c: 'communicate 의 끝 e 가 빠진다.' }],
  ['invite', '초대하다', 'v', 1, 'She [invited] me to her party.', '그녀는 나를 자기 파티에 초대했다.'],
  ['invitation', '초대; 초대장', 'n', 1, 'Thank you for the [invitation].', '초대해 주셔서 감사합니다.', { m: 'invite:초대하다 + -ation:~하는 것(명사)', c: 'invite 의 끝 e 가 빠진다(invit-ation).' }],
  ['possible', '가능한', 'adj', 1, 'Is it [possible] to finish today?', '오늘 끝내는 것이 가능한가요?'],
  ['impossible', '불가능한', 'adj', 1, 'Nothing is [impossible].', '불가능한 것은 없다.', { m: 'im-:~이 아닌 + possible:가능한', c: 'in- 이 p·b·m 앞에서는 im- 이 된다.' }],
  ['polite', '공손한; 예의 바른', 'adj', 1, 'It is [polite] to say thank you.', '고맙다고 말하는 것이 예의 바르다.'],
  ['impolite', '무례한', 'adj', 1, 'It is [impolite] to talk with your mouth full.', '입에 음식을 넣은 채 말하는 것은 무례하다.', { m: 'im-:~이 아닌 + polite:공손한' }],
  ['correct', '옳은; 바로잡다', 'adj', 1, 'Your answer is [correct].', '네 답이 맞다.'],
  ['incorrect', '틀린; 부정확한', 'adj', 1, 'This information is [incorrect].', '이 정보는 틀렸다.', { m: 'in-:~이 아닌 + correct:옳은' }],
  ['depend', '의존하다; ~에 달려 있다', 'v', 1, 'It [depends] on the weather.', '그건 날씨에 달려 있다.'],
  ['independent', '독립적인; 자립한', 'adj', 1, 'He became [independent] at twenty.', '그는 스무 살에 독립했다.', { m: 'in-:~이 아닌 + depend:의존하다 + -ent:~한' }],
  ['comfort', '편안함; 위로하다', 'n', 1, 'Music gives me [comfort].', '음악은 나에게 위로가 된다.'],
  ['comfortable', '편안한', 'adj', 1, 'This chair is very [comfortable].', '이 의자는 아주 편안하다.', { m: 'comfort:편안함 + -able:~할 수 있는' }],
  ['kindness', '친절', 'n', 1, 'Thank you for your [kindness].', '친절에 감사드립니다.', { m: 'kind:친절한 + -ness:~함(명사)' }],
  ['happiness', '행복', 'n', 1, 'Money can’t buy [happiness].', '돈으로 행복을 살 수는 없다.', { m: 'happy:행복한 + -ness:~함(명사)', c: 'happy 의 y 가 i 로 바뀐다(happi-ness).' }],
  ['friendship', '우정', 'n', 1, 'Our [friendship] is very special.', '우리의 우정은 아주 특별하다.', { m: 'friend:친구 + -ship:관계·상태' }],
  ['child', '아이; 어린이', 'n', 1, 'Every [child] needs love.', '모든 아이에게는 사랑이 필요하다.'],
  ['childhood', '어린 시절', 'n', 1, 'I spent my [childhood] in Jeju.', '나는 어린 시절을 제주에서 보냈다.', { m: 'child:아이 + -hood:~인 시기·상태' }],
  ['neighbor', '이웃', 'n', 1, 'Our [neighbor] has a cute dog.', '우리 이웃은 귀여운 개를 키운다.', { a: ['neighbour'] }],
  ['neighborhood', '동네; 이웃', 'n', 1, 'There is a park in my [neighborhood].', '우리 동네에는 공원이 있다.', { m: 'neighbor:이웃 + -hood:~인 무리·상태', a: ['neighbourhood'] }],
  ['govern', '다스리다; 통치하다', 'v', 2, 'The king [governed] the country for 30 years.', '그 왕은 30년 동안 나라를 다스렸다.'],
  ['government', '정부', 'n', 2, 'The [government] built a new school.', '정부는 새 학교를 지었다.', { m: 'govern:다스리다 + -ment:~하는 것(명사)' }],
  ['move', '움직이다; 이사하다', 'v', 2, 'We [moved] to Seoul last year.', '우리는 작년에 서울로 이사했다.'],
  ['movement', '움직임; 운동', 'n', 2, 'The dancer’s [movement] was beautiful.', '그 무용수의 움직임은 아름다웠다.', { m: 'move:움직이다 + -ment:~하는 것(명사)' }],
  ['predict', '예측하다', 'v', 2, 'No one can [predict] the future.', '아무도 미래를 예측할 수 없다.', { m: 'pre-:미리 + *dict:말하다' }],
  ['view', '경치; 관점; 보다', 'n', 2, 'The [view] from the top is amazing.', '꼭대기에서 보는 경치가 놀랍다.'],
  ['preview', '미리 보기; 예습하다', 'n', 2, 'We watched a [preview] of the movie.', '우리는 그 영화의 예고편을 봤다.', { m: 'pre-:미리 + view:보다' }],
  ['transport', '수송하다; 교통수단', 'v', 2, 'Trucks [transport] goods across the country.', '트럭은 전국으로 물건을 수송한다.', { m: 'trans-:가로질러 + *port:나르다' }],
  ['import', '수입하다; 수입', 'v', 2, 'Korea [imports] a lot of oil.', '한국은 석유를 많이 수입한다.', { m: 'im-:안으로 + *port:나르다', c: '여기서 im- 은 「~이 아닌」이 아니라 「안으로」다. 같은 모양의 다른 접두사.' }],
  ['export', '수출하다; 수출', 'v', 2, 'Korea [exports] cars to many countries.', '한국은 여러 나라에 자동차를 수출한다.', { m: 'ex-:밖으로 + *port:나르다' }],
  ['portable', '휴대용의; 들고 다닐 수 있는', 'adj', 2, 'I bought a [portable] speaker.', '나는 휴대용 스피커를 샀다.', { m: '*port:나르다 + -able:~할 수 있는' }],
  ['nation', '국가; 국민', 'n', 2, 'The whole [nation] watched the game.', '온 국민이 그 경기를 보았다.'],
  ['national', '국가의; 국립의', 'adj', 2, 'We visited the [national] museum.', '우리는 국립 박물관을 방문했다.', { m: 'nation:국가 + -al:~의' }],
  ['international', '국제적인', 'adj', 2, 'English is an [international] language.', '영어는 국제적인 언어다.', { m: 'inter-:사이의 + nation:국가 + -al:~의' }],
  ['nature', '자연', 'n', 2, 'I love walking in [nature].', '나는 자연 속을 걷는 것을 좋아한다.'],
  ['natural', '자연의; 자연스러운', 'adj', 2, 'Earthquakes are [natural] disasters.', '지진은 자연재해다.', { m: 'nature:자연 + -al:~의', c: 'nature 의 끝 e 가 빠진다(natur-al).' }],
  ['experience', '경험; 경험하다', 'n', 2, 'Traveling alone was a great [experience].', '혼자 여행한 것은 멋진 경험이었다.'],
  ['experiment', '실험', 'n', 2, 'We did an [experiment] with magnets.', '우리는 자석으로 실험을 했다.'],
  ['society', '사회', 'n', 2, 'We live in a diverse [society].', '우리는 다양한 사회에 살고 있다.'],
  ['social', '사회의; 사교적인', 'adj', 2, 'Poverty is a serious [social] problem.', '빈곤은 심각한 사회 문제다.'],
  ['opinion', '의견', 'n', 2, 'In my [opinion], this plan is better.', '내 의견으로는 이 계획이 더 낫다.'],
  ['reason', '이유', 'n', 2, 'Tell me the [reason] you were late.', '늦은 이유를 말해 줘.'],
  ['result', '결과', 'n', 2, 'The [result] of the test surprised me.', '시험 결과가 나를 놀라게 했다.'],
  ['effect', '영향; 효과', 'n', 2, 'Music has a calming [effect].', '음악은 마음을 차분하게 하는 효과가 있다.'],
  ['cause', '원인; 일으키다', 'n', 2, 'What was the [cause] of the fire?', '화재의 원인은 무엇이었나요?'],
  ['solve', '풀다; 해결하다', 'v', 2, 'Can you [solve] this problem?', '이 문제를 풀 수 있니?'],
  ['solution', '해결책; 해법', 'n', 2, 'We need a quick [solution].', '우리는 빠른 해결책이 필요하다.'],
  ['necessary', '필요한', 'adj', 2, 'Water is [necessary] for life.', '물은 생명에 필요하다.'],
  ['compare', '비교하다', 'v', 2, '[Compare] the two pictures.', '두 그림을 비교해 보세요.'],
  ['support', '지지하다; 지원하다', 'v', 2, 'My parents [support] my dream.', '부모님은 내 꿈을 지지해 주신다.'],
  ['suggest', '제안하다', 'v', 2, 'I [suggest] that we leave early.', '나는 우리가 일찍 떠날 것을 제안한다.'],
  ['consider', '고려하다; 여기다', 'v', 2, 'Please [consider] my idea.', '제 생각을 고려해 주세요.'],
  ['include', '포함하다', 'v', 2, 'The price [includes] breakfast.', '가격에 아침 식사가 포함되어 있다.'],
  ['cover', '덮다; 덮개', 'v', 2, 'Snow [covered] the whole city.', '눈이 도시 전체를 덮었다.'],
  ['discover', '발견하다', 'v', 2, 'Scientists [discovered] a new star.', '과학자들이 새 별을 발견했다.', { m: 'dis-:벗기다(반대) + cover:덮다', c: '「덮개를 벗겨 드러내다」에서 「발견하다」로 뜻이 옮겨 갔다. 어근만으로 뜻이 바로 나오지는 않는다.' }],
  ['appear', '나타나다', 'v', 2, 'A rainbow [appeared] after the rain.', '비가 그친 뒤 무지개가 나타났다.'],
  ['disappear', '사라지다', 'v', 2, 'The sun [disappeared] behind the clouds.', '해가 구름 뒤로 사라졌다.', { m: 'dis-:반대 + appear:나타나다' }],
  ['understand', '이해하다', 'v', 2, 'I don’t [understand] this sentence.', '나는 이 문장을 이해하지 못하겠다.'],
  ['misunderstand', '오해하다', 'v', 2, 'Please don’t [misunderstand] me.', '제 말을 오해하지 마세요.', { m: 'mis-:잘못 + understand:이해하다' }],
  ['believe', '믿다', 'v', 2, 'I [believe] in you.', '나는 너를 믿어.'],
  ['unbelievable', '믿기 어려운; 놀라운', 'adj', 2, 'The ending was [unbelievable].', '결말이 믿기 어려울 정도였다.', { m: 'un-:~이 아닌 + believe:믿다 + -able:~할 수 있는', c: 'believe 의 끝 e 가 빠진다.' }],
  ['volunteer', '자원봉사자; 자원하다', 'n', 3, 'She works as a [volunteer] at the library.', '그녀는 도서관에서 자원봉사자로 일한다.'],
  ['donate', '기부하다', 'v', 3, 'We [donated] books to the school.', '우리는 학교에 책을 기부했다.'],
  ['donation', '기부; 기부금', 'n', 3, 'Thank you for your kind [donation].', '따뜻한 기부에 감사드립니다.', { m: 'donate:기부하다 + -ion:~하는 것(명사)', c: 'donate 의 끝 e 가 빠진다.' }],
  ['respect', '존경하다; 존중', 'v', 3, 'I [respect] my grandparents.', '나는 조부모님을 존경한다.'],
  ['responsible', '책임 있는; 책임감 있는', 'adj', 3, 'You are [responsible] for your own actions.', '너는 네 행동에 책임이 있다.'],
  ['attitude', '태도', 'n', 3, 'She has a positive [attitude].', '그녀는 긍정적인 태도를 가지고 있다.'],
  ['behavior', '행동', 'n', 3, 'His [behavior] in class has improved.', '수업 중 그의 행동이 나아졌다.', { a: ['behaviour'] }],
  ['emotion', '감정', 'n', 3, 'It’s okay to show your [emotions].', '감정을 드러내도 괜찮다.'],
  ['anxious', '불안한; 걱정하는', 'adj', 3, 'I felt [anxious] before the exam.', '나는 시험 전에 불안했다.'],
  ['confident', '자신 있는', 'adj', 3, 'She felt [confident] about her speech.', '그녀는 자기 연설에 자신이 있었다.'],
  ['patient', '참을성 있는; 환자', 'adj', 3, 'Be [patient]. The bus will come soon.', '참고 기다려. 버스가 곧 올 거야.', { c: '명사로는 「환자」다(The doctor saw ten patients). 문장 속 자리로 가린다.' }],
  ['present', '선물; 현재의; 참석한', 'n', 3, 'I got a [present] from my aunt.', '나는 이모에게서 선물을 받았다.', { c: '동사 「발표하다·주다」는 강세가 뒤로 간다(pre-SENT). 뜻마다 쓰임을 따로 익힌다.' }],
  ['habit', '습관', 'n', 3, 'Reading every day is a good [habit].', '매일 책을 읽는 것은 좋은 습관이다.'],
  ['advantage', '이점; 유리한 점', 'n', 3, 'Speaking two languages is a big [advantage].', '두 언어를 하는 것은 큰 이점이다.'],
  ['disadvantage', '불리한 점; 단점', 'n', 3, 'One [disadvantage] of the city is the noise.', '도시의 단점 하나는 소음이다.', { m: 'dis-:반대 + advantage:이점' }],
  ['graduate', '졸업하다', 'v', 3, 'My sister [graduated] from high school.', '우리 언니는 고등학교를 졸업했다.'],
  ['journey', '여행; 여정', 'n', 3, 'It was a long [journey] home.', '집으로 가는 긴 여정이었다.'],
  ['challenge', '도전; 도전하다', 'n', 3, 'Learning a new language is a [challenge].', '새 언어를 배우는 것은 도전이다.'],
  ['audience', '청중; 관객', 'n', 3, 'The [audience] clapped loudly.', '관객들이 크게 박수를 쳤다.'],
  ['scientist', '과학자', 'n', 3, 'I want to be a [scientist].', '나는 과학자가 되고 싶다.', { m: 'science:과학 + -ist:~을 하는 사람', c: 'science 의 끝 -ce 가 -t 로 바뀐다(scien-t-ist).' }],
  ['artist', '예술가; 화가', 'n', 3, 'The [artist] painted the wall.', '그 화가가 벽에 그림을 그렸다.', { m: 'art:예술 + -ist:~을 하는 사람' }],
  ['tour', '관광; 여행', 'n', 3, 'We took a bus [tour] of the city.', '우리는 버스로 시내 관광을 했다.'],
  ['tourist', '관광객', 'n', 3, 'Many [tourists] visit Gyeongju.', '많은 관광객이 경주를 방문한다.', { m: 'tour:관광 + -ist:~을 하는 사람' }],
  ['biology', '생물학', 'n', 3, 'I learned about cells in [biology].', '나는 생물학에서 세포에 대해 배웠다.', { m: 'bio-:생명 + -logy:학문' }],
  ['telephone', '전화; 전화기', 'n', 3, 'The [telephone] is ringing.', '전화가 울리고 있다.', { m: 'tele-:멀리 + *phone:소리' }],
  ['microphone', '마이크', 'n', 3, 'Please speak into the [microphone].', '마이크에 대고 말씀해 주세요.', { m: 'micro-:작은 + *phone:소리', c: '「작은 소리를 크게 하는 기구」 — micro- 가 크기가 아니라 받는 소리를 가리킨다.' }],
  ['telescope', '망원경', 'n', 3, 'We looked at the moon through a [telescope].', '우리는 망원경으로 달을 보았다.', { m: 'tele-:멀리 + *scope:보는 기구' }],
  ['microscope', '현미경', 'n', 3, 'We saw tiny cells under the [microscope].', '우리는 현미경으로 아주 작은 세포를 보았다.', { m: 'micro-:작은 + *scope:보는 기구' }],
  ['visible', '보이는', 'adj', 3, 'The stars are [visible] tonight.', '오늘 밤에는 별이 보인다.', { m: '*vis:보다 + -ible:~할 수 있는' }],
  ['invisible', '보이지 않는', 'adj', 3, 'Air is [invisible].', '공기는 보이지 않는다.', { m: 'in-:~이 아닌 + *vis:보다 + -ible:~할 수 있는' }],
];

function parseMorph(src: string): Morph[] {
  return src.split(' + ').map((chunk) => {
    const [raw, meaning] = chunk.split(':');
    const part = raw.replace(/^\*/, '');
    const kind = raw.startsWith('*') ? 'root' : part.endsWith('-') ? 'prefix' : part.startsWith('-') ? 'suffix' : 'base';
    return { part, meaning, kind };
  });
}

function toWords(rows: Row[], grade: Grade): Word[] {
  return rows.map(([en, ko, pos, level, example, exampleKo, x]) => {
    const w: Word = { id: en, en, ko, pos, grade, level, example, exampleKo };
    if (x?.m) w.morph = parseMorph(x.m);
    if (x?.c) w.caution = x.c;
    if (x?.a) w.accept = x.a;
    return w;
  });
}

const ALL = [...toWords(E34, 'e34'), ...toWords(E56, 'e56'), ...toWords(M13, 'm13')];
const IDS = new Set(ALL.map((w) => w.id));
// 바탕 단어가 앱에 있으면 그것을 먼저 떠올리게 한다(§4.3).
for (const w of ALL) {
  const b = w.morph?.find((m) => m.kind === 'base' && m.part !== w.id && IDS.has(m.part));
  if (b) w.base = b.part;
}

export const WORDS: readonly Word[] = ALL;
export const WORD_BY_ID: Readonly<Record<string, Word>> = Object.fromEntries(ALL.map((w) => [w.id, w]));
